### ISSUE TITLE
cng patch on win8.1 32 bits

### ISSUE THREAD

**Issue by ch0k0bn** [gentilkiwi/mimikatz#10]
on win8.1 32 bits the pattern for cng patch is 
{0xf6, 0x43, 0x1c, 0x02, 0x75} but should be {0xf6, 0x47, 0x1c, 0x02, 0x75}
just patched it and it works well now.
i have not tested with win8.0 but maybe the two different patterns are linked to 32/64 bits instead of win8.0/win8.1 versions ?

**Comment by gentilkiwi** [comment]
At the time of this post, latest version of ncryptprov.dll is 6.3.9600.17415, and pattern is : {0xf6, 0x43, 0x1c, 0x02, 0x75}

**Comment by ch0k0bn** [comment]
after a bunch of update i was still on 6.3.9600.16384 i picked 3 optionnal updates and moved to 17415, everything working well now. Thanks

**Comment by gentilkiwi** [comment]
I did not test on a bunch of files, but {0x1C, 0x02, 0x75} can be enough for both version
