### ISSUE TITLE
Is this 0day true?

### ISSUE THREAD

**Issue by xsaddata** [gentilkiwi/mimikatz#102]
Someone seems that he found the vulnerability of mimikatz by fuzz.
https://www.sec-consult.com/en/blog/2017/09/hack-the-hacker-fuzzing-mimikatz-on-windows-with-winafl-heatmaps-0day/index.html

**Comment by gentilkiwi** [comment]
More information on this little thread: https://twitter.com/gentilkiwi/status/911986789010862080
