### ISSUE TITLE
Error when executing command: lsadump::lsa /inject /name:krbtgt

### ISSUE THREAD

**Issue by forevermirin94** [gentilkiwi/mimikatz#103]
When I'm on the Domain Controller and running Mimikatz(also executed the command Privilege::debug), I try to execute the following command: lsadump::lsa /inject /name:krbtgt 
Unfortunately I'm getting the error:  
RID  : 000001f6 (502)
User : krbtgt
ERROR kull_m_remotelib_create ; RtlCreateUserThread (0xc0000022)

What am I doing wrong?

**Comment by gentilkiwi** [comment]
0xc0000022 is "Access Denied".
Maybe your privilege::debug was not successful, maybe a security product is here, maybe LSA is on a protected process mode...
In all case, maybe think about using: lsadump::dcsync instead ;)
