### ISSUE TITLE
ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)

### ISSUE THREAD

**Issue by sk-y2k** [gentilkiwi/mimikatz#104]
I am using windows 10 x64 Insider Preview Build #16299 RS3 Pre.

  .#####.   mimikatz 2.1.1 (x64) built on Aug 13 2017 17:27:53
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 21 modules * * */

mimikatz(commandline) # sekurlsa::logonPasswords full
ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)

**Comment by gentilkiwi** [comment]
What a bad text format ;) do not hesitate to send full input / output, but:

1. privilege::debug is missing here
2. i don't really work on preview.

**Comment by ShilpeshTrivedi** [comment]
I am using windows 10 x64

  .#####.   mimikatz 2.2.0 (x86) #19041 Aug 16 2020 10:26:09
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::minidump C:\Users\Smit\AppData\Local\Temp\lsass.DMP
Switch to MINIDUMP : 'C:\Users\Smit\AppData\Local\Temp\lsass.DMP'

mimikatz #

mimikatz # sekurlsa::logonpasswords
Opening : 'C:\Users\Smit\AppData\Local\Temp\lsass.DMP' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000002)

mimikatz #

**Comment by BoBo9487** [comment]
use admin's powershell
