### ISSUE TITLE
unable to export cert from ikey e-token

### ISSUE THREAD

**Issue by bullguard01** [gentilkiwi/mimikatz#105]
hello gentil.. i have a rainbow ikey 4000 with my certificate installed in it... mimikatz exports the pfx but I think its without the private key... mimikatz password didn't work .. please assist me .. thank you...

this is the error log

mimikatz # crypto::certificates /export
SER' (0x00010000)
 * Store         : 'My'

 0. bully
	Key Container  : c0ff927666f8b1810b81b5d69d207008_34320939-dd28-4cda-848a-f9d9942808e8
	Provider       : Microsoft Enhanced Cryptographic Provider v1.0
	Provider type  : RSA_FULL (1)
	Type           : AT_KEYEXCHANGE (0x00000001)
	Exportable key : YES
	Key size       : 2048
	Public export  : OK - 'CURRENT_USER_My_0_bully.der'

	Private export : OK - 'CURRENT_USER_My_0_bully.pfx'

 1. bullguard
	Key Container  : p11#4ca0dacae53d2394
	Provider       : eToken Base Cryptographic Provider
	Provider type  : RSA_FULL (1)
# **ERROR kuhl_m_crypto_l_certificates ; CryptAcquireCertificatePrivateKey (0x00000000)**
	Public export  : OK - 'CURRENT_USER_My_1_bullguard.der'

	Private export : OK - 'CURRENT_USER_My_1_bullguard.pfx'

**Comment by gentilkiwi** [comment]
See remarks of: https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#certificates ;)
