### ISSUE TITLE
Potentially unintended consquences of ChangeNTLM

### ISSUE THREAD

**Issue by elitest** [gentilkiwi/mimikatz#106]
Merci pour cet excellent outil!
 
It looks like ChangeNTLM wipes out other "Supplemental Credentials"(as they are called in dcsync) like Kerberos keys.  A colleague(@mrconan) did some testing around this, thinking that there would be implications for Kerberos authentication if the Kerberos keys had been wiped out.  It turns out that if an account is configured to use those keys(e.g. AES for Kerberos authentication), after you ChangeNTLM, the account falls back to RC4, (probably) because all it can use is the NTLM hash that has just been inserted back into the AD database and the rest of the keys are generated from the password, not from the NTLM hash.
 
I wanted to open an issue about it, to first see if you were aware of it and to see if there was a better way to architect ChangeNTLM so that the supplementary credentials could be recreated.  The best Idea I have off the top of my head would be allowing the user to optionally specify the Kerberos keys(perhaps attained through dcsync or manually generating them).

I took a look at the code and it appears that [```SamiChangePasswordUser```](https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kuhl_m_lsadump.c#L2535) is the function in the Windows API that is called.  I couldn't find any documentation on MSDN or otherwise.  Any suggestions on a direction that I could go in with this?

**Comment by gentilkiwi** [comment]
Hello,

This is not unwanted ;) The key of this API is the ability to change user password without knowing its password : only its NTLM hash / RC4 key.
It uses legacy API that does not deal with cleartext passwords, neither AES keys.

Other API are here if you want to deal with passwords :)
