### ISSUE TITLE
Unable to Inject Kerberos tickets in memory

### ISSUE THREAD

**Issue by missingplugin** [gentilkiwi/mimikatz#11]
The client machine on which I want to inject the TGT is non-domain joined system. getting this message after giving the needed command 

http://s17.postimg.org/wyboxc8n3/123.png

What I am doing wrong?

Thanks.

**Comment by gentilkiwi** [comment]
you've "ok", it's injected.
you don't need to run as administrator to inject, and you can avoid "privilege::debug"

**Comment by missingplugin** [comment]
Thanks for the reply.  I verified the kerberos tickets, It was there in the memory,  Even after that I am not able to access domain server resources Perhaps because of the fact that non-domain joined systems uses NTLM authentication by default. I am in process to figure out to enable Kerberos for non-domain joined systems, probably I will need to install Kerberos client software. isn't it? Correct me if I am wrong? 

Thanks Again.

**Comment by gentilkiwi** [comment]
maybe make a real report ? ip / fqdn / mimikatz backlog, etc... ;) even what you try ;)

**Comment by missingplugin** [comment]
Hi, Finally I figured it out, I wasn't doing it exactly right. 

Thanks a alot for your support.

**Comment by gennez** [comment]
Hello,
I am having the same problem and can't figure out what i'm doing wrong... Can you kindly share how you managed to solve it please?
Thanks :)
