### ISSUE TITLE
Release Binaries contain a   V I R U S

### ISSUE THREAD

**Issue by ssrmpc** [gentilkiwi/mimikatz#114]
Dear all

The release binaries provided on [ https://github.com/gentilkiwi/mimikatz/releases]( https://github.com/gentilkiwi/mimikatz/releases ) contain a virus and two trojans. 

Please rebuild the source code and have it run against a anti-virus tool before you upload it.

Thank you
-Marc

**Comment by gentilkiwi** [comment]
![waitno](https://user-images.githubusercontent.com/2307945/33528242-979a86dc-d85d-11e7-867b-66c146868e8c.gif)
https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#check-you-dont-have-a-paranoid-security-product

**Comment by ssrmpc** [comment]
well.... at least the respond-time is excellent. Therefore it's actually less professional to not have the binaries checket regarding the paranoid Windows 10 Defender that complains.

So if you know Windows 10 Defender is complaining... why don't you just write a Little note?

**Comment by cualquierusuarionormal** [comment]
How cute....

**Comment by linxack** [comment]
How cute...🤗

**Comment by xeddmc** [comment]
![](https://media.giphy.com/media/ojkJDqke0p0Hu/giphy.gif)
