### ISSUE TITLE
kull_m_asn1_BitStringFromULONG writes 5 bytes to BerElement

### ISSUE THREAD

**Issue by liav-teichner** [gentilkiwi/mimikatz#115]
I noticed that kull_m_asn1_BitStringFromULONG writes 5 bytes using ber_printf, although a ULONG is only 4 bytes (the first byte written is always 0). I do not know whether this is the correct format, but it seems unlikely.

**Comment by gentilkiwi** [comment]
In fact, you can write numbers in a lots of different ways. When using basic Windows API (not the real ASN1 encoder), it uses long format for number.
Not efficient, but not incorrect :)
