### ISSUE TITLE
Reversible-encrypted passwords on local machine

### ISSUE THREAD

**Issue by gusarov** [gentilkiwi/mimikatz#116]
I found great article about how to extract reversible-encrypted passwords from AD using Mimikatz, but here is short question: how to do the same for a local account? Can't figure that out. In my case I assume that group policy (or some domain admin's batch) defines additional local admin account and I'm curious about the password they use (in fact there is no local session for now, so, lsadump can't help).

**Comment by gentilkiwi** [comment]
As far I know it's not possible for local accounts (and, as the opposit of on the DC, I don't see why it can be needed - so coded by Microsoft).
