### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by moaeddy** [gentilkiwi/mimikatz#117]
i followed this tutorial and its been helpful

http://ultimatepeter.com/mimikatz-windows-powershell-script-for-dumping-local-and-domain-passwords/

but recently, there has been high detection of the powershell script any idea how to obfuscate or make it undetectable by AVs? when running this command its blocked due to detection

**Comment by nest-aka-swan** [comment]
@moaeddy there is a good article on this topic https://www.blackhillsinfosec.com/bypass-anti-virus-run-mimikatz/
