### ISSUE TITLE
build error lasted release 20171220

### ISSUE THREAD

**Issue by johnjohnsp1** [gentilkiwi/mimikatz#118]
Hello Benj,
tried to compile the release of mimikatz but getting this result as output:
```
Error LNK1181 impossibile open the input file 'fltlib.lib'	mimikatz	C:\Temp\mimikatz-2.1.1-20171220\mimikatz\LINK	1	

OS:Microsoft Windows 10 Pro N 
Version: 10.0.16299 build 16299

Microsoft Visual Studio Community 2017 
Versione 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Versione 4.7.02556

Edizione installata: Community

Visual Basic 2017   00369-60000-00001-AA236
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA236
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA236
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.31125.0
ASP.NET and Web Tools 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Gestione pacchetti NuGet   4.5.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web http://docs.nuget.org/.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft MI-Based Debugger   1.0
Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC
Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++
Servizio di linguaggio JavaScript   2.0
Servizio di linguaggio JavaScript
Test Adapter for Boost.Test   1.0
Test Adapter for Google Test   1.0
Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake
```

**Comment by johnjohnsp1** [comment]
I did another try to compile it with another Virtual machine but still getting the same output:

1>------ Build started: Project: mimikatz, Configuration: Release Win32 ------
2>------ Build started: Project: mimilib, Configuration: Release Win32 ------
2>  kappfree.c
2>  kdhcp.c
2>  kdns.c
2>  kfilt.c
2>  kssp.c
2>  kuhl_m_sekurlsa_nt6.c
2>  kuhl_m_sekurlsa_packages.c
2>  kuhl_m_sekurlsa_utils.c
2>  kull_m_rpc.c
2>  kull_m_rpc_ms-credentialkeys.c
2>  kwindbg.c
2>  utils.c
2>     Creating library C:\temp\mimikatz-2.1.1-20171220\Win32\mimilib.lib and object C:\temp\mimikatz-2.1.1-20171220\Win32\mimilib.exp
2>  Generating code
2>  Finished generating code
2>  mimilib.vcxproj -> C:\temp\mimikatz-2.1.1-20171220\Win32\mimilib.dll
3>------ Build started: Project: mimidrv, Configuration: Release Win32 ------
1>  kull_m_asn1.c
1>  kull_m_busylight.c
1>  kull_m_cabinet.c
1>  kull_m_cred.c
1>  kull_m_crypto.c
1>  kull_m_dpapi.c
1>  kull_m_file.c
1>  kull_m_handle.c
1>  kull_m_kernel.c
1>  kull_m_key.c
1>  kull_m_net.c
1>  kull_m_memory.c
1>  kull_m_minidump.c
1>  kull_m_output.c
1>  kull_m_patch.c
1>  kull_m_process.c
1>  kull_m_registry.c
1>  kull_m_remotelib.c
1>  kull_m_sr98.c
1>  kull_m_rpc.c
1>  Compiling...
1>  kull_m_rpc_bkrp.c
1>  kull_m_rpc_dpapi-entries.c
1>  kull_m_rpc_drsr.c
3>  Starting dirs creation...Completed.
3>  BUILD: Compile and Link for x86
3>  
3>  BUILD: Computing Include file dependencies:
3>  
1>  kull_m_rpc_mimicom.c
1>  kull_m_rpc_ms-bkrp_c.c
1>  kull_m_rpc_ms-claims.c
1>  kull_m_rpc_ms-credentialkeys.c
1>  kull_m_rpc_ms-drsr_c.c
1>  kull_m_rpc_ms-pac.c
1>  kull_m_service.c
1>  kull_m_string.c
3>  BUILD: Start time: Wed Dec 20 10:36:39 2017
3>  BUILD: null byte at offset 0x00000003
3>  
3>  BUILD: 972 null bytes in file
3>  
3>  BUILD: Examining c:\temp\mimikatz-2.1.1-20171220\mimidrv directory for files to compile.
3>  
3>      c:\temp\mimikatz-2.1.1-20171220\mimidrv 
3>  
3>  BUILD: Saving c:\winddk\7600.16385.1\build.dat...
3>  
3>  BUILD: Compiling and Linking c:\temp\mimikatz-2.1.1-20171220\mimidrv directory
3>  
1>  kull_m_token.c
3>  _NT_TARGET_VERSION SET TO WS03
3>  Compiling resources - mimidrv.rc
1>  kull_m_xml.c
3>  Compiling - mimidrv.c
3>  Compiling - kkll_m_process.c
1>  mimikatz.c
3>  Compiling - kkll_m_modules.c
3>  Compiling - kkll_m_memory.c
3>  Compiling - kkll_m_ssdt.c
1>  kuhl_m_crypto_extractor.c
3>  Compiling - kkll_m_notify.c
3>  Compiling - kkll_m_filters.c
1>  kuhl_m_crypto_patch.c
3>  Compiling - generating code...
1>  kuhl_m_dpapi.c
3>  Linking Executable - objfre_wnet_x86\i386\mimidrv.sys
3>  BUILD: Finish time: Wed Dec 20 10:36:42 2017
3>  BUILD: Done
3>  
3>  
3>  
3>      10 files compiled - 663 LPS
3>  
3>      1 executable built
3>  
3>  C:\temp\mimikatz-2.1.1-20171220\mimidrv\\objfre_wnet_x86\i386\mimidrv.sys
3>          1 file copiati.
4>------ Build started: Project: mimilove, Configuration: Release Win32 ------
4>  kull_m_kernel.c
1>  kuhl_m_dpapi_oe.c
4>  kull_m_memory.c
1>  kuhl_m_dpapi_chrome.c
4>  kull_m_minidump.c
1>  kuhl_m_dpapi_creds.c
1>  Compiling...
1>  kuhl_m_dpapi_keys.c
4>  kull_m_output.c
1>  kuhl_m_dpapi_wlan.c
4>  kull_m_process.c
4>  kull_m_string.c
1>  kuhl_m_kerberos.c
4>  mimilove.c
1>  kuhl_m_kerberos_ccache.c
1>  kuhl_m_kerberos_claims.c
1>  kuhl_m_kerberos_pac.c
1>  kuhl_m_kerberos_ticket.c
1>  kuhl_m_busylight.c
1>  kuhl_m_crypto.c
1>  kuhl_m_event.c
1>  kuhl_m_iis.c
4>  Generating code
4>  Finished generating code
1>  kuhl_m_kernel.c
4>  mimilove.vcxproj -> C:\temp\mimikatz-2.1.1-20171220\Win32\mimilove.exe
1>  kuhl_m_lsadump.c
1>  kuhl_m_lsadump_remote.c
1>  kuhl_m_misc.c
1>  kuhl_m_net.c
1>  kuhl_m_privilege.c
1>  kuhl_m_process.c
1>  kuhl_m_rpc.c
1>  kuhl_m_service.c
1>  Compiling...
1>  kuhl_m_service_remote.c
1>  kuhl_m_sid.c
1>  kuhl_m_standard.c
1>  kuhl_m_sysenvvalue.c
1>  kuhl_m_token.c
1>  kuhl_m_ts.c
1>  kuhl_m_vault.c
1>  kuhl_m_minesweeper.c
1>  kuhl_m_lsadump_dc.c
1>  kuhl_m_sekurlsa_nt5.c
1>  kuhl_m_sekurlsa_nt6.c
1>  kuhl_m_sekurlsa_nt63.c
1>  kuhl_m_sekurlsa.c
1>  kuhl_m_sekurlsa_utils.c
1>  kuhl_m_sekurlsa_credman.c
1>  kuhl_m_sekurlsa_dpapi.c
1>  kuhl_m_sekurlsa_kerberos.c
1>  kuhl_m_sekurlsa_livessp.c
1>  kuhl_m_sekurlsa_msv1_0.c
1>  kuhl_m_sekurlsa_ssp.c
1>  Compiling...
1>  kuhl_m_sekurlsa_tspkg.c
1>  kuhl_m_sekurlsa_wdigest.c
1>  sqlite3_omit.c
1>LINK : fatal error LNK1181: cannot open input file 'fltlib.lib'
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

OS:Windows 7 Professional
Ver = "6.1.7601.17514"

Microsoft Visual Studio Express 2013 for Windows Desktop
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Desktop Express

Team Explorer for Visual Studio 2013   06157-004-0441005-02320
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06157-004-0441005-02320
Microsoft Visual Basic 2013

Visual C# 2013   06157-004-0441005-02320
Microsoft Visual C# 2013

Visual C++ 2013   06157-004-0441005-02320
Microsoft Visual C++ 2013

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   2.12.0.817
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   12.0.61021.0
Microsoft SQL Server Data Tools

anything I do wrong ? Until this release 20170813 I was able to compile it with VS2017

thanks

**Comment by azzarin** [comment]
I have the same issue. So i follow this one.

**Comment by gentilkiwi** [comment]
It seems recents Visual Studio don't embed `fltlib.lib`.
You can get it from others installation (and push it in the correct `lib` directory of `mimikatz`)

Will (maybe) push it tonight :)

**Comment by johnjohnsp1** [comment]
Thanks for the fast replay Benjamin, made a donation you should receive that from paypal hope it's appreciated.

**Comment by gentilkiwi** [comment]
Haha, thank you, but support is free ;) ;)
