### ISSUE TITLE
 VisualStudio 2017/2015  LNK1181	cannot open input file 'fltlib.lib'	

### ISSUE THREAD

**Issue by mobychien** [gentilkiwi/mimikatz#119]
Can't find the 'fitlib.lib'

**Comment by johnjohnsp1** [comment]
Once you have the WINDDK installed you can grab a copy of that file from this folder: 

C:\WinDDK\7600.16385.1\lib\
or
can just do a search on your system drive  --> folder C:\program files\* for it

**Comment by johnjohnsp1** [comment]
i see Benjamin have updated the repo, just clone it again from source and you will see the file missing is there.

**Comment by gentilkiwi** [comment]
Duplicate with #118 and fixed in 78dba4ede9f70d05872a07717314f3253e0b7f61
