### ISSUE TITLE
French to English translations

### ISSUE THREAD

**Issue by TopazA** [gentilkiwi/mimikatz#12]
Hi,

I'd like to raise a feature request to support both English and French natively. I'd like to offer to spend the time to translate any french text to English. Is there a simple way to extract all text currently being used and to merge translations back in once done? Also happy to translate any documentation that is not yet in English.

Please let me know if this will be possible!

Cheers,
-T

**Comment by gentilkiwi** [comment]
Hi @TopazA !

Thank for your nice idea!
Maybe I missed something, because in version 2.0 I don't see any place where outputs are in French ?

**Comment by TopazA** [comment]
Hey, Not necessarily in the outputs, but in the codebase its-self and any documentation that might be relevant (eg, blog.gentilkiwi.com/securite/mimikatz/overpass-the-hash ) ,ive noticed a few bits and pieces of the code-base (but not display) are still in French. 

This came about after having a chat to someone working on porting the Mimikatz functionality into meterpreter... I figured if i could help two of my favourite projects at once why not? 

Also happy to help contribute to the wiki here: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-remote-execution etc if you'd like?

Cheers,
