### ISSUE TITLE
Mimikatz error I'm not able to run the sekurlsa::logonPasswords full 

### ISSUE THREAD

**Issue by Ab1z3r** [gentilkiwi/mimikatz#124]
I'm having this issue would really appreciate some help.
I have done the following:
1} disabled the UAC.
2} Disabled both Malwarebytes and Windows Defender
3} Excluded the folder from any exclusion  

![screenshot 1](https://user-images.githubusercontent.com/35422222/34915815-5e269ae2-f952-11e7-9cc5-afaf5743a119.png)

**Comment by gentilkiwi** [comment]
I encourage you take a look at the Wiki, especially on the first part: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#check-you-use-latest-mimikatz-version
