### ISSUE TITLE
Issue with Win10 RS4

### ISSUE THREAD

**Issue by richlilly2004** [gentilkiwi/mimikatz#125]
I'm getting the following on RS4, curious if this has been tested. If it matters, I'm also patched for the Intel bug. mimikatz # privilege::debug
Privilege '20' OK

mimikatz # log sekurlsa.log
Using 'sekurlsa.log' for logfile : OK

mimikatz # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

**Comment by gentilkiwi** [comment]
I don't play with insiders builds as it's not used IRL in enterprises.
Latest supported is `Windows NT 10.0 build 16299` (the 1709 one)

**Comment by xcy7e** [comment]
PLEASE remove me from this mailing list as I unsubscribed a few dozen times
without success!!

Am 15.01.2018 03:09 schrieb "Benjamin DELPY" <notifications@github.com>:
