### ISSUE TITLE
NTLM Hash to Password

### ISSUE THREAD

**Issue by skest3qc** [gentilkiwi/mimikatz#126]
Hi,
after running lsadump::sam i can see the local administrator NTLM hash. Can this has be converted to the Windows password.

I need to know the password.

THX

**Comment by bao7uo** [comment]
A hash is non-reversible which means that you cannot convert it back to the password. However, you might be able to crack it, depending on the complexity of the original password. There are free password cracking tools available online. Alternatively if it isn't sensitive, try Googling the hash, or find a site with lists of cracked hashes, perhaps someone has already cracked it and posted the corresponding password online.
