### ISSUE TITLE
rundll32 Mimikatz.dll,main .... return empty

### ISSUE THREAD

**Issue by johnjohnsp1** [gentilkiwi/mimikatz#127]
Hello Benjamin, as a start would like to cheers on your last presentation you and Vincent did on Bluehat IL, really awesome seen it on video and watch carefully the slides !! dcshadow .. unbelievable !!

within this thread I write about a old release you did on Mimikatz as dll.
I tried to compile your latest release 2.1.1-20180203 as Win32/x64 Mimikatz.dll (see output below):

1>------ Inizio compilazione: Progetto: mimikatz, Configurazione: Simple_DLL Win32 ------
2>------ Compilazione ignorata: Progetto: mimilib, Configurazione: Release Win32 ------
2>Progetto non selezionato da compilare per la configurazione della soluzione. 
3>------ Compilazione ignorata: Progetto: mimilove, Configurazione: Release Win32 ------
3>Progetto non selezionato da compilare per la configurazione della soluzione. 
1>kull_m_asn1.c
1>kull_m_busylight.c
1>kull_m_cabinet.c
1>kull_m_cred.c
1>kull_m_crypto.c
1>kull_m_dpapi.c
1>kull_m_file.c
1>kull_m_handle.c
1>kull_m_kernel.c
1>kull_m_key.c
1>kull_m_net.c
1>kull_m_memory.c
1>kull_m_minidump.c
1>kull_m_output.c
1>kull_m_patch.c
1>kull_m_process.c
1>kull_m_registry.c
1>kull_m_remotelib.c
1>kull_m_sr98.c
1>kull_m_rpc.c
1>Compilazione in corso...
1>kull_m_rpc_bkrp.c
1>kull_m_rpc_dpapi-entries.c
1>kull_m_rpc_drsr.c
1>kull_m_rpc_mimicom.c
1>kull_m_rpc_ms-bkrp_c.c
1>kull_m_rpc_ms-claims.c
1>kull_m_rpc_ms-credentialkeys.c
1>kull_m_rpc_ms-drsr_c.c
1>kull_m_rpc_ms-pac.c
1>kull_m_service.c
1>kull_m_string.c
1>kull_m_token.c
1>kull_m_xml.c
1>mimikatz.c
1>kuhl_m_crypto_extractor.c
1>kuhl_m_crypto_patch.c
1>kuhl_m_dpapi.c
1>kuhl_m_dpapi_oe.c
1>kuhl_m_dpapi_chrome.c
1>kuhl_m_dpapi_creds.c
1>Compilazione in corso...
1>kuhl_m_dpapi_keys.c
1>kuhl_m_dpapi_wlan.c
1>kuhl_m_kerberos.c
1>kuhl_m_kerberos_ccache.c
1>kuhl_m_kerberos_claims.c
1>kuhl_m_kerberos_pac.c
1>kuhl_m_kerberos_ticket.c
1>kuhl_m_busylight.c
1>kuhl_m_crypto.c
1>kuhl_m_event.c
1>kuhl_m_iis.c
1>kuhl_m_kernel.c
1>kuhl_m_lsadump.c
1>kuhl_m_lsadump_remote.c
1>kuhl_m_misc.c
1>kuhl_m_net.c
1>kuhl_m_privilege.c
1>kuhl_m_process.c
1>kuhl_m_rpc.c
1>kuhl_m_service.c
1>Compilazione in corso...
1>kuhl_m_service_remote.c
1>kuhl_m_sid.c
1>kuhl_m_standard.c
1>kuhl_m_sysenvvalue.c
1>kuhl_m_token.c
1>kuhl_m_ts.c
1>kuhl_m_vault.c
1>kuhl_m_minesweeper.c
1>kuhl_m_lsadump_dc.c
1>kuhl_m_sekurlsa_nt5.c
1>kuhl_m_sekurlsa_nt6.c
1>kuhl_m_sekurlsa_nt63.c
1>kuhl_m_sekurlsa.c
1>kuhl_m_sekurlsa_utils.c
1>kuhl_m_sekurlsa_credman.c
1>kuhl_m_sekurlsa_dpapi.c
1>kuhl_m_sekurlsa_kerberos.c
1>kuhl_m_sekurlsa_livessp.c
1>kuhl_m_sekurlsa_msv1_0.c
1>kuhl_m_sekurlsa_ssp.c
1>Compilazione in corso...
1>kuhl_m_sekurlsa_tspkg.c
1>kuhl_m_sekurlsa_wdigest.c
1>sqlite3_omit.c
1>   Creazione della libreria C:\Temp\mimikatz\Win32\mimikatz.lib e dell'oggetto C:\Temp\mimikatz\Win32\mimikatz.exp
1>Generazione codice in corso...
1>Generazione codice terminata
1>mimikatz.vcxproj -> C:\Temp\mimikatz\Win32\mimikatz.dll
========== Compilazione: 1 completate, 0 non riuscite, 0 aggiornate, 2 ignorate ==========

but when i issue the command to start it: 

rundll32 Mimikatz.dll,main coffee

as return I have an empty Mimikatz window without anything on it and the cpu get up on rundll32 process at 50% (see attachment)

compiling with the latest release of VStudio2017:

Microsoft Visual Studio Community 2017 
Versione 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Versione 4.7.02556
Edizione installata: Community

Visual Basic 2017   00369-60000-00001-AA236
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA236
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA236
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Gestione pacchetti NuGet   4.5.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web http://docs.nuget.org/.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++

Servizio di linguaggio JavaScript   2.0
Servizio di linguaggio JavaScript

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Consente di usare gli strumenti di test di Visual Studio con unit test scritti per Google Test. Le condizioni d'uso e le comunicazioni relative a terze parti sono disponibili nella directory di installazione dell'estensione.

Visual Studio Tools per CMake   1.0
Using OSX 10.13.3 / 17D47
Versione 10.1.1 (7520154)
Windows 10 Version 1709

BuildNumber  Caption                     OSArchitecture  Version
16299        Microsoft Windows 10 Pro N  64 bit          10.0.16299

seems the only release working without any problems is your binary as 2.1.1-20170720 
even if I try to compile that release I get the same hang on with it. the only way is use your binary

Did you compile it in a different environment by any chance ?

Thanks

<img width="1014" alt="mimikatz dll_hang" src="https://user-images.githubusercontent.com/1888855/35775082-34fbb3f6-0982-11e8-858b-f42804d87560.png">

**Comment by JamesHovious** [comment]
Any solution to this? I've experienced this with release 2.1.0 20180616 and 2.1.1 20180325 when building the "Simple_DLL" solution from source. I've also checked out the 2.1.1-20170720 source and compiled with the same settings, and get the same output as @johnjohnsp1 - so I suppose it may be a VS build setting ?

**Comment by johnjohnsp1** [comment]
thanks for the help Crypto-M3lon with your modify applied to the mimikatz.c code now the generated file mimikatz.dll is working pretty well !!

**Comment by gentilkiwi** [comment]
Thank you all. Did you get errors on Windows 10 too?
Will try to reproduce it on my side, especially with another compiler than WinDDK

**Comment by edermi** [comment]
I am having the same issue on Server 2k12 and Windows 10

**Comment by johnjohnsp1** [comment]
I can confirm applying the modify to the source code mimikatz.c with this reference "@Crypt0-M3lon Crypt0-M3lon referenced this issue on 3 May
 Open
Fix console I/O with Simple DLL build #148" will fix the problem.

The part is at the bottom of the mimikatz.c

void CALLBACK mimikatz_dll(HWND hwnd, HINSTANCE hinst, LPWSTR lpszCmdLine, int nCmdShow)
{
	FILE * pNewStdout;
	FILE * pNewStderr;
	FILE * pNewStdin;

	int argc = 0;
	wchar_t ** argv;

	if (AllocConsole())
	{
		freopen_s(&pNewStdout, "CONOUT$", "w", stdout);
		freopen_s(&pNewStderr, "CONOUT$", "w", stderr);
		freopen_s(&pNewStdin, "CONIN$", "r", stdin);

		if (lpszCmdLine && lstrlenW(lpszCmdLine))
		{
			if (argv = CommandLineToArgvW(lpszCmdLine, &argc))
			{
				wmain(argc, argv);
				LocalFree(argv);
			}
		}
		else wmain(0, NULL);
	}
}
#endif

**Comment by edermi** [comment]
@johnjohnsp1 Indeed, the patch fixes the problem for me. Thank you!

**Comment by antonioCoco** [comment]
i had the same problem compiling and running on Win 10.0.17763 N/D build 17763 using Visual Studio 2017.

Diagnostic info: generated compiler command (cl.exe) Simple_DLL x86 :
```
       C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:classic /Ox /Ob2 /Os /Oy /GL /D WIN32 /D NDEBUG /D _CONSOLE /D _USING_V110_SDK71_ /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /MT /GS- /Gy /fp:fast /fp:except- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Win32\\" /Fd"Win32\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:none ..\modules\kull_m_acr.c ..\modules\kull_m_asn1.c ..\modules\kull_m_busylight.c ..\modules\kull_m_cabinet.c ..\modules\kull_m_cred.c ..\modules\kull_m_crypto.c ..\modules\kull_m_dpapi.c ..\modules\kull_m_file.c ..\modules\kull_m_handle.c ..\modules\kull_m_hid.c ..\modules\kull_m_kernel.c ..\modules\kull_m_key.c ..\modules\kull_m_net.c ..\modules\kull_m_memory.c ..\modules\kull_m_minidump.c ..\modules\kull_m_output.c ..\modules\kull_m_patch.c ..\modules\kull_m_pipe.c ..\modules\kull_m_pn532.c ..\modules\kull_m_process.c ..\modules\kull_m_rdm.c ..\modules\kull_m_registry.c ..\modules\kull_m_remotelib.c ..\modules\kull_m_sr98.c ..\modules\rpc\kull_m_rpc.c ..\modules\rpc\kull_m_rpc_bkrp.c "..\modules\rpc\kull_m_rpc_dpapi-entries.c" ..\modules\rpc\kull_m_rpc_drsr.c ..\modules\rpc\kull_m_rpc_mimicom.c "..\modules\rpc\kull_m_rpc_ms-bkrp_c.c" "..\modules\rpc\kull_m_rpc_ms-claims.c" "..\modules\rpc\kull_m_rpc_ms-credentialkeys.c" "..\modules\rpc\kull_m_rpc_ms-drsr_c.c" "..\modules\rpc\kull_m_rpc_ms-pac.c" ..\modules\kull_m_service.c ..\modules\kull_m_string.c ..\modules\kull_m_token.c ..\modules\kull_m_xml.c mimikatz.c modules\crypto\kuhl_m_crypto_extractor.c modules\crypto\kuhl_m_crypto_patch.c modules\crypto\kuhl_m_crypto_sc.c modules\dpapi\kuhl_m_dpapi.c modules\dpapi\kuhl_m_dpapi_oe.c modules\dpapi\packages\kuhl_m_dpapi_chrome.c modules\dpapi\packages\kuhl_m_dpapi_creds.c modules\dpapi\packages\kuhl_m_dpapi_keys.c modules\dpapi\packages\kuhl_m_dpapi_rdg.c modules\dpapi\packages\kuhl_m_dpapi_ssh.c modules\dpapi\packages\kuhl_m_dpapi_wlan.c modules\kerberos\kuhl_m_kerberos.c modules\kerberos\kuhl_m_kerberos_ccache.c modules\kerberos\kuhl_m_kerberos_claims.c modules\kerberos\kuhl_m_kerberos_pac.c modules\kerberos\kuhl_m_kerberos_ticket.c modules\kuhl_m_acr.c modules\kuhl_m_busylight.c modules\kuhl_m_crypto.c modules\kuhl_m_event.c modules\kuhl_m_iis.c modules\kuhl_m_kernel.c modules\kuhl_m_lsadump.c modules\kuhl_m_lsadump_remote.c modules\kuhl_m_misc.c modules\kuhl_m_net.c modules\kuhl_m_privilege.c modules\kuhl_m_process.c modules\kuhl_m_rdm.c modules\kuhl_m_sr98.c modules\kuhl_m_rpc.c modules\kuhl_m_service.c modules\kuhl_m_service_remote.c modules\kuhl_m_sid.c modules\kuhl_m_standard.c modules\kuhl_m_sysenvvalue.c modules\kuhl_m_token.c modules\kuhl_m_ts.c modules\kuhl_m_vault.c modules\kuhl_m_minesweeper.c modules\lsadump\kuhl_m_lsadump_dc.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt5.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt6.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt63.c modules\sekurlsa\kuhl_m_sekurlsa.c modules\sekurlsa\kuhl_m_sekurlsa_utils.c modules\sekurlsa\packages\kuhl_m_sekurlsa_credman.c modules\sekurlsa\packages\kuhl_m_sekurlsa_dpapi.c modules\sekurlsa\packages\kuhl_m_sekurlsa_kerberos.c modules\sekurlsa\packages\kuhl_m_sekurlsa_livessp.c modules\sekurlsa\packages\kuhl_m_sekurlsa_msv1_0.c modules\sekurlsa\packages\kuhl_m_sekurlsa_ssp.c modules\sekurlsa\packages\kuhl_m_sekurlsa_tspkg.c modules\sekurlsa\packages\kuhl_m_sekurlsa_wdigest.c
```

Diagnostic info: generated compiler command (cl.exe) Simple_DLL x64 :
```
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:classic /Ox /Ob2 /Os /Oy /GL /D WIN32 /D NDEBUG /D _CONSOLE /D _USING_V110_SDK71_ /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /MT /GS- /Gy /fp:fast /fp:except- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\\" /Fd"x64\vc141.pdb" /Gd /TC /FC /errorReport:none ..\modules\kull_m_acr.c ..\modules\kull_m_asn1.c ..\modules\kull_m_busylight.c ..\modules\kull_m_cabinet.c ..\modules\kull_m_cred.c ..\modules\kull_m_crypto.c ..\modules\kull_m_dpapi.c ..\modules\kull_m_file.c ..\modules\kull_m_handle.c ..\modules\kull_m_hid.c ..\modules\kull_m_kernel.c ..\modules\kull_m_key.c ..\modules\kull_m_net.c ..\modules\kull_m_memory.c ..\modules\kull_m_minidump.c ..\modules\kull_m_output.c ..\modules\kull_m_patch.c ..\modules\kull_m_pipe.c ..\modules\kull_m_pn532.c ..\modules\kull_m_process.c ..\modules\kull_m_rdm.c ..\modules\kull_m_registry.c ..\modules\kull_m_remotelib.c ..\modules\kull_m_sr98.c ..\modules\rpc\kull_m_rpc.c ..\modules\rpc\kull_m_rpc_bkrp.c "..\modules\rpc\kull_m_rpc_dpapi-entries.c" ..\modules\rpc\kull_m_rpc_drsr.c ..\modules\rpc\kull_m_rpc_mimicom.c "..\modules\rpc\kull_m_rpc_ms-bkrp_c.c" "..\modules\rpc\kull_m_rpc_ms-claims.c" "..\modules\rpc\kull_m_rpc_ms-credentialkeys.c" "..\modules\rpc\kull_m_rpc_ms-drsr_c.c" "..\modules\rpc\kull_m_rpc_ms-pac.c" ..\modules\kull_m_service.c ..\modules\kull_m_string.c ..\modules\kull_m_token.c ..\modules\kull_m_xml.c mimikatz.c modules\crypto\kuhl_m_crypto_extractor.c modules\crypto\kuhl_m_crypto_patch.c modules\crypto\kuhl_m_crypto_sc.c modules\dpapi\kuhl_m_dpapi.c modules\dpapi\kuhl_m_dpapi_oe.c modules\dpapi\packages\kuhl_m_dpapi_chrome.c modules\dpapi\packages\kuhl_m_dpapi_creds.c modules\dpapi\packages\kuhl_m_dpapi_keys.c modules\dpapi\packages\kuhl_m_dpapi_rdg.c modules\dpapi\packages\kuhl_m_dpapi_ssh.c modules\dpapi\packages\kuhl_m_dpapi_wlan.c modules\kerberos\kuhl_m_kerberos.c modules\kerberos\kuhl_m_kerberos_ccache.c modules\kerberos\kuhl_m_kerberos_claims.c modules\kerberos\kuhl_m_kerberos_pac.c modules\kerberos\kuhl_m_kerberos_ticket.c modules\kuhl_m_acr.c modules\kuhl_m_busylight.c modules\kuhl_m_crypto.c modules\kuhl_m_event.c modules\kuhl_m_iis.c modules\kuhl_m_kernel.c modules\kuhl_m_lsadump.c modules\kuhl_m_lsadump_remote.c modules\kuhl_m_misc.c modules\kuhl_m_net.c modules\kuhl_m_privilege.c modules\kuhl_m_process.c modules\kuhl_m_rdm.c modules\kuhl_m_sr98.c modules\kuhl_m_rpc.c modules\kuhl_m_service.c modules\kuhl_m_service_remote.c modules\kuhl_m_sid.c modules\kuhl_m_standard.c modules\kuhl_m_sysenvvalue.c modules\kuhl_m_token.c modules\kuhl_m_ts.c modules\kuhl_m_vault.c modules\kuhl_m_minesweeper.c modules\lsadump\kuhl_m_lsadump_dc.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt5.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt6.c modules\sekurlsa\crypto\kuhl_m_sekurlsa_nt63.c modules\sekurlsa\kuhl_m_sekurlsa.c modules\sekurlsa\kuhl_m_sekurlsa_utils.c modules\sekurlsa\packages\kuhl_m_sekurlsa_credman.c modules\sekurlsa\packages\kuhl_m_sekurlsa_dpapi.c modules\sekurlsa\packages\kuhl_m_sekurlsa_kerberos.c modules\sekurlsa\packages\kuhl_m_sekurlsa_livessp.c modules\sekurlsa\packages\kuhl_m_sekurlsa_msv1_0.c modules\sekurlsa\packages\kuhl_m_sekurlsa_ssp.c modules\sekurlsa\packages\kuhl_m_sekurlsa_tspkg.c modules\sekurlsa\packages\kuhl_m_sekurlsa_wdigest.c
```

Compiler version:

```
C:\>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe"
Microsoft (R) C/C++ Optimizing Compiler versione 19.16.27027.1 per x86

C:\>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe"
Microsoft (R) C/C++ Optimizing Compiler versione 19.16.27027.1 per x64
```

Applying the patch in #148 solved the problem for me too.
