### ISSUE TITLE
Stop changing release URLs

### ISSUE THREAD

**Issue by wheelerlaw** [gentilkiwi/mimikatz#129]
Self-explanatory. When you release a new version, **stop removing the old ones**.

**Comment by rotateLeft** [comment]
+1. Trying to find an older 2.0 alpha release for testing. Looks like i'm SOL.

**Comment by gentilkiwi** [comment]
![oh-shi](https://user-images.githubusercontent.com/2307945/36312811-f959bef8-132f-11e8-89d4-6d0f0564b770.gif)

**Comment by wheelerlaw** [comment]
The GIF is cute, but would you care to offer an explanation using language like an adult?

**Comment by rotateLeft** [comment]
[Bruce Lee Says Srsly?](https://media.giphy.com/media/MWdOypvVKhOOpn1E4h/giphy.gif)

**Comment by xcy7e** [comment]
It is technically impossible to unsubscribe from this list, right? I tested
a dozen times over a period of 3 months. My Emails regarding this were kept
unanswered.
Can anyone please help me? PLEASE :(

If it's about saving bits, we all should care!

2018-02-16 23:04 GMT+01:00 rotateLeft <notifications@github.com>:
