### ISSUE TITLE
Commit bef58c833cb26c63fd88a1fb4b70d9879f447b61 introduces warnings that prevent building in MSVS

### ISSUE THREAD

**Issue by kmanc** [gentilkiwi/mimikatz#133]
There are two comparisons between ULONG and LONG in SRV_IDL_DRSBind, which result in C4018 warnings [link here](https://msdn.microsoft.com/en-us/library/y92ktdf2.aspx).

Based on the default project settings in VS, this prevents you from building the project.

Proposed fix:
- size changed from ULONG to LONG
- FIELD_OFFSET(DRS_EXTENSIONS_INT, dwFlagsExt) cast as ULONG

**Comment by kmanc** [comment]
Hey @gentilkiwi is there a reason you didn't just merge my PR?

**Comment by gentilkiwi** [comment]
yep, I usually avoid touching Git stuff for simple modification, cause I use SVN behind
