### ISSUE TITLE
lsadump::lsa returns only the local machine SAM and not the domain. 

### ISSUE THREAD

**Issue by wbbigdave** [gentilkiwi/mimikatz#135]
Mimikatz 2.1.1 x86:

I am attempting to perform a golden ticket attack using the following commands

```privilege::debug
Privilege '20' OK

lsadump::lsa /inject /user:krbtgt
Domain: **LOCAL MACHINE NAME** /  **SID**
ERROR kuhl_m_lsadump_lsa; SamLookupNamesInDomain (c0000073)
```
I noticed that when running the commands 

`lsadump::trust`

I was returned the domain to which I am connected. Upon looking into the lsadump module in github i noticed that the method for determining the domains on each of these commands is different. 

lsadump_lsa uses the Win32 function LsaOpenPolicy whereas lasdump_trust uses the POLICY_DNS_DOMAIN_INFO to retrieve the domain name.

**Comment by gentilkiwi** [comment]
On a DC, you can try to use `sekurlsa::krbtgt`
