### ISSUE TITLE
Smart card PIN cache?

### ISSUE THREAD

**Issue by bluikko** [gentilkiwi/mimikatz#139]
I'm not sure how feasible this is but Windows (7 at least) caches the PIN to a smart card, in memory, similarly to passwords. Microsoft states that PIN is cached for Kerberos which would ask several times for PIN on logon were it not cached.

So smart card PIN should be in the memory for same reasons as passwords but I do not know in what format.

I am not aware of much research to this area yet.

**Comment by gentilkiwi** [comment]
I recommend you to test by yourself, or to search?

- https://github.com/gentilkiwi/mimikatz/search?q=kerberos+pin
- https://github.com/gentilkiwi/mimikatz/wiki
