### ISSUE TITLE
Compilation error. 

### ISSUE THREAD

**Issue by jun0s** [gentilkiwi/mimikatz#14]
Error	1	error LNK2001: unresolved external symbol __imp__IsCharAlphaNumericW@4 

thanks!

**Comment by gentilkiwi** [comment]
hmm, well... in what ?
maybe some context =)

**Comment by gentilkiwi** [comment]
I'v added `user32.lib` to mimilove libraries, but keep in mind that Visual Studio 2008 (vc90) is required in Target Build (or `ddk2003` of course)
Visual Studio 2010, and later, don't support well targeting Windows 2000

**Comment by jun0s** [comment]
Sorry for dont give u the details... and i try with VS2013 on win 8.1....now the compilation its complete with ur modifcations... very thanks u benjamin!!!

**Comment by gentilkiwi** [comment]
Don't forget that with Visual Studio 2013... it will not work for Windows 2000 !

**Comment by jun0s** [comment]
yeah... i understood, anyway very few of my targets have win2K servers, thank you benjamin.
