### ISSUE TITLE
Replacing cached domain credentials/mimikatz CQURE edition

### ISSUE THREAD

**Issue by TheWolfH** [gentilkiwi/mimikatz#143]
Hi!

In https://cqureacademy.com/blog/windows-internals/cached-credentials-important-facts, the guys from CQURE show how they replace cached domain credentials using a "/kiwi" switch on lsadump::cache. However, I have not been able to reproduce this with stock mimikatz. Is this a functionality that is exclusive to their (non-public) mimikatz fork?

Best regards and thanks!

**Comment by gentilkiwi** [comment]
you must specify `/user` and (`/password` or `/ntlm`)
