### ISSUE TITLE
Static arrays may lead to overflows

### ISSUE THREAD

**Issue by RootUp** [gentilkiwi/mimikatz#151]
Hi Team, 

During the source code analysis we observed that, 
Statically-sized arrays can be improperly restricted, leading to potential overflows or other issues such as `(CWE-119!/CWE-120). 

I think performing  bounds checking, use functions that limit length, or ensure that the size is larger than the maximum possible length.

`https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kuhl_m_ts.c#L58` 
i.e `wchar_t ip[46];`

Request to please have a look and fix.

Cheers!

**Comment by gentilkiwi** [comment]
I let you read about `RtlIpv6AddressToString` et `RtlIpv4AddressToString`
