### ISSUE TITLE
Windows 10 1803

### ISSUE THREAD

**Issue by Clickbaitcake** [gentilkiwi/mimikatz#153]
sekurlsa::logonpasswords gives error:  _"ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)" in Windows 10 1803 (0S BUILD 17134.48)
Could this be the new LSASS protection being enabled by default?

**Comment by rajiv2790** [comment]
I am using OS and build number, however it is working for me. I am still confused because I enabled credential guard manually, but it is still working. Am I missing something here?

**Comment by meetinnet** [comment]
Windows 10 pro 1803 
Doesn't work for me, passwords are null or Hex.  
M$ changed something on this version ?

**Comment by billybob3** [comment]
Passwords are no longer clear text.  They are NTLM (-m 1000 in hashcat).  Won't take but a minute to crack it.

**Comment by moaeddy** [comment]
@billybob3 can you elaborate what you mean when you said  **-m 1000 in hashcat** ? mine too comes in (null) or hex value

**Comment by billybob3** [comment]
You should now see a 32 character numerical string.  This is an NTLM password.  Use hashcat to crack it with the -m 1000 hash mode flag.  It will take about a minute if you have a password cracking Linux box setup with 4 GPUs.  Longer if you are running a single or older GPUs.
