### ISSUE TITLE
SeTCBPrivilege required?

### ISSUE THREAD

**Issue by rajiv2790** [gentilkiwi/mimikatz#157]
Could someone please explain why mimikatz checks for SeTCBPrivilege? I tried to look at the code, but it seems that TCB privilege is not being used anywhere. Am I missing something?

**Comment by gentilkiwi** [comment]
I don't check for this privilege. What make you think that?
Maybe a Windows API can check that (some process helper check for Debug by eg.)

**Comment by rajiv2790** [comment]
May be. I might have misunderstood then. I thought so because everytime I run mimikatz, windows event log is generated for SeTCBPrivilege check.

Thanks for the response

**Comment by alasta** [comment]
For me, the SeTCBPrivilege is a option which provide if the Service make a PAC (Privilege Account Certificate) validation. It a feature to prevent PAC forgery. 
This link explain this : https://blogs.msdn.microsoft.com/openspecification/2009/04/24/understanding-microsoft-kerberos-pac-validation/
