### ISSUE TITLE
Golden ticket domain event log

### ISSUE THREAD

**Issue by ChrisKing517** [gentilkiwi/mimikatz#16]
Hey,

I have seen some clients increasingly detect golden ticket activity with mimikatz-generated tickets based on the event log login of a domain of "<3 eo.oe ~ ANSSI E>".  I see that this value is hardcoded in located here:

https://github.com/gentilkiwi/mimikatz/blob/42993f51027a0c47ac60e6483b6fd08ff09e9f47/mimikatz/modules/kerberos/kuhl_m_kerberos.c#L589

Is there a reason that this is hardcoded instead of dynamic?  A providable domain name would be awesome here

**Comment by gentilkiwi** [comment]
In fact this is a 'feature': https://twitter.com/gentilkiwi/status/639913689613733888
It helps to get scriptkiddies.

**Comment by ChrisKing517** [comment]
Scriptkiddies vs twitter followers, really.

Its not a huge problem, just recompiling it was pretty simple once we figured out that was the issue.  Not sure I agree with your idea of that as a feature to catch "scriptkiddies".  If you don't want scriptkiddies to use mimikatz, dont release a public binary and force people to compile it themselves.

**Comment by Neo23x0** [comment]
I disagree. 
It was a good idea to leave that value there.

"If you don't want scriptkiddies to use mimikatz, ..."

@Raikia517 You didn't get the intention right.
The idea behind that value was not to avoid(!) script kiddies using mimikatz. 
The idea was to detect(!) script kiddies using mimikatz. 
That's a big difference. 

I liked that value. Even nation state sponsored groups used precompiled mimikatz binaries. (< I am not kidding - that's the sad truth)
