### ISSUE TITLE
Question cracking NTLM(?) hash. Not an issue. Thanks.

### ISSUE THREAD

**Issue by Fireflaker** [gentilkiwi/mimikatz#162]
What command should I use to crack the following hash in windows 10?
They are pulled from WPA2 Enterprise Encryption and I am not sure (probably) is it an NTLMv2.
Thanks!
username:    k.....
     challenge:    e3:5e:f9:cb:b7:ab:1c:b0
     response:    88:3a:c3:d1:14:4b:22:e8:9b:6f:94:79:3f:a1:b4:6b:9c:13:71:bf:66:e4:87:c5
     jtr NETNTLM:    k......
username:    j..........
     challenge:    99:66:3b:ec:fb:df:1e:59
     response:    e2:2f:80:b2:c7:93:82:0e:13:62:c6:e2:00:63:20:61:3d:0d:0c:55:47:79:bb:b8
     jtr NETNTLM:    j.....................c6e2006320613d0d0c554779bbb8
 username:    a......
     challenge:    b3:4e:0e:23:59:83:6e:66
     response:    70:a7:7a:08:d5:a3:7b:9f:8c:46:66:5f:05:03:95:21:d8:e3:49:84:a9:21:90:81
     jtr NETNTLM:    a..................665f05039521d8e34984a9219081﻿

**Comment by robemmerson** [comment]
I would recommend that you check https://hashcat.net/wiki/doku.php?id=example_hashes. The hash type is specified within the information you provided.

**Comment by Fireflaker** [comment]
Thank you!
