### ISSUE TITLE
Error when running lsadump::dcsync

### ISSUE THREAD

**Issue by airhack87** [gentilkiwi/mimikatz#164]
I am getting the following error when I run lsadump::dcsync
i have created a silver ticket and it shows up when I run klist, the machine is domain joined also.
The silver ticket is generated from the hash of the password of an admin account using kerberoasting.
Also tried providing the domain name and DC name.
<img width="297" alt="dcsync-error" src="https://user-images.githubusercontent.com/10479886/42731601-92695d22-8821-11e8-8109-c812028de8f3.png">

**Comment by airhack87** [comment]
yes, just saw that in the windows error code , but the account that I am using is an Domain admin account
https://infosys.beckhoff.com/english.php?content=../content/1033/tf6340_tc3_serial_communication/27021598155389323.html&id=1467695690985181762

**Comment by airhack87** [comment]
In the wireshark trace, I see the following error
krb5_krb_ap_err_modified

**Comment by gentilkiwi** [comment]
> The silver ticket is generated from the hash of the password of an admin account using kerberoasting.

Please, de not mix things not related... Golden or Silver ticket are not related to user accounts (for Silver, it can be only in particular cases, but not for the LDAP service of a DC...)

**Comment by airhack87** [comment]
I found this on @PyroTek3 blog, So are we saying that you cannot pass a silver/service ticket to a AD LDAP service even if its generated from the hash of domain admin ??
Is silver ticket only for non-AD services, and can only be used against the registered SPN from which it was extracted ?
![image](https://user-images.githubusercontent.com/10479886/42736954-98796686-887f-11e8-97d9-09dfef4b4caa.png)

**Comment by vletoux** [comment]
What Benjamin said is that silver ticket is used on the machine that will consume it. You need to embed the DC hash that will process your silver ticket. The admin hash has nothing to do here.

**Comment by airhack87** [comment]
Is it only for the LDAP service that you need the DC computer hash instead of a domain admin hash to generate the silver ticket ?
