### ISSUE TITLE
Password _TBAL_?

### ISSUE THREAD

**Issue by TheNaterz** [gentilkiwi/mimikatz#166]
Hi Benjamin,

Looks like Microsoft pushed a patch out either yesterday or today. Previously, cleartext passwords could be seen under tspkg, but are now replaced by some sort of table reference?

![image](https://user-images.githubusercontent.com/2198138/43340062-57af5fbc-9198-11e8-8bbe-08c6037c6691.png)

The NTLM and SHA1 are still good, just wondering if you had any insight!

Release: 2.1.1-20180616
Windows 10 - Version 1803

**Comment by gentilkiwi** [comment]
Never seen a one like this :)
On my 1803, no reference at all to this.

![image](https://user-images.githubusercontent.com/2307945/43355031-a4c6f98c-9255-11e8-970a-6469a8088beb.png)

Seems to be related to account in the cloud, there is a lots of chance the password is DPAPI protected somewhere or in registry as a "secret".

**Comment by TheNaterz** [comment]
Weird, came back today and couldn't even replicate. If I see it again, I'll keep an eye out for any secrets. Thanks!

**Comment by jagotu** [comment]
@TheNaterz I did some research into TBAL and published my results here: https://vztekoverflow.com/tbal

**Comment by jagotu** [comment]
@gentilkiwi Sample registry hives to test parsing msv1_0 tbal secret:

https://vztekoverflow.com/files/tbal/1709.zip
https://vztekoverflow.com/files/tbal/1803.zip

**Comment by AeroSixNine** [comment]
Can you please tell me how do I exactly resolve this issue? (I am a noob)
