### ISSUE TITLE
win10, it doesn't work. Can you fix it ?

### ISSUE THREAD

**Issue by tosone** [gentilkiwi/mimikatz#17]
win10, it doesn't work. Can you fix it ?

**Comment by wenzhangkai** [comment]
i'm so sorry.i can't fix it 
通过我的 Moto X 发送
On Nov 11, 2015 12:26 PM, Tosone <notifications@github.com> wrote:
>
> win10, it doesn't work. Can you fix it ?
>
> —
> Reply to this email directly or view it on GitHub.
通过我的 Moto X 发送

**Comment by b3mb4m** [comment]
W10 Still not stable.Not worth  write anything ..
