### ISSUE TITLE
Fail to compile 2.1.1 Kitten for Credential Guard using Visual Studio 2017 version 15.7.4

### ISSUE THREAD

**Issue by mobychien** [gentilkiwi/mimikatz#172]
When compiling the latest release using VStudio 2017, I got the following errors -

**Severity	Code	Description	Project	File	Line	Suppression State**
Warning	C4477	'swscanf_s' : format string '%s' requires an argument of type 'unsigned int', but variadic argument 6 has type 'unsigned __int64'	mimikatz	c:\datadisk\mimikatz-2.1.1-20180925\mimikatz\modules\lsadump\kuhl_m_lsadump_dc.c	1772	
Warning	C4477	'swscanf_s' : format string '%[^:]' requires an argument of type 'unsigned int', but variadic argument 2 has type 'unsigned __int64'	mimikatz	c:\datadisk\mimikatz-2.1.1-20180925\mimikatz\modules\lsadump\kuhl_m_lsadump_dc.c	1772	
Warning	C4477	'swscanf_s' : format string '%[^:]' requires an argument of type 'unsigned int', but variadic argument 4 has type 'unsigned __int64'	mimikatz	c:\datadisk\mimikatz-2.1.1-20180925\mimikatz\modules\lsadump\kuhl_m_lsadump_dc.c	1772	
**Error	C2220**	warning treated as error - no 'object' file generated	mimikatz	c:\datadisk\mimikatz-2.1.1-20180925\mimikatz\modules\lsadump\kuhl_m_lsadump_dc.c	1772

**Comment by taherkaraki** [comment]
I fixed it a couple of builds ago by replacing the following line:
ret = swscanf_s(theArg, L"%[^:]:%[^:]:%s", bSalt, ARRAYSIZE(bSalt), bAes256, ARRAYSIZE(bAes256), bAes128, ARRAYSIZE(bAes128));

With:
ret = swscanf_s(theArg, L"%[^:]:%[^:]:%s", bSalt, (UINT)ARRAYSIZE(bSalt), bAes256, (UINT)ARRAYSIZE(bAes256), bAes128, (UINT)ARRAYSIZE(bAes128));


After you fix it, you will get a similar error in another file as far as I remember. So simply do the same.

**Comment by johnjohnsp1** [comment]
Load the project then select Mimikatz on the right side then properties.
Under the menu on the left C/C++ just turn off the warning level by set it up “OFF”

Then just compile
