### ISSUE TITLE
Problem compiling with VS2015

### ISSUE THREAD

**Issue by martclau** [gentilkiwi/mimikatz#184]
Hi,

I get an error when compiling the latest master, the error occurs on this line (modules\lsadump\kuhl_m_lsadump_dc.c(2844)):

				size = ((PDRS_EXTENSIONS_INT) pextClient)->cb >= FIELD_OFFSET(DRS_EXTENSIONS_INT, dwFlagsExt) ? FIELD_OFFSET(DRS_EXTENSIONS_INT, dwFlagsExt) : FIELD_OFFSET(DRS_EXTENSIONS_INT, SiteObjGuid);

I have attached more env information below.

Thanks,
Martin

**Visual Studio**

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90001-89776-AA098
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-90001-89776-AA098
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-90001-89776-AA098
Microsoft Visual Basic 2015

Visual C# 2015   00322-90001-89776-AA098
Microsoft Visual C# 2015

Visual C++ 2015   00322-90001-89776-AA098
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.17.00119.9
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.21111.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.6   14.0.21111.0
Azure App Service Tools v2.9.6

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.2100.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.6.1.6227
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Hive Query Language Service   2.2.2100.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.41104.6

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1701.8
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1701.8

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Build log**

1>------ Build started: Project: mimikatz, Configuration: Release Win32 ------
2>------ Build started: Project: mimilib, Configuration: Release Win32 ------
3>------ Build started: Project: mimilove, Configuration: Release Win32 ------
1>  kull_m_acr.c
2>  kappfree.c
3>  kull_m_kernel.c
1>  kull_m_asn1.c
2>  kdhcp.c
3>  kull_m_memory.c
2>  kdns.c
1>  kull_m_busylight.c
3>  kull_m_minidump.c
2>  kfilt.c
1>  kull_m_cabinet.c
3>  kull_m_output.c
2>  kssp.c
1>  kull_m_cred.c
3>  kull_m_process.c
2>  kuhl_m_sekurlsa_nt6.c
1>  kull_m_crypto.c
3>  kull_m_string.c
2>  kuhl_m_sekurlsa_packages.c
1>  kull_m_dpapi.c
3>  mimilove.c
2>  kuhl_m_sekurlsa_utils.c
1>  kull_m_file.c
2>  kull_m_rpc.c
1>  kull_m_handle.c
2>  kull_m_rpc_ms-credentialkeys.c
1>  kull_m_hid.c
2>  kwindbg.c
1>  kull_m_kernel.c
3>  Generating code
2>  utils.c
3>  Finished generating code
1>  kull_m_key.c
1>  kull_m_net.c
3>  mimilove.vcxproj -> C:\Temp\mimikatz-master\Win32\mimilove.exe
1>  kull_m_memory.c
1>  kull_m_minidump.c
2>     Creating library C:\Temp\mimikatz-master\Win32\mimilib.lib and object C:\Temp\mimikatz-master\Win32\mimilib.exp
2>  Generating code
1>  kull_m_output.c
2>  Finished generating code
1>  kull_m_patch.c
2>  mimilib.vcxproj -> C:\Temp\mimikatz-master\Win32\mimilib.dll
1>  kull_m_pipe.c
1>  kull_m_pn532.c
1>  kull_m_process.c
1>  Compiling...
1>  kull_m_rdm.c
1>  kull_m_registry.c
1>  kull_m_remotelib.c
1>  kull_m_sr98.c
1>  kull_m_rpc.c
1>  kull_m_rpc_bkrp.c
1>  kull_m_rpc_dpapi-entries.c
1>  kull_m_rpc_drsr.c
1>  kull_m_rpc_mimicom.c
1>  kull_m_rpc_ms-bkrp_c.c
1>  kull_m_rpc_ms-claims.c
1>  kull_m_rpc_ms-credentialkeys.c
1>  kull_m_rpc_ms-drsr_c.c
1>  kull_m_rpc_ms-pac.c
1>  kull_m_service.c
1>  kull_m_string.c
1>  kull_m_token.c
1>  kull_m_xml.c
1>  mimikatz.c
1>  kuhl_m_crypto_extractor.c
1>  Compiling...
1>  kuhl_m_crypto_patch.c
1>  kuhl_m_crypto_sc.c
1>  kuhl_m_dpapi.c
1>  kuhl_m_dpapi_oe.c
1>  kuhl_m_dpapi_chrome.c
1>  kuhl_m_dpapi_creds.c
1>  kuhl_m_dpapi_keys.c
1>  kuhl_m_dpapi_rdg.c
1>  kuhl_m_dpapi_ssh.c
1>  kuhl_m_dpapi_wlan.c
1>  kuhl_m_kerberos.c
1>  kuhl_m_kerberos_ccache.c
1>  kuhl_m_kerberos_claims.c
1>  kuhl_m_kerberos_pac.c
1>  kuhl_m_kerberos_ticket.c
1>  kuhl_m_acr.c
1>  kuhl_m_busylight.c
1>  kuhl_m_crypto.c
1>  kuhl_m_event.c
1>  kuhl_m_iis.c
1>  Compiling...
1>  kuhl_m_kernel.c
1>  kuhl_m_lsadump.c
1>  kuhl_m_lsadump_remote.c
1>  kuhl_m_misc.c
1>  kuhl_m_net.c
1>  kuhl_m_privilege.c
1>  kuhl_m_process.c
1>  kuhl_m_rdm.c
1>  kuhl_m_sr98.c
1>  kuhl_m_rpc.c
1>  kuhl_m_service.c
1>  kuhl_m_service_remote.c
1>  kuhl_m_sid.c
1>  kuhl_m_standard.c
1>  kuhl_m_sysenvvalue.c
1>  kuhl_m_token.c
1>  kuhl_m_ts.c
1>  kuhl_m_vault.c
1>  kuhl_m_minesweeper.c
1>  kuhl_m_lsadump_dc.c
1>modules\lsadump\kuhl_m_lsadump_dc.c(2844): error C2220: warning treated as error - no 'object' file generated
1>modules\lsadump\kuhl_m_lsadump_dc.c(2844): warning C4018: '>=': signed/unsigned mismatch
1>modules\lsadump\kuhl_m_lsadump_dc.c(2852): warning C4018: '>=': signed/unsigned mismatch
1>  Compiling...
1>  kuhl_m_sekurlsa_nt5.c
1>  kuhl_m_sekurlsa_nt6.c
1>  kuhl_m_sekurlsa_nt63.c
1>  kuhl_m_sekurlsa.c
1>  kuhl_m_sekurlsa_utils.c
1>  kuhl_m_sekurlsa_credman.c
1>  kuhl_m_sekurlsa_dpapi.c
1>  kuhl_m_sekurlsa_kerberos.c
1>  kuhl_m_sekurlsa_livessp.c
1>  kuhl_m_sekurlsa_msv1_0.c
1>  kuhl_m_sekurlsa_ssp.c
1>  kuhl_m_sekurlsa_tspkg.c
1>  kuhl_m_sekurlsa_wdigest.c
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by emanuelecesari** [comment]
How did you fix it?

**Comment by martclau** [comment]
I haven't tried myself yet - thought it would be picked up by an official developer.

**Comment by mobychien** [comment]
This is the same issue reported in #172 .  Fixed in #172

**Comment by shshzi** [comment]
It seems like https://github.com/gentilkiwi/mimikatz/commit/56d9db738af790a752ebb2e0c3e5d37664405031#diff-3c58a1954f5903deb813027929f50568 introduced a regression (removed the cast to ULONG that was fixed by https://github.com/gentilkiwi/mimikatz/commit/2e4edccee83d63925b9a8861610b1a51276d7432#diff-3c58a1954f5903deb813027929f50568)
