### ISSUE TITLE
Official mirror to gitlab 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [gentilkiwi/mimikatz#192]
Github is Microsoft tool. 
Mimikatz is tool to work with Microsoft Windows.
Would you consider to setup official Gitlab mirror with link from readme?

**Comment by gentilkiwi** [comment]
Your message looks like a Haïku but maybe I did miss the point?

![the point](https://i.kym-cdn.com/photos/images/newsfeed/000/992/397/9c9.gif)

**Comment by dzmitry-lahoda** [comment]
I mean you host tool to export "non exportable" from Windows on site owned by Microsoft. Microsoft may consider cleaning such tools out of Github.

**Comment by gentilkiwi** [comment]
As they also use it, I don't think so.
If they do for whatever reason, I'll move somewhere else.

I already allowed Sourceforge to mirror me: https://sourceforge.net/projects/mimikatz.mirror/
