### ISSUE TITLE
Password does not support special characters such as @

### ISSUE THREAD

**Issue by xz00311** [gentilkiwi/mimikatz#196]
Password does not support special characters such as@
密码不支持特殊字符 例如 @

**Comment by gentilkiwi** [comment]
Change police :)

**Comment by xz00311** [comment]
这是我的名字软件没关系

**Comment by xz00311** [comment]
This is my own software. It doesn't matter if it's not shut down.

**Comment by gentilkiwi** [comment]
![image](https://user-images.githubusercontent.com/2307945/55762940-55408800-5a65-11e9-89f4-976d9ec2ea62.png)
?
