### ISSUE TITLE
Mimikatz didn't work in Win Server 2016 latest version?

### ISSUE THREAD

**Issue by oreilzy** [gentilkiwi/mimikatz#197]
Win Server2016 ,the latest version. LSA Protection was enabled with the value of the registry key “RunAsPPL”=dword:00000001.

I ran mimikatz with the mimidrv.sys, then i used the commonly used “sekurlsa::logonpasswords” command to retrieve hashes and clear text passwords from lsass.exe, but an error occured.

**Comment by oreilzy** [comment]
![20190408215311](https://user-images.githubusercontent.com/46912109/55729596-fff67d80-5a48-11e9-88ff-f05889637ea5.png)

**Comment by gentilkiwi** [comment]
A little: `version /full` even with a `/cab` can help me ;) (with the cab file)

Did you put: `privilege::debug` before `sekurlsa::logonpasswords` ?

**Comment by gentilkiwi** [comment]
![image](https://user-images.githubusercontent.com/2307945/55762248-8d929700-5a62-11e9-952a-dd23eef76dba.png)

> https://github.com/gentilkiwi/mimikatz/releases ;)

**Comment by oreilzy** [comment]
Yes.  i input "privilege::debug" first.
When I tested on a  Windows Server 2012 machine, It worked as expected. However, when I try the same on a Windows Server 2016 (fully patched without antivirus solution and Windows Defender disabled, OS version: 1607,14393.2848), it didn't work.

**Comment by oreilzy** [comment]
![20190409083518](https://user-images.githubusercontent.com/46912109/55766052-5a252c00-5aa5-11e9-8a0e-2a7aee4f6b83.png)

**Comment by oreilzy** [comment]
When i uploaded cab files, the file type wasn't be supported.

**Comment by oreilzy** [comment]
![20190409090114](https://user-images.githubusercontent.com/46912109/55766192-13840180-5aa6-11e9-8424-660f1ed9047b.png)

**Comment by oreilzy** [comment]
![20190409084512](https://user-images.githubusercontent.com/46912109/55766223-4201dc80-5aa6-11e9-8340-cef51217db50.png)

**Comment by oreilzy** [comment]
The latest mimikatz version did work as expected.
thx.
