### ISSUE TITLE
sekurlsa::tickets /export - crash on Windows Server 2012 R2 Evaluation

### ISSUE THREAD

**Issue by maaaaz** [gentilkiwi/mimikatz#20]
Hello Benjamin,

I'm facing a crash with the latest mimikatz when trying to export tickets from the `sekurlsa` module on a Windows Server 2012 R2 Evaluation system.
The command I launched: `mimikatz.exe "privilege::debug" "sekurlsa::tickets /export" "exit"`.
You can find here below:
* The full dump crash
* The WER file
* A dump of my `systeminfo`.  

[Crash_mimikatz_sekurlsa_tickets_export.zip](https://github.com/gentilkiwi/mimikatz/files/72680/Crash_mimikatz_sekurlsa_tickets_export.zip)

Cheers.

**Comment by gentilkiwi** [comment]
Hmm, it seems that with:
- `Hotfix(s):                 3 Hotfix(s) Installed.`
- `ntdll: Timestamp:        Sat Sep 21 10:04:21 2013 (523D5305)`

You did not follow my previous comment ;)
> and latest Windows updates
> https://github.com/gentilkiwi/kekeo/issues/1#issuecomment-167004313

**Comment by maaaaz** [comment]
Héhé that's true :)
The bug still exists on the most up-to-date version (`KB3112336`) of that OS.
[Crash_mimikatz_sekurlsa_tickets_export_update.zip](https://github.com/gentilkiwi/mimikatz/files/75943/Crash_mimikatz_sekurlsa_tickets_export_update.zip)

Happy new year and happy debugging !
Cheers.

**Comment by gentilkiwi** [comment]
Got it :)
My bad: I tested a specific change to Windows 10 build 10586 in the generic NT 6 tickets structures.

- https://github.com/gentilkiwi/mimikatz/commit/1b130574ed78d1d9bf6117b0839056900cb8f816#diff-3d2c2bbb12f82d83088cbdb758f3e152

In fact, it affects all NT 6.x versions, except latest Windows 10.
You can fix it by removing
```
	DWORD		unk10586_d;
	PVOID		unk10586_p;
```
from the current version. I'll commit soon.

**Comment by maaaaz** [comment]
Thanks !
