### ISSUE TITLE
Referring to user via his SID possible?

### ISSUE THREAD

**Issue by Ageraluon** [gentilkiwi/mimikatz#200]
Using the lsadump::ChangeNTLM module, does a switch exist with which we can look up the target user via his SID instead of the user name (/user:)?

Thank you for your help!

**Comment by gentilkiwi** [comment]
Not SID, but RID (last part of SID) is now ok ;)

![image](https://user-images.githubusercontent.com/2307945/56101791-dc8b7100-5f27-11e9-96c6-b6caad46c472.png)

**Comment by Ageraluon** [comment]
Very nice, many thanks :)
