### ISSUE TITLE
The password is null on my computer

### ISSUE THREAD

**Issue by Jason4774** [gentilkiwi/mimikatz#205]
![Snipaste_2019-04-23_01-26-43](https://user-images.githubusercontent.com/19594338/56515474-90b17b00-656a-11e9-97e4-65f1be2e1203.png)
my password is  123.but i get null by using your tool,how to solve it ?can you help me. thanks.

**Comment by gentilkiwi** [comment]
Try: 123 as the password.

Otherwise: https://github.com/gentilkiwi/mimikatz/issues/40#issuecomment-220830921
