### ISSUE TITLE
Why Kiwi can't export TGS tickets when loaded with meterpreter?

### ISSUE THREAD

**Issue by agrawalsmart7** [gentilkiwi/mimikatz#207]
I loaded kiwi with meterpreter then I tried to to find the TGS ticket with this module `kerberos_tickets_list` and then I tried to export them into local disk with the help of `/export` but it failed. 

Can I know why?

**Comment by gentilkiwi** [comment]
Maybe be more prolific ;)
And take a look at: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue

**Comment by agrawalsmart7** [comment]
Yes sir, I will keep it in mind. :) 

When I use mimikatz from your latest release it worked without any problem.

Thanks
