### ISSUE TITLE
Passwords with letters with accents not shown

### ISSUE THREAD

**Issue by MrWolf-to** [gentilkiwi/mimikatz#209]
Hi, I've just tried on my computer (Windows 7 64 bit). My password contains a letter with accent: ì.
Oddly enough, only the first character is shown:
[![mimikatz.png](https://i.postimg.cc/YSKckLQ7/mimikatz.png)](https://postimg.cc/xXRp3Csp)

**Comment by gentilkiwi** [comment]
It depends mainly on the font you're using in the terminal, try to adjust with more modern font for console
(or use: `log` before, and see it in the log file)
