### ISSUE TITLE
Privilege debug error

### ISSUE THREAD

**Issue by orion18** [gentilkiwi/mimikatz#21]
I try to use mimikatz on Windows 10 Pro N (Build 1511) on VirtualBox but it gives me the following error when i use `privilege::debug` and can't begin my analysis
```ERROR kuhl_m_privilege_simple ; RtlAdjustPrivilege (20) c0000061```

**Comment by tazeat** [comment]
Are you running as an admin user?

**Comment by gentilkiwi** [comment]
> Are you running as an admin user?

Yep, see 'Remark': https://github.com/gentilkiwi/mimikatz/wiki/module-~-privilege#debug

**Comment by Yangff** [comment]
I'm using 1511 11099.1000

And, I can run 
```
mimikatz # privilege::debug
Privilege '20' OK
```

However, get `ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list`, when I try to `sekurlsa::logonpasswords`.

**Comment by gentilkiwi** [comment]
This is only the fast ring, not a normal one ;)

**Comment by lizardpunk** [comment]
That kind of error is common when its used the software deep freeze to stop virus and other applications in the registry.

**Comment by lizardpunk** [comment]
Can mimikatz bypass deep freeze? that's the real question i believe ..................

**Comment by gentilkiwi** [comment]
> Can mimikatz bypass deep freeze? that's the real question i believe ..................

#24
