### ISSUE TITLE
Don't delete old releases

### ISSUE THREAD

**Issue by YoloClin** [gentilkiwi/mimikatz#218]
Hey man, love your work!

I'm (probably) dealing with #214 in the current release and would like to try and old version but you remove old releases. I'm compiling the binaries myself, but having old releases would be super handy for a variety of reasons (regression testing, manual fingerprinting, quick access, verified/sane builds, etc).

Would it be possible to not delete previous releases from github when new ones come out? Many other repos expose historic versions so I don't think there's any technical limitations.

Again, thanks for the awesome work!

**Comment by gentilkiwi** [comment]
I try to let n-1, n-2 and sometimes n-3, but otherwise binaries are flagued "very dangerous" and it can be problematic with the repo.. so...

btw, #214 is now fixed ;)

**Comment by pqyptixa** [comment]
> I try to let n-1, n-2 and sometimes n-3, but otherwise binaries are flagued "very dangerous" and it can be problematic with the repo.. so...
> 
> btw, #214 is now fixed ;)

Maybe you could keep them encrypted? Like in passworded zip files.
