### ISSUE TITLE
Cannot export key from wildcard cert

### ISSUE THREAD

**Issue by shawmoo** [gentilkiwi/mimikatz#22]
Hello.  Excellent tool!  

When I export a wildcard certificate from My store it appears to export to a pfx properly but when I try to retrieve the private key it's just blank.

![image](https://cloud.githubusercontent.com/assets/16702198/12323996/5f71844c-ba85-11e5-8c38-ddc37b932c90.png)

But after reimporting I see this (there's no private key):

![image](https://cloud.githubusercontent.com/assets/16702198/12323922/db2aed9a-ba84-11e5-92f1-f4f3ccd3fae5.png)

Sorry for blurring out so much...

**Comment by gentilkiwi** [comment]
Hello !
I don't think the problem is about wildcard (I have a cleaning routine for forbidden chars).
0x80090011 is about object missing... here the private key.
I don't have a lots of test with SChannel provider... but what certutil says to you when you make a test with it ?

**Comment by shawmoo** [comment]
What test should I do with certutil?

**Comment by gentilkiwi** [comment]
As the same user with admin right (like in mimikatz) : `certutil -user -store My`
Also, you can try `crypto::keys` in mimikatz :)

You can paster mimikatz output without printscreen... it's text !

**Comment by shawmoo** [comment]
Ok... certutil says "Encryption test FAILED".  I guess the private key is messed up.  Sorry for bothering you with this.  Thanks though!

**Comment by gentilkiwi** [comment]
maybe you can try: `crypto::keys /provider:MS_DEF_RSA_SCHANNEL_PROV /providertype:PROV_RSA_SCHANNEL`
