### ISSUE TITLE
mimidrv: Error ERROR kull_m_kernel_ioctl ; CreateFile (0x00000002)

### ISSUE THREAD

**Issue by 0x6d69636b** [gentilkiwi/mimikatz#221]
I compiled  _mimidrv_ with Visual Studio 2010 on Windows 7 and signed the driver with an EV Code Signing Certificate. I can load _mimidrv_ on Windows 8.1 Professional, but when I try to remove the protected flag of the LSASS process I get an error message:

```
mimikatz # !+
[*] 'mimidrv' service not present
[+] 'mimidrv' service successfully registered
[+] 'mimidrv' service ACL to everyone
[+] 'mimidrv' service started

mimikatz # !processprotect /remove /process:lsass.exe
Process : lsass.exe
PID 500 -> 00/00 [0-0-0]
ERROR kull_m_kernel_ioctl ; CreateFile (0x00000002)
```
The original driver works as expected and can remove the protected flag. I used mimikatz.exe release 2.2.0-20190813.

**Comment by gentilkiwi** [comment]
I'm pretty sure the driver is not really loaded (as my original one is working and not your)
Just debug to see what drivers are really in memory (windbg or others)
