### ISSUE TITLE
Launch userapp from service from kuhl_m_ts_sessions

### ISSUE THREAD

**Issue by kenkit** [gentilkiwi/mimikatz#222]
Hi, I came accross some code in line https://github.com/gentilkiwi/mimikatz/blob/6436bbe7bc9712fdacc99ca0ca6b0fcfcb853187/mimikatz/modules/kuhl_m_ts.c#L56
I was wondering if it's possible to use this code to launch an app as active user ?
e.g launch gui app from a service ussing the current session id.
Please help I can't find information anywhere about this.
Thanks in advance.

**Comment by gentilkiwi** [comment]
Nop, this module was not for that.
