### ISSUE TITLE
volatility/rekall -> mimikatz

### ISSUE THREAD

**Issue by s0i37** [gentilkiwi/mimikatz#224]
Good day.
I am looking for an approach to using mimikatz with physical dumps. I know that mimikatz supports minidump formats. But when I try convert physical memory to virtual:
```
volatility -f pmem.dmp raw2dmp -O pmem.mdmp
sekurlsa::Minidump pmem.mdmp
sekurlsa::logonPasswords
```
I had an access violation error.
May you please tell me how can I switch to address space of lsass.exe into pmem.mdmp?

**Comment by Beercow** [comment]
After using raw2dmp, load the image into windbg. You can load mimikatz (mimilib.dll) into windbg and use it from there.
http://blog.digital-forensics.it/2014/03/mimikatz-offline-addendum_28.html

**Comment by s0i37** [comment]
Great. Thank you!
But whats about extracting kerberos tickets? Is it posible to extract them from memory dump?

**Comment by s0i37** [comment]
#232
