### ISSUE TITLE
no pass showup

### ISSUE THREAD

**Issue by moaeddy** [gentilkiwi/mimikatz#225]
i have a password set on my PC Windows NT 10.0 build 17134 (arch x64), when run mimikatz it shows NULL and when run version all i can see is

mimikatz 2.2.0 (arch x64)
Windows NT 10.0 build 17134 (arch x64)
msvc 150030729 207

how do i retrieve my PC password

**Comment by supermorkovka** [comment]
Try 
`reg add HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest /v UseLogonCredential /t REG_DWORD /d 1`
Then logoff and login.
Then run mimikatz.

**Comment by moaeddy** [comment]
thanks this really works
