### ISSUE TITLE
mimikatz sid::query /sam:username not working for me

### ISSUE THREAD

**Issue by Papotito123** [gentilkiwi/mimikatz#231]
Hello:
Windows 10 1809 x64 Home.
I try to retrieve user GUID using sid::query  but throws :
mimikatz # sid::query /sam:username
ERROR kull_m_ldap_getRootDomainNamingContext ; ldap_search_s 0x51 (81)

Does this command works in standalone computers or is only for Servers environment?

Thanks.

**Comment by gentilkiwi** [comment]
You can specify a DC with `/system:xxx`, but you must have valid credential in the current mimikatz session (with a runas by eg.)

**Comment by Papotito123** [comment]
Hello:
Thanks for answer.
I'm not in Domain environment 
So,my question is if sid::query /sam:username command can be run for a single computer.
Or there's another way to get users GUID for running OS and for users in offline Windows?

Thanks.
