### ISSUE TITLE
mimikatz not able to dump private keys

### ISSUE THREAD

**Issue by 0c0c0c0c** [gentilkiwi/mimikatz#239]
I'm using the following command to create a self signed certificate with 'KeyExportPolicy Nonexportable' to protect private key dumping. 

Link - https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

PS C:\>New-SelfSignedCertificate -Type Custom -Subject "CN=Patti Fuller,OU=UserAccounts,DC=corp,DC=contoso,DC=com" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2","2.5.29.17={text}upn=pattifuller@contoso.com") -KeyUsage DigitalSignature -KeyExportPolicy Nonexportable -KeyAlgorithm ECDSA_nistP256 -CurveExport CurveName -CertStoreLocation "Cert:\CurrentUser\My"

Output from mimikatz (Windows 10) -

        Key Container  : te-f168b88b-f398-4464-82ce-e9c588cf4fbb
        Provider       : Microsoft Software Key Storage Provider
        Provider type  : cng (0)
        Type           : CNG Key (0xffffffff)
        Exportable key : NO
        Key size       : 2048
        Public export  : OK - 'CURRENT_USER_MY_1_Patti Fuller1.der'
ERROR kull_m_crypto_exportPfx ; PFXExportCertStoreEx (0x8009000b)
        Private export : KO - ERROR kuhl_m_crypto_exportCert ; Export / CreateFile (0x8009000b)

I have tried using 'crypto::capi' and 'crypto::cng' to patch non-exportable keys but no luck.

**Comment by gentilkiwi** [comment]
I think I modify the provider only to deal with RSA keys

**Comment by 0c0c0c0c** [comment]
Commandline Explanation - 

This example creates a self-signed client authentication certificate in the user MY store. The certificate uses the default provider, which is the Microsoft Software Key Storage Provider. The certificate uses an RSA asymmetric key with a key size of 2048 bits. The certificate has a subject alternative name of pattifuller@contoso.com.

It using RSA keys.

 What modifications should I make in the command to make it work?

**Comment by 0c0c0c0c** [comment]
Thanks for the reply. I tried this -
New-SelfSignedCertificate -Type Custom -Subject "CN=Patti Fuller,OU=UserAccounts,DC=corp,DC=contoso,DC=com" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2","2.5.29.17={text}upn=pattifuller@contoso.com") -KeyUsage DigitalSignature -KeyExportPolicy Nonexportable -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation "Cert:\CurrentUser\My"

Same Error!!

**Comment by gentilkiwi** [comment]
You may have a Windows version I don't support (like preview/insider)
```
    3. te-8786dad1-e390-4931-bb82-dc0ec4f5c16a
    f025aed2ac8736579892da4f9ed19134_74dd92d9-27f8-4d98-95dc-d991e1b151e9
        Exportable key : NO
        Key size       : 2048
        Private export : OK - 'user_cng_3_te-8786dad1-e390-4931-bb82-dc0ec4f5c16a.pvk'
```

What is the output of: `version /full` ?

**Comment by 0c0c0c0c** [comment]
I'm using -
crypto::capi
crypto::certificates /export /store:MY /systemstore:CURRENT_USER

Should I be using crypto::keys instead??

**Comment by gentilkiwi** [comment]
It's the same result. What's your full output of version ?

**Comment by 0c0c0c0c** [comment]
mimikatz # version /full

mimikatz 2.2.0 (arch x86)
Windows NT 10.0 build 18362 (arch x64)
msvc 150030729 207

msv1_0.dll      : 10.0.18362.418
tspkg.dll       : 10.0.18362.1
wdigest.dll     : 10.0.18362.1
kerberos.dll    : 10.0.18362.387
cryptdll.dll    : 10.0.18362.113
rsaenh.dll      : 10.0.18362.1
ncrypt.dll      : 10.0.18362.1
ncryptprov.dll  : 10.0.18362.295

**Comment by gentilkiwi** [comment]
it seems you use a Win32 version on a x64 Windows... maybe reboot and try again the full chain, with the full log...

**Comment by 0c0c0c0c** [comment]
Thanks! It works
