### ISSUE TITLE
The specified log name doesn't work from command line as string(.bat)

### ISSUE THREAD

**Issue by GjBrutello** [gentilkiwi/mimikatz#242]
![log](https://user-images.githubusercontent.com/50217444/70323293-9ee0ad00-1856-11ea-897f-c505a92ef8b0.png)

**Comment by Papotito123** [comment]
Hello:
Did you try;
mimikatz "log other.log" privilege::debug sekurlsa::logonpasswords exit

When running commands with spaces,have to be enclosed in " " .

Also seems is more than 1 space between other commands.

You can substitute other.log with something like, %username%.log , and have the account name.

**Comment by GjBrutello** [comment]
> 
> 
> Hello:
> Did you try;
> mimikatz "log other.log" privilege::debug sekurlsa::logonpasswords exit
> 
> When running commands with spaces,have to be enclosed in " " .
> 
> Also seems is more than 1 space between other commands.
> 
> You can substitute other.log with something like, %username%.log , and have the account name.

Thanks bro, I just forgot about this rule . Now everything is ok.
```
@echo off
cd /d "%~dp0"
set log=%computername%-system.log
mimikatz "log %log%" privilege::debug sekurlsa::logonpasswords exit privilege::debug  sekurlsa::logonpasswords exit
start "" notepad.exe %log%
goto :eof
```
