### ISSUE TITLE
Visual Studio 2017 build error

### ISSUE THREAD

**Issue by Cx01N** [gentilkiwi/mimikatz#243]
I am receiving the following error when compiling 2.2.0 20191125 DPAPI & Crypto stuff. It seems that the lines with 
`if(dataLen >= FIELD_OFFSET(KULL_M_DPAPI_BLOB, dwMasterKeyVersion))` in kuhl_m_dpapi_creds.c seem to be causing the issue. I was able to fix it with changing the lines from `>=` to `>>=`

![image](https://user-images.githubusercontent.com/20302208/70382844-9e5c1b00-1917-11ea-937d-acfc6e3f316b.png)

**Comment by tigros** [comment]
haha! yikes!
