### ISSUE TITLE
Memory leak errors and unused pointers

### ISSUE THREAD

**Issue by 17arnab17** [gentilkiwi/mimikatz#244]
While analysing the code to fork it into my side, i was checking with valgrind and cppcheck and could notice a lot of memory leaks and pointers not freed upon failure. Please have a look at a sample below:

[modules/sqlite3_omit.c:22845]: (error) Memory leak: p
[modules/sqlite3_omit.c:22910]: (error) Common realloc mistake: 'p' nulled but not freed upon failure

**Comment by gentilkiwi** [comment]
sqlite3* is from SQLite project :')
