### ISSUE TITLE
Win 8.1 sekurlsa problem

### ISSUE THREAD

**Issue by awhitex** [gentilkiwi/mimikatz#25]
On Windows 8.1 x86 (6.3.9600) running under SYSTEM even with minidump from this machine got error:
sekurlsa::logonpasswords
**ERROR kuhl_m_sekurlsa_acquireLSA ; Key import**

**Comment by awhitex** [comment]
But **lsadump::cache**, **lsadump::sam** works! Also have this issue on other Win8.1 hosts in same network

**Comment by gentilkiwi** [comment]
Well, I'm surprised... with an up to date Windows 8.1, and current mimikatz:
![mimikatz_8 1_x86](https://cloud.githubusercontent.com/assets/2307945/13475930/b97ab628-e0c5-11e5-81ce-6a7a3d9bdefc.png)
![mimikatz_8 1_x64](https://cloud.githubusercontent.com/assets/2307945/13475946/c579a196-e0c5-11e5-896b-1b362c1df07f.png)

**Comment by awhitex** [comment]
Sure, I also tested in the my lab on an updated Win8.1 and everything worked well, but in one other network on all Win8.1 machines I got the same error (ERROR kuhl_m_sekurlsa_acquireLSA ; Key import). Maybe I should provide some additional detail from these machines?

**Comment by gentilkiwi** [comment]
Yep, like the diff between your lab and others computers ;)
