### ISSUE TITLE
x86 cannot access x64 process

### ISSUE THREAD

**Issue by Epic1033** [gentilkiwi/mimikatz#252]
So I'm new to mimikatz and cyberseq in general. I've done the mimikatz sekurlsa::logonpasswords and every time I do it and on every computer it says ERROR kuhl_m_sekurlsa_acquireLSA ; mimikatz x86 cannot access x64 process. I'm on the latest version btw. I've done log and privilege debug. Can't find anything about this on google.

**Comment by Papotito123** [comment]
Hello:
Be sure you are running mimikatz according your OS arch.
Sounds like running mimikatz 32 bit in a x64 OS.Running log and then sekurlsa::logonpasswords is suffice.I run latest mimikatz in Windows 10 1809 64 bit and do very well.

**Comment by Epic1033** [comment]
wait so where do I get the 64 bit version?

**Comment by Epic1033** [comment]
Hey I ran the 64 bit version, but all the passwords are now null, or I just get hashes. Does mimikatz not get you the password in plane text.

Here is the output:

Authentication Id : 0 ; 428397 (00000000:0006896d)
Session           : Interactive from 1
User Name         : ericm
Domain            : DESKTOP-7PLKS18
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:37 PM
SID               : S-1-5-21-612572412-3442448785-3554022054-1001
        msv :
         [00000003] Primary
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * NTLM     : a2960f3e5648d6e1898bbbb7a0c46e3b
         * SHA1     : bd3b73ebd98305f18d789d759802defb7d1fa4ac
        tspkg :
        wdigest :
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        kerberos :
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 428353 (00000000:00068941)
Session           : Interactive from 1
User Name         : ericm
Domain            : DESKTOP-7PLKS18
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:37 PM
SID               : S-1-5-21-612572412-3442448785-3554022054-1001
        msv :
         [00000003] Primary
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * NTLM     : a2960f3e5648d6e1898bbbb7a0c46e3b
         * SHA1     : bd3b73ebd98305f18d789d759802defb7d1fa4ac
        tspkg :
        wdigest :
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        kerberos :
         * Username : ericm7000@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 140136 (00000000:00022368)
Session           : Interactive from 1
User Name         : DWM-1
Domain            : Window Manager
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-90-0-1
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 140113 (00000000:00022351)
Session           : Interactive from 1
User Name         : DWM-1
Domain            : Window Manager
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-90-0-1
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 996 (00000000:000003e4)
Session           : Service from 0
User Name         : DESKTOP-7PLKS18$
Domain            : WORKGROUP
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-20
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
         * Username : desktop-7plks18$
         * Domain   : WORKGROUP
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 107255 (00000000:0001a2f7)
Session           : Interactive from 1
User Name         : UMFD-1
Domain            : Font Driver Host
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-96-0-1
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 997 (00000000:000003e5)
Session           : Service from 0
User Name         : LOCAL SERVICE
Domain            : NT AUTHORITY
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-19
        msv :
        tspkg :
        wdigest :
         * Username : (null)
         * Domain   : (null)
         * Password : (null)
        kerberos :
         * Username : (null)
         * Domain   : (null)
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 99235 (00000000:000183a3)
Session           : Interactive from 0
User Name         : UMFD-0
Domain            : Font Driver Host
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-96-0-0
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 98335 (00000000:0001801f)
Session           : UndefinedLogonType from 0
User Name         : (null)
Domain            : (null)
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               :
        msv :
        tspkg :
        wdigest :
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 999 (00000000:000003e7)
Session           : UndefinedLogonType from 0
User Name         : DESKTOP-7PLKS18$
Domain            : WORKGROUP
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-18
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
         * Username : desktop-7plks18$
         * Domain   : WORKGROUP
         * Password : (null)
        ssp :
        credman :

**Comment by Epic1033** [comment]
Hey I ran the 64 bit version but all the passwords were null, or just hashes. Does Mimikatz not give you the password in plane text?

Here is the output:

Authentication Id : 0 ; 428397 (00000000:0006896d)
Session           : Interactive from 1
User Name         : ericm
Domain            : DESKTOP-7PLKS18
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:37 PM
SID               : S-1-5-21-612572412-3442448785-3554022054-1001
        msv :
         [00000003] Primary
         * Username : reeeeeeeeeeeee@gmail.com
         * Domain   : MicrosoftAccount
         * NTLM     : a2960f3e5648d6e1898bbbb7a0c46e3b
         * SHA1     : bd3b73ebd98305f18d789d759802defb7d1fa4ac
        tspkg :
        wdigest :
         * Username : reeeeeeeeeeeee@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        kerberos :
         * Username : reeeeeeeee@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 428353 (00000000:00068941)
Session           : Interactive from 1
User Name         : reee
Domain            : DESKTOP-7PLKS18
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:37 PM
SID               : S-1-5-21-612572412-3442448785-3554022054-1001
        msv :
         [00000003] Primary
         * Username : reeee@gmail.com
         * Domain   : MicrosoftAccount
         * NTLM     : a2960f3e5648d6e1898bbbb7a0c46e3b
         * SHA1     : bd3b73ebd98305f18d789d759802defb7d1fa4ac
        tspkg :
        wdigest :
         * Username : re@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        kerberos :
         * Username : reeee@gmail.com
         * Domain   : MicrosoftAccount
         * Password : (null)
        ssp :
        credman :

Authentication Id : 0 ; 140136 (00000000:00022368)
Session           : Interactive from 1
User Name         : DWM-1
Domain            : Window Manager
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-90-0-1
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 0 ; 140113 (00000000:00022351)
Session           : Interactive from 1
User Name         : DWM-1
Domain            : Window Manager
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-90-0-1
        msv :
        tspkg :
        wdigest :
         * Username : DESKTOP-7PLKS18$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : no clue what this even does so I'll put text over it
Session           : Service from 0
User Name         : mens-asd$
Domain            : WORKGROUP
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : idk what this does either
        msv :
        tspkg :
        wdigest :
         * Username : rereeee$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
         * Username : mens$
         * Domain   : WORKGROUP
         * Password : (null)
        ssp :
        credman :

Authentication Id : asd
Session           : Interactive from 1
User Name         : UMFD-1
Domain            : Font Driver Host
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-96-0-1
        msv :
        tspkg :
        wdigest :
         * Username : 4124124124124$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 124124124124124124124
Session           : Service from 0
User Name         : LOCAL SERVICE
Domain            : NT AUTHORITY
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-19
        msv :
        tspkg :
        wdigest :
         * Username : (null)
         * Domain   : (null)
         * Password : (null)
        kerberos :
         * Username : (null)
         * Domain   : (null)
         * Password : (null)
        ssp :
        credman :

Authentication Id :124124124124124124
Session           : Interactive from 0
User Name         : idk
Domain            : Font Driver Host
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-96-0-0
        msv :
        tspkg :
        wdigest :
         * Username : 141241241241$
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
        ssp :
        credman :

Authentication Id : 1241241241243434556t
Session           : UndefinedLogonType from 0
User Name         : (null)
Domain            : (null)
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               :
        msv :
        tspkg :
        wdigest :
        kerberos :
        ssp :
        credman :

Authentication Id : 42424
Session           : UndefinedLogonType from 0
User Name         : DESKTOP-7PLKS18$
Domain            : WORKGROUP
Logon Server      : (null)
Logon Time        : 2020-01-07 10:15:27 PM
SID               : S-1-5-18
        msv :
        tspkg :
        wdigest :
         * Username : 1124124
         * Domain   : WORKGROUP
         * Password : (null)
        kerberos :
         * Username : 7676767676
        * Domain   : WORKGROUP
         * Password : (null)
        ssp :
        credman :

**Comment by Epic1033** [comment]
Hey I found the 64 bit version and ran it, but all the passwords come up as null. The ones that do show  passwords only show hashes. Does mimikatz not show the password in clear text? Or am I doing something wrong? I typed privilege debug than Serkurlsa::logonPasswords

**Comment by Papotito123** [comment]
Hello;
From  Windows 10 earlier versions user passwords are not saved in plain text anymore.
In latest Windows 10 user passwords are also not saved in lsass process.
But you can get NTLM hashes that you can decrypt.But can be a hard and consuming process.
Also user Microsoft login can't be retrieved.

Thanks.

**Comment by gentilkiwi** [comment]
https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#be-logic ;)
