### ISSUE TITLE
[Feature] Can I create a log file for the operations done on Mimikatz?

### ISSUE THREAD

**Issue by ismailtasdelen** [gentilkiwi/mimikatz#254]
Hi @gentilkiwi ,

Can I create a log file for the operations done on Mimikatz? This may be necessary. If I get a copy of my operations on Mimikatz, I won't have to copy through the terminal.

**Comment by Papotito123** [comment]
Hello:
Use as this;
   cmd(Run As  Admin) > cd path/of/mimikatz.exe

   mimikatz.exe ""privilege::debug"" ""sekurlsa::logonpasswords"" exit >> log.txt

This will output mimikatz cmd output also with mimikatz logo.

**Comment by ismailtasdelen** [comment]
Thanks @Papotito123 👍
