### ISSUE TITLE
Abstract the console from the core library

### ISSUE THREAD

**Issue by OJ** [gentilkiwi/mimikatz#26]
Hi Ben!

I wanted to start a discussion about how we might work together to separate the UX/Console code from the core library that makes up the Mimikatz functionality. From there, I aim to wrap up the core library as a Meterpreter extension (ie. the `kiwi` extension that you already know!).

The reason I'm keen to do this here is because keeping the code in sync is a tough gig, especially given the rate at which you churn out features!

Are you open to teaming up and working on teasing the bits apart a little so that it's easier for us poor MSF folk to keep your latest and greatest stuff in Metasploit?

Cheers for all your awesome work, as always.

**Comment by gentilkiwi** [comment]
Hi Oliver :)

To help me understand how all of that works in a ideal Metasploit/Meterpret world ; have you any clean/quick example of module for me?
With functions you can call, and of course with results -- but you're right... in the clean way that Meterpreter can understand :)

Thank you for your nice words, I'm pretty sure you wand all Busylight colors in Meterpreter now ;)

Cheers !

**Comment by OJ** [comment]
Hey Ben!

Thanks for the response.

So basically what I'd love to get is a "Mimikatz API". The console version of Mimikatz would just invoke the API and print it to screen. The Meterp version would translate the structures to TLV packets to send back to MSF.

I realise that this can go quite deep given that there are a few low-level printf() calls. But I am more than happy to help make this happen.

I think I should throw together some sort of design suggestions for you to read so that we can get to a point of agreement. But I think if we could make it so that there is a core `mimikatz.lib`, and that lib is linked into a both a console version and others such as Meterp, then that'd be awesome.

Thanks for being open to the discussion!

**Comment by t0b1nux** [comment]
Maybe this would imply creating strucs for storing answers from the API (or even linked chains of structs, like a list of credentials structures for the answer of sekurlsa::logonPasswords) ? I agree it would be better to be able to embed just a "sane" mimikatz library without all the user interact part (e.g. For automated test). It would allow people to get mimikatz results and format them to JSON or Toml or whatever, and use it with different tools latter.

**Comment by gentilkiwi** [comment]
@OJ mades all the magic!

**Comment by OJ** [comment]
🙌
