### ISSUE TITLE
Question around private key exports

### ISSUE THREAD

**Issue by 0c0c0c0c** [gentilkiwi/mimikatz#260]
Does patching and exporting of non-exportable private keys (using crypto::cng) work when the keys are created using any one of the following flags -

#define NCRYPT_PREFER_VIRTUAL_ISOLATION_FLAG	0x10000
#define NCRYPT_USE_VIRTUAL_ISOLATION_FLAG		0x20000
#define NCRYPT_USE_PER_BOOT_KEY_FLAG			0x40000

**Comment by 0c0c0c0c** [comment]
Hello, any update on above?

**Comment by gentilkiwi** [comment]
No, keys are protected by VSM, not Key Isolation service.
