### ISSUE TITLE
W10 x64 1809 17763.1039 Win Defender off but cannot patch cng

### ISSUE THREAD

**Issue by scerazy** [gentilkiwi/mimikatz#269]
Only get:
KO - ERROR kuhl_m_crypto_exportCert ; Export / CreateFile (0x8009000b)

Windows Defender service is stopped (using nsudo as TrustedInstaller)

Trying to export user certificate with NO exportable key

During tries I got it just once (and never again, with multiple reboots):
mimikatz # crypto::cng
"KeyIso" service patched

Each next time it failed to do so

but even when it patched (that once) it failed to export key.
Anything to do with TPM possibly?

**Comment by gentilkiwi** [comment]
Without details about your commands and the output, will be hard :)

**Comment by scerazy** [comment]
crypto::cng
ERROR kull_m_patch_genericProcessOrServiceFromBuild ; kull_m_patch (0x00000005)

**Comment by gentilkiwi** [comment]
The command line and the output of your command (to export)

**Comment by scerazy** [comment]
`mimikatz # crypto::certificates /store:my /export
 * System Store  : 'CURRENT_USER' (0x00010000)
 * Store         : 'my'

 0. Name Surname
    Subject  : 
    Issuer   : 
    Serial   : 3050000003008cca164c55d21ef23050000040
    Algorithm: 1.2.840.113549.1.1.1 (RSA)
    Validity : 28/02/2020 17:20:40 -> 27/02/2021 17:20:40
    UPN      : **********.**@*****.org
    Hash SHA1: ff3406302c2cf64018883de5f1c6131d3b2b540a
        Key Container  : te-VPNUsers-be61d507-27c3-4d70-88e0-4a1a85d9f814
        Provider       : Microsoft Software Key Storage Provider
        Provider type  : cng (0)
        Type           : CNG Key (0xffffffff)
        |Provider name : Microsoft Software Key Storage Provider
        |Implementation: NCRYPT_IMPL_SOFTWARE_FLAG ;
        Key Container  : te-VPNUsers-be61d507-27c3-4d70-88e0-4a1a85d9f814
        Unique name    : 1fd4913fc8e59087f7e92c4275846d04_f81db635-3976-4f45-9c6a-9b6825b2d145
        Algorithm      : RSA
        Key size       : 2048 (0x00000800)
        Export policy  : 00000000 ( )
        Exportable key : NO
        LSA isolation  : NO
        Public export  : OK - 'CURRENT_USER_my_0_Name Surname.der'
        Private export : ERROR kull_m_crypto_exportPfx ; PFXExportCertStoreEx/kull_m_file_writeData (0x8009000b)


mimikatz #
`

**Comment by gentilkiwi** [comment]
Use: `privilege::debug` before, like in https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#cng

**Comment by scerazy** [comment]
Nice, **that** with usage of the toggledefnder.bat makes the .pfx export perfectly fine!
Please close
