### ISSUE TITLE
Unable to export private key

### ISSUE THREAD

**Issue by sltang** [gentilkiwi/mimikatz#27]
Hi,

I have a certificate with a private key marked as non-exportable. I use mimikatz to export the certificate:

```
mimikatz # crypto::certificates /export
 * System Store  : 'CURRENT_USER' (0x00010000)
 * Store         : 'My'

0. xxxxx
        Key Container  : !A42A9E45958D92C643D542A3C4B619AF21FC3CF7
        Provider       : Symantec PKI Client CSP
        Provider type  : RSA_FULL (1)
        Type           : AT_KEYEXCHANGE (0x00000001)
        Exportable key : NO
        Key size       : 2048
        Public export  : OK - 'CURRENT_USER_My_0_ xxxxx.der'
        Private export : OK - 'CURRENT_USER_My_0_ xxxxx.pfx'
```

I then use openssl to extract the public certificate and private key:

```
openssl pkcs12 -in my.pfx -out cert.pem -nokeys
openssl pkcs12 -in my.pfx -out key.pem -nocerts
```

The resulting cert.pem looks fine but key.pem has size 0. When I run:

`certutil -user -store My`

I get the following output:

```
My
================ Certificate 0 ================
Serial Number: 73f1964b9c30379490fa6db433e9ea96
Issuer: CN=xxxxx, O=xxxxx
 NotBefore: 2/19/2016 4:00 PM
 NotAfter: 2/19/2017 3:59 PM
Subject: OU=MULTI-ALLOWED, OU=RACERT, CN=xxxxx, CN=xxxxx
Non-root Certificate
Template:
Cert Hash(sha1): a4 2a 9e 45 95 8d 92 c6 43 d5 42 a3 c4 b6 19 af 21 fc 3c f7
  Key Container = !A42A9E45958D92C643D542A3C4B619AF21FC3CF7
  Provider = Symantec PKI Client CSP
Private key is NOT exportable
ERROR: Could not verify certificate public key against private key
CertUtil: -store command completed successfully.
```
Do you know why I cannot export the private key? Thanks.

**Comment by gentilkiwi** [comment]
It seems to be a SmartCard/Token certificate (not a Microsoft CSP, but a Symantec one).
I've seen multiple times incorrect private export status when SmartCard (https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#certificates)

Your certutil result make me think you don't have the SmartCard/Token inserted ;)

**Comment by sltang** [comment]
Hi,
When I enrolled and installed the certificate, I did not use a smart card.
I use the certificate without a smart card. Does it mean it is not a smart
card certificate?

**Comment by gentilkiwi** [comment]
So it seems to be a software one :)
But I know nothing about "Symantec PKI Client CSP", and I cannot test it, so it seems you're stuck with this non-based Microsoft CSP!

**Comment by dlenski** [comment]
I've had the exact same problem as @sltang: I can only export the certificate, but not the private key, from Symantec PKI Client. (MimiKatz 2.1 and Symantec PKI Client v2.15)

According to [this blog post from August 2014](http://theunixtips.com/export-nonexporteable-private-certificate-from-symantec-pki/), it was possible to export the private keys from Symantec PKI Client… possibly Symantec has changed something about the way that they store the private keys :-1:
