### ISSUE TITLE
Cant download mimikatz

### ISSUE THREAD

**Issue by Greatsociety3s** [gentilkiwi/mimikatz#278]
Google, or any browser wont let me download mimikatz.
i have tried turning off safebrowsing, but it still wont allow me to continue.

Hvad can i do to install the mimikatz exe ?

screenshot of problem:
![123](https://user-images.githubusercontent.com/63550243/79071943-a8839100-7cde-11ea-863a-77b1cde01d27.PNG)

It says that it cant download because of a virus that has been detected, and it wont let me download. 

Thanks.

**Comment by Papotito123** [comment]
Hello:
Use Chrome to download.When finished press Show All files tab .Then click on Keep dangerous file.

Decompress the .zip.
You have to turn OFF windows Defender or any AV before run mimikatz.exe

**Comment by Greatsociety3s** [comment]
Hello :)
Thank you alot for reply.

Chrome wont let me install, even when i press the "keep dangerrous file" it says that a virus is in the file and therefor it cant download.

**Comment by Greatsociety3s** [comment]
> Hello:
> Use Chrome to download.When finished press Show All files tab .Then click on Keep dangerous file.
> 
> Decompress the .zip.
> You have to turn OFF windows Defender or any AV before run mimikatz.exe

Hello. Thankyou for reply :)
Chrome wont let me install, even when i press keep dangerous file, it just tells me that a virus is in the file...

**Comment by Papotito123** [comment]
Hello:
You have to turn OFF windows Defender or any AV before decompressing and run mimikatz.exe

**Comment by makc** [comment]
> You have to turn OFF windows Defender or any AV before decompressing and run mimikatz.exe

yes, I could not ownload it and had to copy it using usb stick, but then it wont let me run it either. and I cant turn AV off bcause Ive lost admin pass (the whole point of running mimikatz was to somehow get its hash, lol).

![Screen Shot 2020-12-24 at 16 13 26 ](https://user-images.githubusercontent.com/242577/103096076-0654d080-4603-11eb-8f7c-de90269b814b.png)

I guess the lesson here is to always make at least 2 admin accounts.

**Comment by Papotito123** [comment]
Hello:
Running mimikatz from USB will really trigger any AVs.
But in your case of a Standard user account...
One guess is to make a lsass dump (can try to make it thru Task Manager) and take this file to other user (admin) in other computer and run the command to minidump .
Or manage to copy SAM and SECURITY and SYSTEM from System32/config  folder.And take this files to the other user (admin) in other computer and run the command for offline hives.
Common,, if you are using mimikatz you should have some computer skills.
Boot to Recovery partition, choose Troubleshoot,then get to CMD,and from here use  copy command and copy SAM/SECURITY/SYSTEM files from "C:\Windows\System32\config"  folder to USB.And then bring these files and mimikatz to an admin user.
If no Recovery partition,boot to a Linux USB.

If you want to grab the NTLM hashes of your password there's plenty of choices.
Seek in Google.You will find something according to your skills.
Decrypting NTLM could be a long pain route.
