### ISSUE TITLE
Creative Commons should not be used for software

### ISSUE THREAD

**Issue by rugk** [gentilkiwi/mimikatz#28]
See https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

I recommend to [choose](http://choosealicense.com/) another license.

**Comment by gentilkiwi** [comment]
I'm not a developer; mimikatz isn't a software but some art.

**Comment by rugk** [comment]
Well.. okay.
But in this case the last sentence in the Readme is a bit wrong:
> This is a personal development

development or art?

**Comment by gentilkiwi** [comment]
A development can lead to art :)

**Comment by girng** [comment]
please repent.
