### ISSUE TITLE
Problems  building Mimikatz in VS2019

### ISSUE THREAD

**Issue by mobychien** [gentilkiwi/mimikatz#289]
When building the latest Mimikatz source code using Visual Studio 2019, the following issues appeared:
**Severity	Code	Description	Project	File	Line	Suppression State**
Error	C2220	warning treated as error - no 'object' file generated	mimikatz	f:\applicationdev\mimikatz-2.2.0-20200519 \mimikatz\modules\dpapi\packages\kuhl_m_dpapi_creds.c	188	
Warning	C4018	'>=': signed/unsigned mismatch	mimikatz	f:\applicationdev\mimikatz-2.2.0-20200519 - revised\mimikatz\modules\dpapi\packages\kuhl_m_dpapi_creds.c	188	
Error	C2220	warning treated as error - no 'object' file generated	mimikatz	f:\applicationdev\mimikatz-2.2.0-20200519\mimikatz\modules\kuhl_m_vault.c	527	
Warning	C4018	'>=': signed/unsigned mismatch	mimikatz	f:\applicationdev\mimikatz-2.2.0-20200519 - revised\mimikatz\modules\kuhl_m_vault.c	527

**Comment by zeroploitable** [comment]
Same issue here!!!
Did you solve it?

**Comment by mobychien** [comment]
Change the C/C++ compile warning level -> level2 from level 3(default) 
solved the issue.

YP Chien

**Comment by mobychien** [comment]
I resolved the issues by the changing the following:
1.   line 188 of mimikatz\modules\dpapi\packages\kuhl_m_dpapi_creds.c 
        if(dataLen >= **(DWORD)** FIELD_OFFSET(KULL_M_CRED_APPSENSE_DN, data))
          based on the same format as the code at line 171 above.
2.  Line 527 of mimikatz\modules\kuhl_m_vault.c :
       if(pCredential->CredentialBlobSize >= **(DWORD)** FIELD_OFFSET(KULL_M_CRED_APPSENSE_DN, data))
      Same logic.

Build the project using warning level 3 and it works..

**Comment by oscarandreu** [comment]
> I resolved the issues by the changing the following:
> 
> 1. line 188 of mimikatz\modules\dpapi\packages\kuhl_m_dpapi_creds.c
>    if(dataLen >= **(DWORD)** FIELD_OFFSET(KULL_M_CRED_APPSENSE_DN, data))
>    based on the same format as the code at line 171 above.
> 2. Line 527 of mimikatz\modules\kuhl_m_vault.c :
>    if(pCredential->CredentialBlobSize >= **(DWORD)** FIELD_OFFSET(KULL_M_CRED_APPSENSE_DN, data))
>    Same logic.
> 
> Build the project using warning level 3 and it works..

It works!
Can you do a pull request with this changes?
