### ISSUE TITLE
WCE FAQ URL is missing a /

### ISSUE THREAD

**Issue by jordanbertasso** [gentilkiwi/mimikatz#295]
Under [this heading](https://github.com/gentilkiwi/mimikatz/wiki#some-ressources-inspired-by-my-work) in the wiki the FAQ URL should be https://www.ampliasecurity.com/research/wcefaq.html, but instead is https://www.ampliasecurity.comresearch/wcefaq.html

**Comment by gentilkiwi** [comment]
In fact, error is somewhere in their URL rewriting:

![image](https://user-images.githubusercontent.com/2307945/87529850-de466600-c68f-11ea-81f4-e5bbdf7c2f34.png)

But I fixed to the target.
