### ISSUE TITLE
Program crashes when using dpapi::masterkey with /hash or /system

### ISSUE THREAD

**Issue by w0rmh013** [gentilkiwi/mimikatz#304]
The line I run:
dpapi::masterkey /in:BK-MyDomain /hash:SHA1_OF_DOMAIN_BACKUP_KEY
And mimikatz.exe hangs for a while, then crashes. 

End goal of this command is to decrypt a Protect masterkey via the domain's sha1 of the backup key.

**Comment by gentilkiwi** [comment]
It's not working like that.
At all.

Domain backup key is a RSA private key extracted from the DC... and it protect a masterkey... not a public key (BK-*), and I don't even know where did you find a SHA1_OF_DOMAIN_BACKUP_KEY

**Comment by w0rmh013** [comment]
Thank you! I misunderstood the concept. Didn't find a lot of documentation about these files.
However, I don't understand what are the /hash and /system parameters for dpapi::masterkey
