### ISSUE TITLE
Private Export certificate KO

### ISSUE THREAD

**Issue by kad25** [gentilkiwi/mimikatz#305]
Hello,

I am trying to pull a certificate needed to connect to the wifi from laptop (windows 10 enterprise version 1809) and transfer it to another laptop to get access to the wifi. 
When trying to export the certificate I got this message: 
mimikatz(powershell) # privilege::debug
Privilege '20' OK

mimikatz(powershell) # crypto::capi

mimikatz(powershell) # crypto::cng
ERROR kull_m_patch_genericProcessOrServiceFromBuild ; Incorrect version in refe
rences

mimikatz(powershell) # crypto::certificates /systemstore:local_machine /export
 * System Store  : 'local_machine' (0x00020000)
 * Store         : 'My'

 0. WX-XXXXXXXXX
        Key Container  : f55e72e5302fa2a7eb75ace3c414df8e_6e74a031-9362-4658-88b2-1d43
9c7714b5
        Provider       : Microsoft RSA SChannel Cryptographic Provider
        Type           : AT_KEYEXCHANGE (0x00000001)
        Exportable key : NO
        Key size       : 2048
        Public export  : OK - 'local_machine_My_0_WX-XXXXXXXXX.der'
        Private export : KO - ERROR kuhl_m_crypto_exportCert ; Export / CreateFile (0x
8009000b)

any ideas on how to fix it and export the certificate with the key?

**Comment by gentilkiwi** [comment]
This isn't a CNG certificate, but a CAPI one, `crypto::capi` before

**Comment by kad25** [comment]
Hello, 
I don't understand , I use this command:
PowerLine.exe Invoke-Mimikatz “Invoke-Mimikatz -Command \”`\”privilege::debug`\” `\”crypto::capi`\” `\”crypto::cng`\” `\”crypto::certificates /systemstore:local_machine /export`\” \””

**Comment by gentilkiwi** [comment]
You don't use mimikatz here...
