### ISSUE TITLE
How to select text or copy/paste on Windows?

### ISSUE THREAD

**Issue by Stopi** [gentilkiwi/mimikatz#318]
The title says it all, I couldn't do it so...

I mean this is a great tool, but copying long path name or getting hashes back is a nightmare.
Well I guess it useless to explain any more why copy/paste function is required.

Please help...

**Comment by githubkuyaya** [comment]
Just mark the text with the cursor and do ctrl+c...?
Works for me :)

**Comment by Stopi** [comment]
yeah, obviusly I've tried that and it didn't work.
it was few months ago but I think it was on windows 10.

**Comment by githubkuyaya** [comment]
Well then it's a problem with your shell settings from the windows side probably

**Comment by Stopi** [comment]
OK, I've been investigating more...
My problem was on Windows Server 2012 R2 (not Windows 10).

No contextual menu when right clicking the terminal, but if I use the icon (top-left of window's decoration) then I can access the [Edit] sub-menu which give me access to [Mark].

So I guess this solves my issue, I close the ticket.
Thanks a lot for your help.
