### ISSUE TITLE
Big Issue on Win 10 HELP

### ISSUE THREAD

**Issue by mellamofiras** [gentilkiwi/mimikatz#32]
On win 10, if you open mimikatz and try to get the passwords, you can not get it because it is impossible, I tryed with all: open like administrator,
        -privileges::debug
"privilege 20 OK"
        -sekurlsa::logonpasswords
"ERROR kuhl_m_sekurlsa_acquireLSA ; Modules Informations"
        -lsadump::cache
"Domain: ******"
"Syskey: ****************************"
"ERROR kuhl_m_lsadump_secretsOrCache ; kull_m_registry_regOpenKeyEx (SECURITY) (0x00000005)"
       -lsadump::sam 
"Domain: ******"
"Syskey: ****************************"
"ERROR kuhl_m_lsadump_getUsersandSamKey ; kull_m_registry_regOpenKeyEx SAM accounts (0x00000005)"

Pls getilkiwi help me.

**Comment by bbdoron770** [comment]
Check this out
http://www.attactics.org/2015/09/windows-10-extracting-hashes-plaintext.html

**Comment by mellamofiras** [comment]
No, that not worked, because my error was
 "ERROR kuhl_m_sekurlsa_acquireLSA ; Modules Informations"
 "ERROR kuhl_m_lsadump_secretsOrCache ; kull_m_registry_regOpenKeyEx (SECURITY)
"ERROR kuhl_m_lsadump_getUsersandSamKey ; kull_m_registry_regOpenKeyEx SAM accounts (0x00000005)" 
My error wasnt extracting the haches.
but Thanks for help :D

**Comment by zqguang3708** [comment]
Year,I open with administrator   then got the password is (NULL)
Is there anything wrong?

**Comment by gentilkiwi** [comment]
https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#be-logic ;)
