### ISSUE TITLE
Win 7: Handle on memory

### ISSUE THREAD

**Issue by WGierke** [gentilkiwi/mimikatz#34]
Hey everyone,

really nice program! Congrats and thank you very much!

Though, I'm getting an error on Windows 7:
When running `privilege::debug` I'm getting "ERROR kuhl_m_privilege_simple ; RtlAdjustPrivilege <20> c0000061"
and when running `sekurlsa::logonpasswords" I'm getting "ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory <0x00...5>"
Is there any get around?

**Comment by tigros** [comment]
are you running cmd as admin?

**Comment by WGierke** [comment]
No and that solved the problem ... thank you very much!
