### ISSUE TITLE
Has nobody noticed the syntax errors?

### ISSUE THREAD

**Issue by RyozoKa** [gentilkiwi/mimikatz#346]
It's clear that many of the headers in fact contain syntax errors that do not show up in Visual Studio due to some of their non-standard workarounds for people's common mistakes, which shows up on other compilers. Thus, it's not possible to even use the headers in MinGW for example without falling into hundreds of syntax errors. Some of the errors are SAL related, so we can ignore those, but many of the other ones I found were related to simple syntax mistakes such as declaring a variable in both the header and the corresponding compilation unit. Variables that should be accessible through a header in a different compilation unit needs to be prefixed with "extern". Something as simple as "const wchar_t *KULL_M_REGISTRY_TYPE_WSTRING[];" in "kull_m_registry.h" is going to fail syntax wise, if it isn't prefixed with extern.

**Comment by gentilkiwi** [comment]
`mimikatz` is Windows C project, so yes, if I can have some shortcut with particularities of VS, I'll :)
