### ISSUE TITLE
DCSync fails against renamed domains

### ISSUE THREAD

**Issue by MichaelGrafnetter** [gentilkiwi/mimikatz#35]
Running DCSync against domains that have been renamed ends with this message:

`ERROR kuhl_m_lsadump_dcsync ; RPC Exception 0x00002191 (8593)`

That error code stands for

> The directory service cannot perform the requested operation because the servers involved are of different replication epochs (which is usually related to a domain rename that is in progress).

Probable cause: Mimikatz does not set the DRS_EXTENSIONS_INT::dwReplEpoch value, so it always defaults to 0. But each domain rename increments this counter on DCs and if the client and the server are not in the same epoch, the server simply refuses to send replication changes.

Possible solution: IDL_DRSBind should be called again with the epoch that the server returns in the first call, if it is not 0.

**Comment by gentilkiwi** [comment]
Amazing :)
Thank you @MichaelGrafnetter and @rmbolger !
I even didn't know that a domain could be renamed :)

Luckily the ``kull_m_rpc_drsr.h`` file is ready to embed the ``dwReplEpoch`` :)

```
typedef struct _DRS_EXTENSIONS_INT {
	DWORD cb;
	DWORD dwFlags;
	//GUID SiteObjGuid;
	//DWORD Pid;
	//DWORD dwReplEpoch;
	//DWORD dwFlagsExt;
	//GUID ConfigObjGUID;
	//DWORD dwExtCaps;
} DRS_EXTENSIONS_INT, *PDRS_EXTENSIONS_INT;
```

I'll take a look, maybe this week end !

**Comment by rmbolger** [comment]
Glad to help. And yeah, domain renames are definitely rare and can be cumbersome if you have a lot of services already running against it.  But I think the process has been officially supported since at least AD 2003.

**Comment by speidy** [comment]
Cool :) thanks for updating
בתאריך יום ו׳, 29 באפר׳ 2016 ב-0:58 מאת Ryan Bolger <
notifications@github.com>:

**Comment by MichaelGrafnetter** [comment]
Well, the [documentation](https://msdn.microsoft.com/en-us/library/cc228475.aspx#Appendix_A_Target_44) on dwReplEpoch clearly says that

> This value is set to zero by all client callers.

Lessons learned: Do not trust the documentation. ;-) On the other hand, mimikatz or DSInternals do way more than a regular client caller.

**Comment by gentilkiwi** [comment]
Or we must read the all the [documentation](https://msdn.microsoft.com/en-us/library/cc228293.aspx) :D 

> If the client is a DC, it reads the value of msDS-ReplicationEpoch from its nTDSDSA object and assigns this value to the dwReplEpoch field of the DRS_EXTENSIONS_INT structure; otherwise, it sets the dwReplEpoch field of the DRS_EXTENSIONS_INT structure to zero.

On my sided I tried to minimize this struct size to minimize error on input... at least we must now go to this field ;)

**Comment by rmbolger** [comment]
This is the first time I've read this deep into the replication protocol. And I'm confused about their "client" and "server" terms.  Can't decide whether they mean a generic client/server like caller/endpoint...or more specifically a replication client vs a replication server.  And since mimikats is impersonating a server in this case, it would need to follow the second sentence.

> The server sets this value by assigning the value of msDS-ReplicationEpoch from its nTDSDSA object.

But because we're only a fake server, we don't actually have an nTDSDSA object of our own to check. So we need to cheat, check the target DC's value, and match it.

**Comment by gentilkiwi** [comment]
I think it will not be a problem because we must get ``uuidDsaObjDest`` from ``NtdsDsaObjectGuid`` so I presume it will be easy to get ``dwReplEpoch`` from this previous bind.

**Comment by rmbolger** [comment]
Here's a better reference in the docs for [IDL_DRSBind](https://msdn.microsoft.com/en-us/library/cc228293.aspx).

> The client uses pextClient to pass a properly initialized DRS_EXTENSIONS_INT structure to the server. If the client is a DC, it reads the value of msDS-ReplicationEpoch from its nTDSDSA object and assigns this value to the dwReplEpoch field of the DRS_EXTENSIONS_INT structure;

**Comment by MichaelGrafnetter** [comment]
Of course that by client they mean Windows 7, which uses IDL_DRSCrackNames extensively. That is the security problem of this protocol: It mixes DC-DC, client-DC and admin-DC communication, so you cannot block it by firewall.

**Comment by gentilkiwi** [comment]
Damned, even MS can update its code ;)
https://community.office365.com/en-us/f/156/t/172670
