### ISSUE TITLE
chrome offline decryption possible on >80 versions not working

### ISSUE THREAD

**Issue by Anass-bekar** [gentilkiwi/mimikatz#361]
I tried decrypting chrome Login file offline using masterkeys retrieved using backup key and lsass dump but neither one seems to work I get the error No Alg and/or Key handle despite AES encryption. only decrypted key from cryptUnprotect in user context works.

`Command :  dpapi::chrome /in:Login /masterkey:f35cfc2b44aedd7…`

**Comment by Anass-bekar** [comment]
figured it out.

**Comment by B3YD4** [comment]
dude i have the same problem can you explain how you solved it? In my problem, I specify the path of the login data file and bring /unprotect at the end, but it does not give me the aes key in the terminal.
