### ISSUE TITLE
Cert extraction feature is overengineered

### ISSUE THREAD

**Issue by DavidEl03** [gentilkiwi/mimikatz#365]
The extraction is extremely cool, but here is a nicer way to do it:
Take a look at https://docs.microsoft.com/en-us/windows/win32/api/cryptuiapi/nf-cryptuiapi-cryptuiwizexport
In combination of the tricks done in https://github.com/iSECPartners/jailbreak

My Flatmate had a PTSD flashback reading through kuhl_m_crypto_extractor.c

**Comment by gentilkiwi** [comment]
1. the question is not to be nice, but usable... this UI is not compatible with a lots of use case.
2. extractor functions are not related to Certificate with private key export
