### ISSUE TITLE
Exporting certificates of user

### ISSUE THREAD

**Issue by vivami** [gentilkiwi/mimikatz#38]
I'm trying to export user certificates from a system, but I'm ending up with the error `kuhl_m_crypto_l_certificates ; CertOpenStore`. 

`crypto::capi privilege::debug crypto::cng` are were succesful.

![](http://cl.ly/gCJ4/error.png)

**Comment by gentilkiwi** [comment]
The error code you have (0x00000002) is ``ERROR_FILE_NOT_FOUND``... it can help you about your system store that does not exist... "user".

See: https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#certificates

**Comment by deliciouslytyped** [comment]
This issue helped me.
