### ISSUE TITLE
Mimikatz stopped working on Windows 10 1511 VSM with current patches

### ISSUE THREAD

**Issue by goldfinger2** [gentilkiwi/mimikatz#39]
Salut Benjamin,

it seems that mimikatz 2.1 from 06 May stopped working on windows 10 systems with activated Virtual Secure Mode and current patch sets installed.

To be precise, the commands "logonpasswords" and "msv" have become broken.

We obtain an endless list of values for the LSA Isolated Data attribute "Encrypted", or alternatively a crash popup "mimikatz for Windows has stopped working".

We tried it with a Microsoft Surfacebook (with TPM 2.0)
Windows 10 Enterprise (US) version 1511
OS      Version: 10586.0 and  10586.318
LsaIso  Version: 10.0.586.0 and 10.0.10586.212

At the end we used the newest Windows Patch:
May 10, 2016 — KB3156421 (OS Build 10586.318)

> This update includes quality improvements and security fixes. No new operating system features are being introduced in this update. Key changes include: 
> Fixed additional security issues with kernel mode drivers, remote procedure calls, the Microsoft Graphics Component, Internet Explorer 11, Microsoft Edge, Windows Shell, Windows Journal, 
> **Virtual Secure Mode**, Schannel, and Jscript.

Greetings from Germany,
Jürgen
M

Following is a session transcript of mimikatz which triggers the crash popup:

```
  .#####.   mimikatz 2.1 (x64) built on May  6 2016 01:28:44
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 19 modules * * */
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000020)

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonpasswords

Authentication Id : 0 ; 6164539 (00000000:005e103b)
Session           : Interactive from 3
User Name         : admin
Domain            : COMPANY
Logon Server      : DC1
Logon Time        : 18.05.2016 13:17:47
SID               : S-1-5-21-504569365-2122958605-3922303804-1108
        msv :
         [00000003] Primary
         * Username : admin
         * Domain   : COMPANY
           * LSA Isolated Data: lmHash)
ß¶??¤ðgAÆL4$?ð?k¨ø,¨è¬??À*Å¸¶p?r?ßç®~Vý 'ÆK¡ó­?ó^è4  ±ö-äb"£Ûæ
             Unk-Key  : 701857763ed94172143552903b20950a2fb1fc0488884e0d9ed4e1c3bc80ebd1838f736e3b7492dea90780caa6fd0100
             Encrypted:
```

**Comment by gentilkiwi** [comment]
Thank you @goldfinger2 ! I'll try to take a look !
I try to support LTSB and current branch, but not easy as I want it to be: laptop does not support SecureBoot, and if I enable Credential Guard on my main computer: no more VMWare :(

If you have some ``lsass.dmp`` from computer with errors, it'll help :)

**Comment by goldfinger2** [comment]
@gentilkiwi NoPe. Thanks.
[lsass2.zip](https://github.com/gentilkiwi/mimikatz/files/276361/lsass2.zip)

**Comment by gentilkiwi** [comment]
Thank you @goldfinger2 .
Microsoft seem to search their way with LSAIso code/structures, it's not the first time at all I have to change some code like this because of their... well, you see ;)

**Comment by Twan14** [comment]
can someone help me with this error?
-----------------------------------------

  .#####.   mimikatz 2.1.1 (x64) #17763 Dec  9 2018 23:56:50
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo) ** Kitten Edition **
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000005)
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000005)
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000005)
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000005)
ERROR kull_m_busylight_devices_get ; CreateFile (deviceHandle) (0x00000005)
