### ISSUE TITLE
sid::add

### ISSUE THREAD

**Issue by mzsf3c** [gentilkiwi/mimikatz#41]
Hi, 

I am experimenting with sidhistory, but the sid module only seems to have the lookup and query function, the add and modify functions are missing in version 2.1 alpha 20160506.

or, what am I missing

Merci!

**Comment by gentilkiwi** [comment]
As DC are "often" x64, there is no support for x86 versions

**Comment by mzsf3c** [comment]
Thx, that explains my issue.
