### ISSUE TITLE
Official Mimikatz documentation

### ISSUE THREAD

**Issue by sfakiana** [gentilkiwi/mimikatz#42]
Hi all,

Is there any official documentation? Is there any appetite to create one?
One unofficial can be found in adsecurity blog.

Cheers,
Andreas

**Comment by sfakiana** [comment]
Or may the wiki page (https://github.com/gentilkiwi/mimikatz/wiki) is supposed to be the updated official documentation? I have just seen it!

**Comment by gentilkiwi** [comment]
You found it :)
official: yes, up to date is another story ;)
