### ISSUE TITLE
 Benjamin - We Love you

### ISSUE THREAD

**Issue by xbxhckr** [gentilkiwi/mimikatz#421]
You are a bad ass. We hope you are well. And we love you and your work.

That is all. That is the issue.

Nous vous aimons

Stay safe.

**Comment by gentilkiwi** [comment]
On valentine night, it's a little bit suspicious
![fails_fails_everywhere_32](https://user-images.githubusercontent.com/2307945/218872069-b34a8f9c-9186-4031-bce0-c6549b536d8a.gif)

**Comment by xbxhckr** [comment]
You know we love you  :)
Click no links, drink more wine.

Love you!

Stay safe my mon ami.

![image](https://user-images.githubusercontent.com/125408416/218874957-ed5de9e4-229e-4778-a775-0c35681e8016.png)
