### ISSUE TITLE
cert is exported but without priv key

### ISSUE THREAD

**Issue by nestnisus** [gentilkiwi/mimikatz#44]
First of all this seems to be a great tool, thanks.

When I try to export my certificate it is exported without the private key, which doesn´t help me.

System info: Windows 2008 Server R2 64bits
mimikatz 2.1 x64 (downloaded today)

At some point I get error:
```ERROR kuhl_m_crypto_l_certificates ; CryptAcquireCertificatePrivateKey (0x80090011)```

I made sure I opened command prompt using the "Run as Administrator" and went over UAC. Because of that I´m assuming I have ACL permissions on the private keys.

I am sure the key is not there because when I use openssl to verify pfx (```openssl pkcs12 -info```) the ```BEGIN ENCRYPTED PRIVATE KEY``` is not there. And when I try to extract the key to a .pem (```openssl pkcs12 -in pfx -out pem```) the output file is empty.

Can you help?

Output (broken lines kept, sorry):
```
mimikatz # privilege::debug
Privilege '20' OK

mimikatz # crypto::cng
"KeyIso" service patched

mimikatz # crypto::capi
Local CryptoAPI patched

mimikatz # crypto::certificates /systemstore:CERT_SYSTEM_STORE_LOCAL_MACHINE /store:My /export
 * System Store  : 'CERT_SYSTEM_STORE_LOCAL_MACHINE' (0x00020000)
 * Store         : 'My'

 0. wantedCert.com
        Key Container  : {some_key}
        Provider       : Microsoft Enhanced Cryptographic Provider v1.0
        Provider type  : RSA_FULL (1)
ERROR kuhl_m_crypto_l_certificates ; CryptAcquireCertificatePrivateKey (0x80090011)
        Public export  : OK - 'CERT_SYSTEM_STORE_LOCAL_MACHINE_My_0_wantedCert.com.der'
        Private export : OK - 'CERT_SYSTEM_STORE_LOCAL_MACHINE_My_0_wantedCert.com.pfx'

 1. WMSvc-IISDefaultCertificate
        Key Container  : WMSvc Certificate Key Container
        Provider       : Microsoft RSA SChannel Cryptographic Provider
        Provider type  : RSA_SCHANNEL (12)
        Type           : AT_KEYEXCHANGE (0x00000001)
        Exportable key : YES
        Key size       : 2048
        Public export  : OK - 'CERT_SYSTEM_STORE_LOCAL_MACHINE_My_1_WMSvc-IISDefaultCertificate.der'
        Private export : OK - 'CERT_SYSTEM_STORE_LOCAL_MACHINE_My_1_WMSvc-IISDefaultCertificate.pfx'
```

**Comment by gentilkiwi** [comment]
It seems to have problem with this particular private key (exportable or not)
What give ``certutil -store my`` and ``certutil -key`` ?

If confidential data, do not hesitate to mail me extra details.

**Comment by bullguard01** [comment]
hello gentil.. i have a rainbow ikey 4000 with my certificate installed in it... mimikatz exports the pfx but I think its without the private key... mimikatz password didn't work .. please assist me .. thank you
