### ISSUE TITLE
DCSync does not work with PAM feature enabled

### ISSUE THREAD

**Issue by MichaelGrafnetter** [gentilkiwi/mimikatz#47]
Hi @gentilkiwi ,

knowing that DCSync had problem with AD Recycle Bin being enabled, I tried it against a Windows Server 2016 TP5 DC with the [Privileged Access Management Feature](https://technet.microsoft.com/en-us/library/dn903243.aspx) on, just out of curiosity. And guess what, it ends with error 8236 (The server does not support the requested critical extension), just as my own [DSInternals](https://github.com/MichaelGrafnetter/DSInternals) does.

The solution will involve more than just fun with flags, as it was with DRS_EXT_RECYCLE_BIN, because the updated Doc states this: GR9 (DRS_EXT_GETCHGREPLY_V9, 0x00000100): If present, signifies that the DC supports [DRS_MSG_GETCHGREPLY_V9](https://msdn.microsoft.com/en-us/library/mt181670.aspx). The DRS_MSG_GETCHGREPLY_V9 message basically adds link expiration timestamp to DRS_MSG_GETCHGREPLY_V6.

@asolino This issue most probably affects Impacket, too, though I cannot verify it right now.

Cheers
Michael

**Comment by asolino** [comment]
Hey @MichaelGrafnetter thanks for pointing this out! I'm downloading TP5 now and will give a try with `impacket`. Right now I'm expecting receiving `DRS_EXT_GETCHGREPLY_V6`. Cannot you control that through `DRSBind.dwFlags`?

**Comment by MichaelGrafnetter** [comment]
@asolino It seems that once PAM is enabled, DC only returns DRS_EXT_GETCHGREPLY_V9 and fails if the client does not support it, because otherwise it could not tell the client about the expiring links.

**Comment by gentilkiwi** [comment]
>  more than just fun with flags

![blog_bigbangtheory_funwithflags](https://cloud.githubusercontent.com/assets/2307945/15808253/66a2e8dc-2b73-11e6-8f6c-f4eb8abadabd.jpg)

**Comment by MichaelGrafnetter** [comment]
@gentilkiwi You read my mind!

**Comment by asolino** [comment]
All right.. fair point.. that for the clarification @MichaelGrafnetter!

**Comment by MichaelGrafnetter** [comment]
There are still a few undocumented flags, because TP5 returns this in DRS_EXTENSIONS_INT with RB+PAM enabled:
dwExtCaps = 2047
dwFlagsExt = 526
dwFlags = 1073741695

**Comment by gentilkiwi** [comment]
I get it work, you need `0x200` ;)

**Comment by gentilkiwi** [comment]
Flag validated :+1: 
![because](https://cloud.githubusercontent.com/assets/2307945/15808758/3a7db720-2b80-11e6-83da-e74ff3b2a866.png)

**Comment by MichaelGrafnetter** [comment]
So it was fun with flags after all... Sorry for spreading unverified info, @asolino . But to my excuse, even the [doc](https://technet.microsoft.com/en-us/dd207742) is somewhat smoke and mirrors.

**Comment by gentilkiwi** [comment]
It could have been much more complex.
Fortunately, the structures have very compatible unions (Req v8/v10 & Rep v6/v9)

 ![tumblr_lyg8ft2wxp1qbiz5t](https://cloud.githubusercontent.com/assets/2307945/15808808/da3c70a2-2b81-11e6-8cd1-3d01d7c1f724.gif)

**Comment by MichaelGrafnetter** [comment]
I have fixed it in DSInternals, too, but you beat me to it. Nevertheless, I just learned something and I had fun doing it. ;-)

**Comment by gentilkiwi** [comment]
Because I don't want to give a fuck about future flags:
* `DRS_EXT_RECYCLE_BIN`
* `DRS_EXT_PAM`
* ...

![fuck-everything](https://cloud.githubusercontent.com/assets/2307945/15809139/eef26b34-2b89-11e6-81c6-b68d5392e2c8.gif)

ac09c27a40082ddb400ab1525a075e316a7b9689 (`pDrsExtensionsInt->dwExtCaps = MAXDWORD32`)

Thank you for nice exchanges @MichaelGrafnetter & @asolino

**Comment by asolino** [comment]
That's uber potential! ;) ;) :)

thanks for the quick turn around.. and likewise @gentilkiwi & @MichaelGrafnetter

**Comment by MichaelGrafnetter** [comment]
@gentilkiwi Hopefully, your cannonball approach will turn out to be futureproof. And Ben, you really are a meme machine! ;-)
