### ISSUE TITLE
Windows Server 2003

### ISSUE THREAD

**Issue by mehranexpert** [gentilkiwi/mimikatz#48]
i Got This error : 

```
mimikatz # sekurlsa::logonPasswords
ERROR kuhl_m_sekurlsa_nt5_init ; kull_m_memory_search
ERROR kuhl_m_sekurlsa_acquireLSA ; Local LSA library failed
```

**Comment by gentilkiwi** [comment]
it leads me to write a wiki page, no only for you, but a little bit for you :)
https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue

**Comment by mehranexpert** [comment]
oh Sorry :+1: 

here is my Log file 
'Using 'new2.txt' for logfile : OK

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_nt5_init ; kull_m_memory_search
ERROR kuhl_m_sekurlsa_acquireLSA ; Local LSA library failed

mimikatz # lsadump::dcsync
[DC] 'texas.test.com' will be the domain
[DC] 'texas.test.local.com' will be the DC server
ERROR kuhl_m_lsadump_dcsync ; Missing user or guid argument

mimikatz # 
'
Version of Windows : 'Windows 2003 Enterprise SP2 ( Build 3790.srv03_sp2_rtm.070216-1710) '

im run it from User have admin Permission . i dont run Windows Update

**Comment by gentilkiwi** [comment]
You don't even post if it's x86 or x64... or send minidump...
In your case you can also post a zip of your `lsasrv.dll` file.

**Comment by mehranexpert** [comment]
its x86 , i can't upload zip file here i uploaded on Dropbox 

minidump file : https://www.dropbox.com/s/xv6e18nsg0si5f7/lsass.zip?dl=0
lsasrv.dll file : https://www.dropbox.com/s/e679nbsxszl71pm/lsasrv.ZIP?dl=0

**Comment by gentilkiwi** [comment]
It must be OK now :)
US version was built 2h14m12s before the FR build, so the timestamp I compared was too recent.
I adjusted with the US one (logically the first version built)

Thank you for your report, and full data! It's easier with all of that!
