### ISSUE TITLE
Sekurlsa::LogonPasswords Fails on Windows 10 RS1 Builds

### ISSUE THREAD

**Issue by canyonbrewer** [gentilkiwi/mimikatz#49]
Hello - 

We have a Windows 10 pre-RS1 build and it appears that mimikatz is unable to run Sekurlsa::LogonPasswords . 

It fails with this error:

ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

attached is screenshot.  

Is this a known issue?  Please help us get this working
![mimikatz error](https://cloud.githubusercontent.com/assets/19937529/16057263/df01c650-323e-11e6-9d57-21ce703c1173.jpg)

**Comment by gentilkiwi** [comment]
As it's a pre-release, I can't work on it ;)
