### ISSUE TITLE
Mimikatz Kerberox export issue

### ISSUE THREAD

**Issue by aldo1901** [gentilkiwi/mimikatz#50]
I'm playing around with Kerberos dumping and cracking. I'm starting mimikatz and running "standard::base64" so that all the .kirbi files get exported using base64 encoding. However once I execute "kerberos::list /export" using base64, there are no output files in my directory. Mimikatz only saves .kirbi files when I DON'T use base64 encoding.

**Comment by gentilkiwi** [comment]
That's exactly the expected behavior: https://github.com/gentilkiwi/mimikatz/wiki/module-~-standard#base64

**Comment by aldo1901** [comment]
So to manually put these into a blah.kirbi I would just copy the encoding alone without the ===== lines or with======?

====================
doIFOTCCBTWgAwIBBaEDAgEWooIELjCCBCphggQmMIIEIqADAgEFoREbD0NIT0NP
TEFURS5MT0NBTKIkMCKgAwIBAqEbMBkbBmtyYnRndBsPQ0hPQ09MQVRFLkxPQ0FM
...
GA8yMDE0MDQyNDIyNTE0NFqnERgPMjAxNDA1MDExMjUxNDRaqBEbD0NIT0NPTEFU
RS5MT0NBTKkkMCKgAwIBAqEbMBkbBmtyYnRndBsPQ0hPQ09MQVRFLkxPQ0FM
====================

**Comment by gentilkiwi** [comment]
If you want to have data in a file, don't use the base64 command.
