### ISSUE TITLE
Easy way to build the correct PFX of howto ~ decrypt EFS files

### ISSUE THREAD

**Issue by 3gstudent** [gentilkiwi/mimikatz#51]
**Link is:**
https://github.com/gentilkiwi/mimikatz/wiki/howto-~-decrypt-EFS-files
Learn many from this,thank you so much!
**And a little advice:**
Installation and configuration of OpenSSL is very troublesome.
And I think there is an easier way：）
We can use `cert2spc.exe` and `pvk2pfx.exe`.
They are all included in the Microsoft Windows SDK and can be run separately.
The code is:
```
cert2spc.exe B53C6DE283C00203587A03DD3D0BF66E16969A55.der public.spc
pvk2pfx.exe -pvk raw_exchange_capi_0_ffb75517-bc6c-4a40-8f8b-e2c555e30e34.pvk -pi test -spc public.spc -pfx cert.pfx -f
```

I hope you will like it~

**Comment by gentilkiwi** [comment]
"installation", "configuration" ? what do you mean?
this is a simple `.exe` that I provide: http://blog.gentilkiwi.com/programmes/openssl (not up to date, but amply enough)

but I love your way too ! :)

**Comment by 3gstudent** [comment]
I mean it is very troublesome for me to download the source code and compile it. :)
I haven't seen your simple .exe before.
Learn a new method from you again.
Thanks！

**Comment by gentilkiwi** [comment]
There are a lot of places where you can find OpenSSL binaries for Windows - https://wiki.openssl.org/index.php/Binaries

New versions of SDKs are a hell to install/download, especially when you need only few parts.

**Comment by 3gstudent** [comment]
Yeah,cert2spc.exe , pvk2pfx.exe and some other exe file are the most I use in SDKs.
:)

**Comment by prof79** [comment]
https://slproweb.com/products/Win32OpenSSL.html is a no-brainer, use it all the time on Windows.
