### ISSUE TITLE
[Question] Log

### ISSUE THREAD

**Issue by Lionir** [gentilkiwi/mimikatz#54]
How to create a Log at a specific location using a batch file?
I currently use "mimikatz.exe privilege::debug log sekurlsa::logonpasswords" and need a way to make to make the log save to U:/results/mimikatz.txt

**Comment by gentilkiwi** [comment]
https://github.com/gentilkiwi/mimikatz/wiki/module-~-standard#log ;)

**Comment by Lionir** [comment]
@gentilwiki If I say "mimikatz.exe privilege::debug log U:/results/mimikatz.txt sekurlsa::logonpasswords", it will think that "log" and "U:/results/mimikatz.txt" are two different commands. Any ways to run around this issue?

**Comment by gentilkiwi** [comment]
`mimikatz privilege::debug "log U:\results\mimikatz.txt" sekurlsa::logonpasswords exit`

**Comment by Lionir** [comment]
@gentilkiwi Ah, thank you. it's my first time making a batch file, haha.
