### ISSUE TITLE
anti virus software thinks mimikatz is malware

### ISSUE THREAD

**Issue by junkb** [gentilkiwi/mimikatz#55]
i came across minikatz when looking for a method to retrieve a "non exportable" key from a windows computer.  the anti virus software running on the computer i happened to be using to download mimikatz flagged the software as a virus.  this isn't particularly compelling, but in the interest of self preservation, and somewhat on a whim, i decided to investigate a little more.  i uploaded mimikatz.exe to virustotal, which reported this analysis:

https://www.virustotal.com/en/file/c3c336a23021b68b026bdf1642b220d88037039aa6d7f8e7d4d576cc38063088/analysis/1470356182/

i'm accustomed to the world of crappy anti virus software and constant false positives, but it was a bit surprising to see so many claiming mimikatz to be a trojan, rootkit, malware, etc., but not find any references to this in the various resources discussing its use.

is just an inevitable nuance, given the nature of this software, and happens to be little more than a coincidence?  if nothing else, i thought the author[s]/community might be interested to know this [even if it's just for the sake of being informed on principle], assuming it's not something which has already been mentioned.

**Comment by simonuvarov** [comment]
@junkb it's ok, because mimikatz is often used during pentests. You can try to dump lsass.exe memory using procexplorer/taskmanager/procdump and then extract hashes/passwords from it.

**Comment by gentilkiwi** [comment]
Sometimes, people forget that there other features than passwords-dumping in `mimikatz`.

In fact for CAPI Certificate, you can make a private key exportable with comparing to another one exportable, and a hex editor!
More complicated, you can backup files/registry and make all the work on another computer.

For antivirus debate, *no*: `mimikatz` isn't a virus or malware, but *yes*: you would not like to find it on your corporate computer/server :neutral_face:
I was shocked the first when antivirus blacklisted my program (made by hand, with love :sparkling_heart:), but as `mimikatz` is often used "as-is" in real attacks, it's a logical reaction.

As it's not a virus/malware they are not zealous when making signature ;)
