### ISSUE TITLE
Mimikatz stopped working on Windows 10 1607 VSM 

### ISSUE THREAD

**Issue by goldfinger2** [gentilkiwi/mimikatz#56]
Salut Benjamin,

as we expect mimikatz 2.1 from 08 August don't work with the Windows 10 Build 1607 and Credential Guard
Windows 10 Enterprise (US) version 1607
OS Version: 14393.10
LsaIso Version: 10.0.14393.0

We attached the lsass dump file created by the taskmanager.

Greetings from Germany,

Jürgen
[lsass-1607.zip](https://github.com/gentilkiwi/mimikatz/files/413104/lsass-1607.zip)

**Comment by gentilkiwi** [comment]
Hello Jürgen :)

Another version, another structure ;)
Thank you for dump!
For test purpose, what's the password of your `COMPANY\admin` account?

**Comment by goldfinger2** [comment]
Hi Benjamin,
thanks for the fast reply.
The password is:
P@ssw0rd!

Thanks 
Jürgen

Am 11.08.2016 um 23:37 schrieb Benjamin DELPY <notifications@github.com <mailto:notifications@github.com> >:

Hello Jürgen :)

Another version, another structure ;)
Thank you for dump!
For test purpose, what's the password of your COMPANY\admin account?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

 
-- 
Science + Computing AG
Vorstandsvorsitzender/Chairman of the board of management:
Dr. Martin Matzke
Vorstand/Board of Management:
Johannes Barthmes, Yvonne Veyhelmann
Vorsitzender des Aufsichtsrats/
Chairman of the Supervisory Board:
Philippe Miltin
Aufsichtsrat/Supervisory Board:
Martin Wibbe, Winfried Holz
Sitz/Registered Office: Tuebingen
Registergericht/Registration Court: Stuttgart
Registernummer/Commercial Register No.: HRB 382196

**Comment by gentilkiwi** [comment]
Now you version is handled:
```
        msv :
         [00000003] Primary
         * Username : admin
         * Domain   : COMPANY
           * unkSHA1: 9fa9aaa47e7ccb12cefb7335cabdb0a3916db926
           * LSA Isolated Data: NtlmHash
             Unk-Key  : f340a9f324c30a5cb636828ddb796f1f5da9b0a699c446711f5158410aceb18dfcdac753a320e26b0cb76c0d3534e23d
             Encrypted: ac9e017840929702f22e8d05dd53f3ffaac36bb047a6cc1a7b3881fd0fa1f9061f58e6b6478220b7070eb413b9c78c2fcca37bae
                   SS:160, TS:8, DS:52
                   0:0x0, 1:0x64, 2:0x1, 3:0x101, 4:0x0, E:01000000000000000000000000000000, 5:0x8001
```

Thank you for the dump, it helped a lot!
