### ISSUE TITLE
Remote Credential Guard  Issue

### ISSUE THREAD

**Issue by goldfinger2** [gentilkiwi/mimikatz#58]
Salut Benjamin,

the new mimikatz version from Aug 12  is working with Windows Build 1607 with and without Credential Guard. :-)
But we have a little issue together with Remote Credential Guard (RCG).

We used the following setup:
Source (RPC Client) Windows Build 1607 with Credential Guard protected
Target Windows Build 1607 without Credential Guard
We made a RPC-connection with the parameter "/remoteguard" to the target. 
After running mimikatz on the target machine it will crash. (See attachments)
May be the problem is that the TGT-ticket on the target machine is a copy of the TGT-ticket of the source machine but **without** the session key. This is why the target must call back to the source to use his session key to decrypt the response from the TGS of the new service tickets.

![mimikatz-remote-cred-bug](https://cloud.githubusercontent.com/assets/19430229/17706475/7c371fdc-63dc-11e6-8ba1-8c5e574808b6.jpg)
![mimikatz-remote-cred-bug2](https://cloud.githubusercontent.com/assets/19430229/17706497/8faab2c2-63dc-11e6-89b1-d6dc20f0bd10.jpg)

Greetings from Germany

Juergen

**Comment by gentilkiwi** [comment]
Amazing :)
It already existed with `/restrictedAdmin`, a ticket without keys (without SSO).
A flag may exist to indicate it's remote :)

Do you have a dump on client side, and in the same time on server side ?

Cheers

**Comment by goldfinger2** [comment]
No currently not but we can make it at the end of this week.

Jürgen


Am 16.08.2016 um 18:40 schrieb Benjamin DELPY <notifications@github.com <mailto:notifications@github.com> >:

Amazing :)
It already existed with /restrictedAdmin, a ticket without keys (without SSO).
A flag may exist to indicate it's remote :)

Do you have a dump on client side, and in the same time on server side ?

Cheers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

 
-- 
Science + Computing AG
Vorstandsvorsitzender/Chairman of the board of management:
Dr. Martin Matzke
Vorstand/Board of Management:
Johannes Barthmes, Yvonne Veyhelmann
Vorsitzender des Aufsichtsrats/
Chairman of the Supervisory Board:
Philippe Miltin
Aufsichtsrat/Supervisory Board:
Martin Wibbe, Winfried Holz
Sitz/Registered Office: Tuebingen
Registergericht/Registration Court: Stuttgart
Registernummer/Commercial Register No.: HRB 382196

**Comment by goldfinger2** [comment]
Salut Benjamin,
here your dumps.
We made a connection from source with active credential guard (lsass-source-rdp-cg) with mstsc /remoteGuard to the target (lsass-target-rg)
Executing mimikatz on the target with sekurlsa::tickets we get a crash.
We used sadmin with P@ssw0rd!

[lsass-target-rgc.zip](https://github.com/gentilkiwi/mimikatz/files/425497/lsass-target-rgc.zip)
[lsass-source-rdp-cg.zip](https://github.com/gentilkiwi/mimikatz/files/425498/lsass-source-rdp-cg.zip)

**Comment by gentilkiwi** [comment]
Hello Jürgen :)

Thank you, I'll take a look :+1: 
Was the use in "Protected Users" group too ?

**Comment by goldfinger2** [comment]
Yes, he is in the Protected User Group, too.

Jürgen

Am 18.08.2016 um 20:44 schrieb Benjamin DELPY <notifications@github.com <mailto:notifications@github.com> >:

Hello Jürgen :)

Thank you, I'll take a look  
Was the use in "Protected Users" group too ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

 
-- 
Science + Computing AG
Vorstandsvorsitzender/Chairman of the board of management:
Dr. Martin Matzke
Vorstand/Board of Management:
Johannes Barthmes, Yvonne Veyhelmann
Vorsitzender des Aufsichtsrats/
Chairman of the Supervisory Board:
Philippe Miltin
Aufsichtsrat/Supervisory Board:
Martin Wibbe, Winfried Holz
Sitz/Registered Office: Tuebingen
Registergericht/Registration Court: Stuttgart
Registernummer/Commercial Register No.: HRB 382196

**Comment by goldfinger2** [comment]
Salut Benjamin,
I forgot to attach the user information. 
We used claims, too. May be they can be counterfeit soon and easy by the mimikatz golden ticket creation. ;-)
By the way is there a mimikatz command to list the Kerberos PAC field authorization information directly?

Juergen

whoami /all
USER INFORMATION
----------------
User Name      SID                                         
============== =============================================
company\sadmin S-1-5-21-504569365-2122958605-3922303804-1609

GROUP INFORMATION
-----------------
Group Name                                     Type             SID                                          Attributes                                                    
============================================== ================ ============================================ ===============================================================
Everyone                                       Well-known group S-1-1-0                                      Mandatory group, Enabled by default, Enabled group            
BUILTIN\Users                                  Alias            S-1-5-32-545                                 Mandatory group, Enabled by default, Enabled group            
BUILTIN\Administrators                         Alias            S-1-5-32-544                                 Mandatory group, Enabled by default, Enabled group, Group owner
NT AUTHORITY\INTERACTIVE                       Well-known group S-1-5-4                                      Mandatory group, Enabled by default, Enabled group            
CONSOLE LOGON                                  Well-known group S-1-2-1                                      Mandatory group, Enabled by default, Enabled group            
NT AUTHORITY\Authenticated Users               Well-known group S-1-5-11                                     Mandatory group, Enabled by default, Enabled group            
NT AUTHORITY\This Organization                 Well-known group S-1-5-15                                     Mandatory group, Enabled by default, Enabled group            
LOCAL                                          Well-known group S-1-2-0                                      Mandatory group, Enabled by default, Enabled group            
COMPANY\Group Policy Creator Owners            Group            S-1-5-21-504569365-2122958605-3922303804-520 Mandatory group, Enabled by default, Enabled group            
COMPANY\Domain Admins                          Group            S-1-5-21-504569365-2122958605-3922303804-512 Mandatory group, Enabled by default, Enabled group            
COMPANY\Protected Users                        Group            S-1-5-21-504569365-2122958605-3922303804-525 Mandatory group, Enabled by default, Enabled group            
COMPANY\Schema Admins                          Group            S-1-5-21-504569365-2122958605-3922303804-518 Mandatory group, Enabled by default, Enabled group            
COMPANY\Enterprise Admins                      Group            S-1-5-21-504569365-2122958605-3922303804-519 Mandatory group, Enabled by default, Enabled group            
NT AUTHORITY\Claims Valid                      Well-known group S-1-5-21-0-0-0-497                           Mandatory group, Enabled by default, Enabled group            
Authentication authority asserted identity     Well-known group S-1-18-1                                     Mandatory group, Enabled by default, Enabled group            
COMPANY\Denied RODC Password Replication Group Alias            S-1-5-21-504569365-2122958605-3922303804-572 Mandatory group, Enabled by default, Enabled group, Local Group
Mandatory Label\High Mandatory Level           Label            S-1-16-12288                                                                                               

PRIVILEGES INFORMATION
----------------------
Privilege Name                            Description                                                        State  
========================================= ================================================================== ========
SeIncreaseQuotaPrivilege                  Adjust memory quotas for a process                                 Disabled
SeSecurityPrivilege                       Manage auditing and security log                                   Disabled
SeTakeOwnershipPrivilege                  Take ownership of files or other objects                           Disabled
SeLoadDriverPrivilege                     Load and unload device drivers                                     Disabled
SeSystemProfilePrivilege                  Profile system performance                                         Disabled
SeSystemtimePrivilege                     Change the system time                                             Disabled
SeProfileSingleProcessPrivilege           Profile single process                                             Disabled
SeIncreaseBasePriorityPrivilege           Increase scheduling priority                                       Disabled
SeCreatePagefilePrivilege                 Create a pagefile                                                  Disabled
SeBackupPrivilege                         Back up files and directories                                      Disabled
SeRestorePrivilege                        Restore files and directories                                      Disabled
SeShutdownPrivilege                       Shut down the system                                               Disabled
SeDebugPrivilege                          Debug programs                                                     Disabled
SeSystemEnvironmentPrivilege              Modify firmware environment values                                 Disabled
SeChangeNotifyPrivilege                   Bypass traverse checking                                           Enabled
SeRemoteShutdownPrivilege                 Force shutdown from a remote system                                Disabled
SeUndockPrivilege                         Remove computer from docking station                               Disabled
SeManageVolumePrivilege                   Perform volume maintenance tasks                                   Disabled
SeImpersonatePrivilege                    Impersonate a client after authentication                          Enabled
SeCreateGlobalPrivilege                   Create global objects                                              Enabled
SeIncreaseWorkingSetPrivilege             Increase a process working set                                     Disabled
SeTimeZonePrivilege                       Change the time zone                                               Disabled
SeCreateSymbolicLinkPrivilege             Create symbolic links                                              Disabled
SeDelegateSessionUserImpersonatePrivilege Obtain an impersonation token for another user in the same session Disabled

USER CLAIMS INFORMATION
-----------------------
Claim Name           Claim ID                    Flags Type   Values                 
==================== =========================== ===== ====== ========================
"AuthenticationSilo" ad://ext/AuthenticationSilo       String "Restricted_Admin_Logon"
  
Am 18.08.2016 um 20:44 schrieb Benjamin DELPY <notifications@github.com <mailto:notifications@github.com> >:

Hello Jürgen :)

Thank you, I'll take a look  
Was the use in "Protected Users" group too ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

 
-- 
Science + Computing AG
Vorstandsvorsitzender/Chairman of the board of management:
Dr. Martin Matzke
Vorstand/Board of Management:
Johannes Barthmes, Yvonne Veyhelmann
Vorsitzender des Aufsichtsrats/
Chairman of the Supervisory Board:
Philippe Miltin
Aufsichtsrat/Supervisory Board:
Martin Wibbe, Winfried Holz
Sitz/Registered Office: Tuebingen
Registergericht/Registration Court: Stuttgart
Registernummer/Commercial Register No.: HRB 382196

**Comment by gentilkiwi** [comment]
I don't know a lots about claims for the moment.
I've embedded some tools in `mimikatz` to decrypt ticket & for PAC interpretation,.. but can not make all automated because of ASN.1 interpretation: https://social.msdn.microsoft.com/Forums/vstudio/en-US/b237c77e-614b-4c77-b9d7-9773eefb2698/berinit-and-asn1-sequence

You can enable "allowtgtsessionkey", export tgt by API and send me ticket + AES krbtgt. I can take a look.
Do not hesitate to use mail if sensitive informations.
