### ISSUE TITLE
Mimikatz Export all user passwords to txt

### ISSUE THREAD

**Issue by 810978558** [gentilkiwi/mimikatz#60]
Export all user passwords to txt
Excuting an order？

**Comment by 810978558** [comment]
If you do not understand the meaning of trouble with google translation

**Comment by gentilkiwi** [comment]
![c-est-kloug-colmate-avec-shpotzis](https://cloud.githubusercontent.com/assets/2307945/17713133/9fc6f6f8-63f9-11e6-965d-68256bf8e5cd.png)

- https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue
- https://github.com/gentilkiwi/mimikatz/wiki/module-~-standard#log
