### ISSUE TITLE
Mimikatz work on Win 10 Credential Guard?

### ISSUE THREAD

**Issue by PowerPress** [gentilkiwi/mimikatz#62]
Does mimikatz work against Win 10 new credential guard?

**Comment by gentilkiwi** [comment]
It seems you're not a big fan of making test by yourself?
- https://github.com/carmaa/inception/issues/127
- https://github.com/pentestmonkey/windows-privesc-check/issues/11
- https://github.com/xme/cuckoomx/issues/3
