### ISSUE TITLE
Password null

### ISSUE THREAD

**Issue by MatthewHKnight** [gentilkiwi/mimikatz#64]
I wanted to make this post I don't believe it's an issue with mimikatz but can someone refresh my memory as to why the password shows as null again is it because the screen was locked or because the version of Windows wasn't storing the password in memory.

I remember reading about why that happens but I have a lot of people who keep asking me and I forget the reason as to why this happens.

**Comment by gentilkiwi** [comment]
You don't remember about your own issue? #40

**Comment by MatthewHKnight** [comment]
I remember this but I thought that ticket was deleted that's why I asked I guess I skipped my own ticket. I've taken note of the reply I get this question a lot in a video I did for mimikatz and every now and then someone always asks about why their password is showing up null I'm gonna link that issue in my video description.
