### ISSUE TITLE
since the last change minidump (sekurlsa::logonpasswords) fail...

### ISSUE THREAD

**Issue by jun0s** [gentilkiwi/mimikatz#65]
latest mimikatz and lsass.exe 6.3.9600.16384 minidump file..
```
mimikatz # standard::version

mimikatz 2.1 (arch x64)
Windows NT 10.0 build 14393 (arch x64)
msvc 180031101 0

mimikatz # sekurlsa::minidump G:\depurando\ls6\ls6.dmp
Switch to MINIDUMP : 'G:\depurando\ls6\ls6.dmp'

mimikatz # sekurlsa::logonpasswords
Opening : 'G:\depurando\ls6\ls6.dmp' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

mimikatz #
```
before the last change worked well.

thank you Benjamin.

**Comment by gentilkiwi** [comment]
Thanks for report and good start on precisions (see: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue ) :)

Please, specify information on DMP source, especially age of plateform/update status.
Don't hesitate to send me the DMP.

**Comment by jun0s** [comment]
Sorry, this dump file it´s old (almost two years)... i suppose that this "Microsoft Windows Server 2012 R2 Essentials, (6.3.9600.16384)" but i can´t be sure, because i don´t remember where i get the file. 

 And is a "producction server" i can´t share :(

**Comment by gentilkiwi** [comment]
You can try to use `mimilib` in WinDBG x64.

**Comment by jun0s** [comment]
windbg mode works!!

**Comment by gentilkiwi** [comment]
Can you send me the result of: `uf lsasrv!WLsaEnumerateLogonSession` ?
It's only function code, no data inside.

**Comment by jun0s** [comment]
of course...!

[WLsaEnumerateLogonSession.txt](https://github.com/gentilkiwi/mimikatz/files/505162/WLsaEnumerateLogonSession.txt)

**Comment by gentilkiwi** [comment]
Is there any address where I can send you a private build for you to test ? :)

**Comment by jun0s** [comment]
yes, at mor.ph@hotmail.com
