### ISSUE TITLE
Windows cannot access the specified device,path,or file

### ISSUE THREAD

**Issue by uamj** [gentilkiwi/mimikatz#68]
I can open mimikatz 32 bit version.
But i got the error everytime i open mimikatz 64 bit version.
I tried running it as administrator
any help?

**Comment by gentilkiwi** [comment]
Hello,

I invite you to consult https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue and to give a little bit more informations :)

**Comment by uamj** [comment]
Windows 7 Professional x64
mimikatz 2.1 x64  20161005
Im running it with administrator
![download 1](https://cloud.githubusercontent.com/assets/23019743/19666041/f2aa9062-99fc-11e6-9226-0e785e18a2bb.jpg)

**Comment by gentilkiwi** [comment]
Especially this part: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#check-you-dont-have-a-paranoid-security-product ;)
Try it in a clean VM by example.
