### ISSUE TITLE
Mimikatz lsass.dmp Error

### ISSUE THREAD

**Issue by str4n63r** [gentilkiwi/mimikatz#69]
When I am trying to dump credentials from lsass.dmp using Mimikaz it is giving me below error.

**kuhl_m_sekurlsa_acquireLSA ; Memory opening**

What does that mean?

**Comment by gentilkiwi** [comment]
Hello,

I invite you to use the latest mimikatz release, and to post as much you can informations indicated in https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue
