### ISSUE TITLE
Tool does not show password on 2012 R2

### ISSUE THREAD

**Issue by kirillkovalenko** [gentilkiwi/mimikatz#70]
I'm playing with the mimikatz 2.1 (x64) built on Oct  5 2016 20:44:55 on a fully patched 2012R2 box in my lab.

I've logged in on the box with user alice (who has administrative rights) and run `privilege::debug` and `sekurlsa::logonpasswords`. I've got a bunch of records. There are two records that belong to alice, but password is not reviled. I expect to see clear text password somewhere, but there is only `(null)`.

The log file is attached hereto. 

Am I missing something obvious?

[mimikatz.zip](https://github.com/gentilkiwi/mimikatz/files/548197/mimikatz.zip)

**Comment by gentilkiwi** [comment]
Hello :)

I invite you to take a look at https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#be-logic (Be Logic) part
