### ISSUE TITLE
Extract private key from smart card appear to be succeeded, but cannot use

### ISSUE THREAD

**Issue by Daniel-league** [gentilkiwi/mimikatz#71]
I have used this great tool to extract the private key from smart card ,it seems the output that is ok ,but when I imported to the certification store ,no private key only the certificate. please help ,thanks

**Comment by Daniel-league** [comment]
The screen

**Comment by Daniel-league** [comment]
The screen

**Comment by Daniel-league** [comment]
The screen

**Comment by Daniel-league** [comment]
The screen

**Comment by Daniel-league** [comment]
The screen

**Comment by Daniel-league** [comment]
The screen

**Comment by gentilkiwi** [comment]
Hi Daniel,

I think I've missed this issue !
I already seen such behavior with SmartCard CSPs:
- https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#be-logic
- https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#certificates (remarks part)

Of course, a software patch cannot modify a smartcard behavior ;)
- https://github.com/gentilkiwi/mimikatz/wiki/module-~-crypto#capi

This patch only deal with standard RSA CSP :)
You can check standard export test with the `certutil -user -exportpfx ...` command.

By the way:
- `privilege::debug` isn't needed for CAPI patch (only for CNG)
- `/systemstor` is misspelled, it's `/systemstore` (and you don't need it for `CURRENT_USER`)
- `/store:my` isn't needed, `My` is the default one ;)
