### ISSUE TITLE
[Question] What can we get of this

### ISSUE THREAD

**Issue by AlexandreBR3N** [gentilkiwi/mimikatz#72]
https://github.com/AlexandreBR3N/anti_debug

Hi this is my piece of code that i stolen from a book. certificate_steal and cert_export. 
Anyway i just want to share this piece of information. anyway i will close my question. 

But ii really want to know why both extract diff. certificates. I think it just extract RSA

The certificate_steal is more interesting because i treats of a windows bug.

**Comment by gentilkiwi** [comment]
It really looks like _your_:

- [certificate_steal.cpp](https://github.com/AlexandreBR3N/anti_debug/blob/380e5d0431e7bb6cd51271ac3b3bf08acda7f8f4/certificate_steal.cpp) is from @geffner excellent code/research [exportable_rsa_keys.pdf](https://www.nccgroup.trust/globalassets/our-research/uk/whitepapers/exporting_non-exportable_rsa_keys.pdf)...
- [certificate_export.cpp](https://github.com/AlexandreBR3N/anti_debug/blob/0a32a37b43112d5a384059911be980a45769efe1/certificate_export.cpp) is from @idrassi cool sample [CAPI_KEYGEN.cpp](https://www.idrix.fr/Root/Samples/CAPI_KEYGEN.cpp)

These two codes have two different objectives and functioning.
I encourage you at first to understand the _normal_ behavior of [CAPI_KEYGEN.cpp](https://www.idrix.fr/Root/Samples/CAPI_KEYGEN.cpp) then  [exportable_rsa_keys.pdf](https://www.nccgroup.trust/globalassets/our-research/uk/whitepapers/exporting_non-exportable_rsa_keys.pdf).

**Comment by AlexandreBR3N** [comment]
Thanks u so much sorry for anything but im appreciate your response thanks for mimikatz
