### ISSUE TITLE
VC 2008 solution file

### ISSUE THREAD

**Issue by slacker69** [gentilkiwi/mimikatz#73]
I was wondering if you can add a solution file for MSVC2008, if its not to hard to save as/export to. My computer is running slow enough as it is; don't want to have to upgrade to MSVC2010, cause my computer might not survive

**Comment by gentilkiwi** [comment]
I agree for 2010 :) I can recommend you to use 2012 :)
Unfortunately, VS 2008 is not compatible with XML project trick I use.
