### ISSUE TITLE
Can't retrieve Win 10 scheduled task password

### ISSUE THREAD

**Issue by flacostec** [gentilkiwi/mimikatz#74]
Hello,

DPAPI nor Credman seems to be able to dump stored password for scheduled task on Windows 10. I've seen you made some progress in 2013 but haven't found the second part. 

http://blog.gentilkiwi.com/securite/mimikatz/sekurlsa-credman-planificateur-taches

Is it already incoporated somewhere or is it still a WIP ? 

Thanks

**Comment by gentilkiwi** [comment]
Hi,

My answer was too long, so I made a little post: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-scheduled-tasks-credentials !

**Comment by flacostec** [comment]
Oh, I've just tested it and it worked! C'est merveilleux ! Merci pour votre excellent travail.
