### ISSUE TITLE
can not get password

### ISSUE THREAD

**Issue by hostbob** [gentilkiwi/mimikatz#75]
Nice project mate, keep it up

How do i figure out pass in this log?

* Password : 01 00 00 00 d0 8c 9d df 01 15 d1 11 8c 7a 00 c0 4f c2 97 e
b 01 00 00 00 0a 0b 18 59 89 ef 7c 49 92 d1 5a f0 b7 ad fe 99 00 00 00 00 18 00
00 00 57 00 49 00 4e 00 49 00 4e 00 45 00 54 00 43 00 72 00 65 00 64 00 00 00 03
 66 00 00 c0 00 00 00 10 00 00 00 1e 6e 93 34 de 75 2b 7d ec 29 3d ab 27 41 5b 4
3 00 00 00 00 04 80 00 00 a0 00 00 00 10 00 00 00 01 69 ee 21 79 02 ac 35 c2 5c
0d 6d 0a 2f 84 c0 30 00 00 00 72 5e 76 21 1e 6d f7 c2 fd 07 84 e1 d6 2a f9 df 3a
 a7 81 67 6a 2b 65 41 bf d7 e7 81 03 24 3b c6 79 9c 07 39 57 8d 0f a8 0f ed e4 1
2 1f 4d 10 ac 14 00 00 00 b8 50 35 69 6d f7 54 c2 14 ed 5c b9 39 22 75 d9 da cc
37 a2

How do i can i export logs to text?

Thanks

**Comment by gentilkiwi** [comment]
I doubt this can be the binary form of a password.
So, please, can you give enough informations? (like in: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue)

**Comment by hostbob** [comment]
the logs i have are too long, is there command i can use to export the logs so i can attach here to really know what is going on?

**Comment by gentilkiwi** [comment]
Take a look at this part: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#paste-the-full-log-file ;)

**Comment by hostbob** [comment]
ok bro, thanks i was able to get the pass by using mimikatz log export.

Nice job mate like the project
