### ISSUE TITLE
Compile time error: The OutputPath property is not set for project 'mimidrv.vcxproj'.

### ISSUE THREAD

**Issue by slacker69** [gentilkiwi/mimikatz#76]
Using Microsoft Visual Studio 2010; v10.0.30319.1; .NET 4.0.30319
Windows XP
3 of the 4 projects compile just fine. The mimidrv project is the one that isn't compiling.
2>------ Build started: Project: mimidrv, Configuration: Release Win32 ------
2>Build started 1/14/2017 1:12:00 PM.
1>Build started 1/14/2017 1:12:00 PM.
2>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(483,9): error : The OutputPath property is not set for project 'mimidrv.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
2>
2>Build FAILED.

**Comment by gentilkiwi** [comment]
Did you read: https://github.com/gentilkiwi/mimikatz#build ?

**Comment by slacker69** [comment]
Yeah I think that might be it, I didn't install the correct driver kit.
