### ISSUE TITLE
crypto::cng ERROR on win8/win10/win2012

### ISSUE THREAD

**Issue by lidm1989** [gentilkiwi/mimikatz#79]
crypto::cng works well on win7/win2008, but not on win8/win10/win2012.

**Comment by gentilkiwi** [comment]
Hello,

Can you please be more explicit ? :) (see: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue )

**Comment by lidm1989** [comment]
Sorry, 
Please reference [FreerRDP](https://github.com/FreeRDP/FreeRDP/wiki/Mimikatz).
When I follows the steps, crypto:cng got an error `ERROR kull_m_patch_genericProcessOrServiceFromBuild ; kull_m_patch (0x00000000)`.
Remember to forbid Windows Defender.

Versions:
Windows: Windos 8.1 Enterprise/Windows 10 Enterprise/Windows Server 2012 R2 standard.
mimikatz: 20170121

**Comment by gentilkiwi** [comment]
There is a lots of chance that this kind of private keys are not CNG (you can check by listing them).
`kull_m_patch (0x00000000)` indicate that pattern cannot be found: usually because service already patched.

A lots of info are missing to help (see wiki page)

**Comment by lidm1989** [comment]
Oh, yeah,
I redo after reboot. It works well on win8/win10 on the first time after reboot. But not on windows server 2012 r2.

**Comment by gentilkiwi** [comment]
![cng_2k12r2](https://cloud.githubusercontent.com/assets/2307945/22846774/72a7b1e0-efe9-11e6-9f73-bfd15f139909.png)

**Comment by Kuzirashi** [comment]
After uninstalling Avast (even before reboot) command magically worked. So just get rid of it.
