### ISSUE TITLE
lsadump::sam -> Offline mode seems broken

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [gentilkiwi/mimikatz#80]
Offline mode seems to be ignored:
Using copied versions of the SAM and System files or with the `reg save HKLM\SYSTEM SystemBkup.hiv
reg save HKLM\SAM SamBkup.hiv` command. 

They all give the no permissions error: `ERROR kull_m_registry_OpenAndQueryWithAlloc ; kull_m_registry_RegOpenKeyEx KO
ERROR kuhl_m_lsadump_getUsersAndSamKey ; kull_m_registry_RegOpenKeyEx SAM Accounts (0x00000005)`

If I elevate it with `token::elevate`, it will just print out info for the current machine, not the inputed files.

Running on a Windows 10 machine, and the offline files I tried are from both 7 and 10.

**Comment by gentilkiwi** [comment]
Offline mode is not broken... Wiki is ;)

You must use: `/system:<your SYSTEM hive>` and `/sam:<your SAM hive>`

**Comment by AddaxSoft** [comment]
@gentilkiwi - I was looking to correct the wiki, but I can't seem to contribute to it. Can you please fix it as google search lands there? :)
