### ISSUE TITLE
NOT WORKING SINCE WINDOWS 10 UPDATES

### ISSUE THREAD

**Issue by Blackbeard1st** [gentilkiwi/mimikatz#81]
After the Updates a few days ago, it wont show the password now. Befor all workted pefectly.
Problem: ...
**The "tspkg :" is empty** 

  .#####.   mimikatz 2.1 (x64) built on Jan 21 2017 01:22:06
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 20 modules * * */

mimikatz # Privilege '20' OK

mimikatz # 
Authentication Id : 0 ; 10012845 (00000000:0098c8ad)
Session           : Interactive from 3
User Name         : Orlando
Domain            : P23022
Logon Server      : P23022
Logon Time        : 16.03.2017 15:04:21
SID               : S-1-5-21-3664216913-2383559531-550671219-1001
	msv :	
	 [00000003] Primary
	 * Username : Orlando
	 * Domain   : P23022
	 * NTLM     : 5e2993dee5d055a15b1572d77211c4f7
	 * SHA1     : e5230b7d06c17b3844d3a97017256fa4abb76ff5
	tspkg :	
	wdigest :	
	 * Username : Orlando
	 * Domain   : P23022
	 * Password : (null)
	kerberos :	
	 * Username : Orlando
	 * Domain   : P23022
	 * Password : (null)
	ssp :	
	credman :	

Hope for an Fix.

**Comment by KiUserExceptionDispatcher** [comment]
Agree. W10 LTSB not working.

**Comment by gentilkiwi** [comment]
wow, certainly one of the worst 'issue' declaration I had to read...
- [x] LTSB 2015 10240 x86 pre March update
- [x] LTSB 2015 10240 x64 pre March update
- [x] LTSB 2016 x86 pre March update
- [x] LTSB 2016 x64 pre March update

And after update:
- [x] LTSB 2015 10240 x86 post March update
- [x] LTSB 2015 10240 x64 post March update
- [x] LTSB 2016 x86 post March update
- [x] LTSB 2016 x64 post March update

In all cases, no data in `mimikatz` TsPkg part... and it's normal, see #40
Structures (and passwords) now appear in TsPkg part when you enable Credentials Delegation

Also tested after enabled Credentials Delegation:
- [x] LTSB 2015 10240 x86 post March update
- [x] LTSB 2015 10240 x64 post March update
- [x] LTSB 2016 x86 post March update
- [x] LTSB 2016 x64 post March update

Passwords are here

**Comment by Blackbeard1st** [comment]
Should i need to enable the Credentials Delegation manually ? cause i don't know how to if necessery.
plus

the values are not set at:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\Credssp\PolicyDefaults 

 i cant find CredentialsDelegation in my registry in that path
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation <--

so if we could fix these by manually enable Credentials Delegation in Registry it wold be nice trough commands in cmd or powershell.

thx. -> gentilkiwi
