### ISSUE TITLE
Compile for PS Invoke-Mimikatz

### ISSUE THREAD

**Issue by daniel0x00** [gentilkiwi/mimikatz#83]
Hi Benjamin. 

I'm trying to build the last version of your tool to PS, selecting the release 'Second_Release_PowerShell' and by base64 the dll with linux by using 'base64 -w 0 powerkatz.dll > base64.txt' command. Then replacing the $PEBytes64 var in Invoke-Mimikatz.ps1. Problem is when I run it, PS window just crash closes. Do you have an idea of why? 

Thanks in advance!

**Comment by gentilkiwi** [comment]
Hi Daniel,

Thank you for the report.
Because of some RPC stuff, I was ending the process too soon to let PowerShell knows about the result.
It will be back soon ;) (already fixed but I've other stuff to push ;))

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Tous droits réservés.

PS C:\Users\gentilkiwi> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
PS C:\Users\gentilkiwi> . .\Desktop\Invoke-Mimikatz.ps1
PS C:\Users\gentilkiwi> Invoke-Mimikatz -Command version

  .#####.   mimikatz 2.1.1 (x64) built on Mar 25 2017 14:01:06
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 21 modules * * */

mimikatz(powershell) # version

mimikatz 2.1.1 (arch x64)
Windows NT 10.0 build 14393 (arch x64)
msvc 150030729 207
```

**Comment by daniel0x00** [comment]
Ok Benjamin, thank you for your support. We all love your tool 😃

Best regards!
Daniel.
