### ISSUE TITLE
[Question] Meaning Unk-Key and Encrypted in sekurlsa::logonpasswords in "msv" section

### ISSUE THREAD

**Issue by CDpon** [gentilkiwi/mimikatz#84]
Hello! Could you please explain what is means Unk-Key and Encrypted in sekurlsa::logonpasswords in "msv" section?

**Comment by gentilkiwi** [comment]
It seems that `Unk-key` is a subkey encrypted by `LsaIso` in VSM needed to decrypt `Encrypted` data (NTLM hash among others)
