### ISSUE TITLE
Error getting passwords on windows 10 x64.

### ISSUE THREAD

**Issue by chris001** [gentilkiwi/mimikatz#86]
```
mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonPasswords full
ERROR kuhl_m_sekurlsa_acquireLSA : Handle on memory (0x00000005)

mimikatz # version
mimikatz 2.1.1 (arch x64)
Windows NT 10.0 build 14393 (arch x64)
msvc 150030729 207

mimikatz # 
```

Help?  How to properly get passwords on Windows 10.
I understand it is necessary to use many commands in a `.bat` file, because passwords are no longer kept in memory.  
Could you share this `.bat` file.

**Comment by gentilkiwi** [comment]
A `.bat` file? Really?

If you are admin (you seems to be because of the `DEBUG` privilege) but you can't access `LSASS` process (5 = access denied), a lots of chances:
- `LSASS` is running as a protected process ;
- A security product prevent your access.

**Comment by chris001** [comment]
Avast antivirus is installed, although it is disabled temporarily, to permit mimikatz to run.
When Avast antivirus is running, it blocks mimikatz from being downloaded to disk!

**Comment by gentilkiwi** [comment]
I can confirm you that Avast, among others products, is not fully disabled when you disable it.

**Comment by chris001** [comment]
Are you saying, I must uninstall avast, and then, this mimikatz will work correctly on windows 10 x64?

**Comment by gentilkiwi** [comment]
I'm only saying what's the product's behavior. But you do what you want :)

**Comment by chris001** [comment]
OK but were you able to get mimikatz to work successfully on windows 10 x64 with only the default system protection app, windows defender?

**Comment by wolf0x** [comment]
pls try to disable UAC and you would get it works.

**Comment by pixel-hustler** [comment]
Hi,

same as above, Win 10 64bit, only 1 admin user. I have disabled UAC.
Few seconds after inserting rubber ducky, mimikatz starts as it supposed to, but getting an error.

![mem-error](https://user-images.githubusercontent.com/32702092/36073942-9014f186-0f30-11e8-9105-fe60da4b094e.gif)

**Comment by chris001** [comment]
@vletoux 
After so many security improvements in Windows, including the recent Meltdown fix causing the complete separation of kernel address space from user address space, etc, is this method used by mimikatz even working for anyone on Windows x64 anymore?
