### ISSUE TITLE
Non-Unicode Credentials

### ISSUE THREAD

**Issue by MrAnde7son** [gentilkiwi/mimikatz#87]
Hi,

I noticed that sekurlsa module ignores non-unicode characters and displays nothing in case either the username or the password configured differently.
In the image attached, you can see a screen shot of dumping credentials, the username and password were written in Hebrew, so they do not appear in the dump.

![nopass](https://cloud.githubusercontent.com/assets/15673250/25804860/0830a4fa-3406-11e7-87c9-d36d518713c5.png)

**Comment by wwbbs** [comment]
Are you sure they are missing and not just a character set problem. Try
piping output to a file and check.

**Comment by gentilkiwi** [comment]
Or use an unicode font in the console ;) (like `Consola`)

**Comment by MrAnde7son** [comment]
Piped the output to a log file, and it still ignores the Hebrew letters.
In mimikatz source code, it casts the username to UNICODE_STRING structure, so I don't think you can put in it non Latin language characters.

![nopass](https://cloud.githubusercontent.com/assets/15673250/25808712/99ff97c6-3413-11e7-8396-96bf9d1cb18b.png)

**Comment by wwbbs** [comment]
Then it is a character set issue, Can those same characters be displayed /
entered into the console your using?

**Comment by gentilkiwi** [comment]
Use a font like `Courier New`
![mimi_hebrew](https://cloud.githubusercontent.com/assets/2307945/25810792/7c896da4-3411-11e7-909c-cd473c1dc0a2.png)
of course, it's mixed with reverse order ;)

**Comment by MrAnde7son** [comment]
How come the result changes depending on the font?

**Comment by gentilkiwi** [comment]
Results don't vary, a byte is a byte.
Windows console is not a perfect model when handling international chars.

All Windows fonts are not able to render output in hebrew.
Especially when using UNICODE encoding (and not OEM).

**Comment by MrAnde7son** [comment]
I see. Thanks!
