### ISSUE TITLE
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

### ISSUE THREAD

**Issue by sayak-brm** [gentilkiwi/mimikatz#90]
Hi, When trying to run mimikatz through the Invoke-Mimikatz.ps1 it gives the following error:
```

  .#####.   mimikatz 2.1 (x64) built on Nov 10 2016 15:31:14
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 20 modules * * */
ERROR mimikatz_initOrClean ; CoInitializeEx: 80010106

mimikatz(powershell) # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

mimikatz(powershell) # exit
Bye!
```

**Comment by sayak-brm** [comment]
Win10 x64 with Creators Update. Executed via admin PowerShell

**Comment by gentilkiwi** [comment]
Hello :)

Maybe take a look at: https://github.com/gentilkiwi/mimikatz/wiki/howto-~-open-an-issue#check-you-use-latest-mimikatz-version
And try first with an original version of `mimikatz` ;)

**Comment by sayak-brm** [comment]
I downloaded the latest version and tried with it, but I got the same
results. :(

**Comment by gentilkiwi** [comment]
I need more information ;) as mentionned in the previous link.
FYI, I use an up to date Windows 10 CU and `mimikatz` works like a charm on it.

**Comment by dhagrow** [comment]
I'm not sure if it's related, but I'm seeing the same error on:

    Microsoft Windows 8.1 Pro (6.3.9600 Build 9600) x86 English

SP0 & SP1 (But not on 8.0, or 8.1 x64)

This is executed directly, not using Powershell.

```
  .#####.   mimikatz 2.1.1 (x86) built on Jun 18 2017 18:46:12
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 21 modules * * */

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list
```

**Comment by gentilkiwi** [comment]
Hmm, just tested with an up to date 8.1 x86 ... (check: `version /full`)
![81](https://user-images.githubusercontent.com/2307945/27357559-ef35ca1e-5612-11e7-8eb5-321ea3669582.png)

**Comment by dhagrow** [comment]
It looks like an issue with older versions of 8.1 then.

SP0 (fresh install):
![mimikatz-win81-error](https://user-images.githubusercontent.com/987294/27386235-23f872ce-5663-11e7-8864-bae50ff070be.png)

SP1
![mimikatz-win81-sp1-error](https://user-images.githubusercontent.com/987294/27386250-2d5b9a26-5663-11e7-9761-5623f5764603.png)

**Comment by gentilkiwi** [comment]
I rarely support fresh Windows install without any update (not the real life env.)
Sayak, can you post: `version /full`

**Comment by huzaifa-007** [comment]
same problem windows 10 64-bit Creator update;
invoke-mimkatz gave me the same error but the full version worked ...(at least without errors)

**Comment by edussousa** [comment]
It may seem like a silly contribution, but I arrived here with the same error and when I remembered to use "privilege::debug" before "sekurlsa::logonpasswords" magically it worked again. And, I can see that the guy who asked the question didn't use it either! :-)
