### ISSUE TITLE
lsadump::sam

### ISSUE THREAD

**Issue by Banaanhangwagen** [gentilkiwi/mimikatz#93]
Hey,
I am trying to understand what this module does when faced with Microsoft online account, and there is no NTLM stored like with local accounts.

It searches for a cached value, I suppose, but how, and what happens exactly?

Maybe one can point me to the right codeline on this [page?](https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kuhl_m_lsadump.c)
Any technical doc/blog/white paper about this?

Thanx

**Comment by dcnoren** [comment]
If I understand your question properly, I think you're looking for a password to dump when the user doesn't have an actual password and is using Windows Hello instead? Given that MS is moving towards certificates for this, you need to dump a certificate and private key instead. Try:

crypto::capi
crypto::cng
crypto::certificates /export
