### ISSUE TITLE
kuhl_m_sekurlsa_acquireLSA ; Handel on memory (0x0000005)

### ISSUE THREAD

**Issue by Itschi** [gentilkiwi/mimikatz#94]
Hey,

I get this Error Message always when I use sekurlsa::LogonPasswords
Tested on version 2.1.1 20170618 and 2.1.1 20170607.

Win 7 SP 1 Professional x64

**Comment by Itschi** [comment]
![print](https://user-images.githubusercontent.com/30163148/28192845-165014dc-6839-11e7-83e8-d8160f6a56bd.png)

**Comment by esfomeado** [comment]
I have the same problem on one of my machines.

**Comment by rafaelbrasilia** [comment]
Having the same problem here using a dump from a Windows 10 machine.

**Comment by TalkL3ss** [comment]
runas admin + privilege::debug?

**Comment by esfomeado** [comment]
Yes @TalkL3ss

**Comment by gentilkiwi** [comment]
Do not forget about full output (privilege::debug not on your screenshot), and to deal with your security products...
