### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by umeharasang** [gentilkiwi/mimikatz#96]
when I build the project, I got 2 part failed.
1.FROM MIMIDRV:C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(609,5): error : The OutputPath property is not set for project 'mimidrv.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
2.FROM MIMIKATZ:>modules\kuhl_m_net.c : error C2220: warning treated as error - no 'object' file generated
1>modules\kuhl_m_net.c : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

I already installed WinDDK and I use VS2010, don't know why this happened

**Comment by gentilkiwi** [comment]
I maybe forgot some local character in C files. Do not hesitates to remove it to be able to compile.
