### ISSUE TITLE
Dump copied SAM/SYSTEM files

### ISSUE THREAD

**Issue by Penetant-Tangent** [gentilkiwi/mimikatz#97]
I have copied the SAM and SYSTEM files from a windows 10 anniversary edition computer onto my own, and can't figure out how to dump the hashes. When I try lsadump::sam, it only dumps my own hashes. What should I do?

**Comment by marcusguita** [comment]
Try to use this sintaxe: lsadump::sam /system:SYSTEM.hiv /SAM:SAM.hiv

(SYTEM.hiv and SAM,hiv are your dump files)

**Comment by marianoka** [comment]
Hi!
I'm getting the same issue.
mimikatz # lsadump::sam /system:SYSTEM.hiv /SAM:SAM.hiv
ERROR kuhl_m_lsadump_sam ; CreateFile (SYSTEM hive) (0x00000002)
Files are located at root directory where mimikatz  is . (c:\mimikatz)
Any idea?

Thanks

**Comment by willmendil** [comment]
https://www.ultimatewindowssecurity.com/blog/default.aspx?p=c2bacbe0-d4fc-4876-b6a3-1995d653f32a

> We do this by running “privilege::debug” and then “token::elevate”.
